import type { ExplanationLanguage, LocalizedField } from './types'

export const languageNames: Record<ExplanationLanguage, string> = {
  en: 'English',
  fr: 'Français',
}

export function getLocalizedText(
  text: LocalizedField,
  language: ExplanationLanguage,
) {
  return typeof text === 'string' ? text : text[language]
}

export const uiCopy = {
  en: {
    explanationLabel: 'Explanation',
    languageToggleLabel: 'Explanation language',
    nav: {
      siteNavLabel: 'Main navigation',
      home: 'Home',
      pinyin: 'Pinyin',
      journey: 'Journey',
      culture: 'Culture',
    },
    courseSeries: {
      label: 'Course series',
      pinyinTitle: 'Mandarin tones and pinyin',
      basicExpressionsTitle: 'Useful sentences, expressions and Hanzi recognition',
      cultureTitle: 'Culture advice for travelers in China',
    },
    culturePage: {
      heading: 'Culture advice for travelers in China',
      subtitle: 'Practical etiquette and customs for a smooth trip',
      tablistLabel: 'Culture topics',
    },
    homePage: {
      heading: '轻松学中文',
      heroSlogan: 'Basic Chinese expressions for a stress-free travel',
      lessonEyebrow: 'Lesson',
      openLesson: 'Open lesson',
      comingSoon: 'Coming soon',
      previewPeek: 'Peek inside',
      previewHide: 'Hide preview',
      previewGoalLabel: 'Goal',
      previewKeyPhraseLabel: 'Key phrase',
      previewMeaningLabel: 'Meaning',
      lessonListLabel: 'Lesson list',
      learningHighlightsLabel: 'Learning highlights',
      heroPhraseLabel: 'Hero phrase',
      learningMockupLabel: 'Learning preview mockup',
      courseProgressSummaryLabel: 'Course progress summary',
      mockupListenLabel: 'Listen',
      lessonCount: (count: number) => `${count} ${count === 1 ? 'lesson' : 'lessons'}`,
      completedLessonCount: (count: number) => `${count} complete`,
      reviewCount: (count: number) => `${count} review`,
      lessonScenarioBadges: {
        'daily-greetings': 'Greetings',
        'self-intro': 'Arrival',
        'ask-directions': 'Taxi',
        'order-food': 'Hotel',
        'phone-and-payment': 'SIM card',
        'convenience-store-run': 'Shopping',
        'restaurant-order': 'Restaurant',
        'metro-ticket': 'Metro',
        'pharmacy-help': 'Emergency',
        'ask-for-help-problem': 'Help',
        'train-station-ticket': 'Train',
        'small-talk': 'Small talk',
      },
    },
    lessonPage: {
      notFoundEyebrow: 'Lesson not found',
      notFoundHeading: 'We couldn’t find that lesson.',
      dialogue: 'Phrases',
      sentencePatterns: 'Useful patterns',
      vocabulary: 'Vocabulary',
      goToPractice: 'Go to practice',
      backToHome: 'Back to home',
      speakerPrefix: 'Speaker',
      listenChinese: 'Play Chinese',
      lessonActions: 'Lesson actions',
      lessonProgressPreviewLabel: 'Lesson progress preview',
      dialoguePracticeLabel: 'Dialogue practice',
      dialogueLineLabel: (speaker: string) => `Dialogue line speaker ${speaker}`,
    },
    practicePage: {
      eyebrow: 'Practice',
      notFoundEyebrow: 'Practice not found',
      notFoundHeading: 'We couldn’t find that practice set.',
      backToLesson: 'Back to lesson',
      goToReview: 'Go to review',
      viewProgress: 'View progress',
      practiceActions: 'Practice actions',
    },
    practiceChallenge: {
      playPromptAudio: (current: number) => `Play the audio for question ${current}`,
      playOptionAudio: (option: string) => `Play ${option}`,
      answerOptions: 'Answer options',
      correctFeedback: 'Correct!',
      incorrectFeedback: 'Not quite.',
      correctAnswer: (answer: string) => `Answer: ${answer}`,
      nextQuestion: 'Next question',
      playAgain: 'Play again',
      completeLesson: 'Complete lesson',
      lessonCompleted: 'Lesson complete. Review cards are ready.',
      answerReview: 'Your answers',
      answerReviewCorrect: 'Correct',
      answerReviewIncorrect: 'Incorrect',
    },
    reviewPage: {
      eyebrow: 'Review',
      heading: 'Review',
      cardsDueToday: (count: number) => `Cards due today: ${count}`,
      front: 'Front',
      back: 'Back',
      markComplete: 'Mark complete',
      finishedCount: (count: number) => `${count} ${count === 1 ? 'card finished.' : 'cards finished.'}`,
      queueClear: 'Queue clear',
      noCards: 'No cards due right now.',
      startLearning: 'Start learning',
      viewProgress: 'View progress',
      reviewActions: 'Review actions',
      currentFlashcardLabel: 'Current review flashcard',
      frontSideLabel: 'Flashcard front',
      backSideLabel: 'Flashcard back',
      statusPanelLabel: 'Review status panel',
      dueNow: 'Due now',
      completedNow: 'Completed now',
    },
    progressPage: {
      eyebrow: 'Progress',
      heading: 'Progress',
      summaryLabel: 'Learning path summary',
      statsLabel: 'Learning indicators',
      progressActionsLabel: 'Progress actions',
      nextStepEyebrow: 'Next step',
      completedLessonsLabel: 'Completed lessons',
      masteryLabel: 'Course mastery',
      completedSummary: (done: number, total: number) =>
        `${done} of ${total} lesson${total === 1 ? '' : 's'} completed`,
      currentLesson: 'Current lesson',
      notStartedYet: 'Not started yet',
      startLearning: 'Start learning',
      reviewQueue: 'Review queue',
      reviewItemsWaiting: (count: number) =>
        `${count} review item${count === 1 ? '' : 's'} waiting`,
      lessonStatusComplete: 'Complete',
      lessonStatusCurrent: 'Current',
      lessonStatusUpcoming: 'Upcoming',
      lessonStatusPreview: 'Preview',
      previewDisplayOnly: 'Display-only preview',
      openLesson: 'Open lesson',
      openJourneyLesson: (title: string) => `Open ${title}`,
      goToReview: 'Go to review',
    },
    pinyinPage: {
      heading: 'Pinyin（Mandarin Phonetic System）',
      syllableIntro: {
        description:
          'Pinyin is the official phonetic system for learning Mandarin Chinese. A syllable can consist of an initial, a final, and a tone. Tones change the meaning of words.',
        figureLabel:
          'Pinyin syllable composition example: mā consists of initial m, final a, and the first-tone mark.',
        pinyinLabel: 'Pinyin',
        initialLabel: 'Initial',
        finalLabel: 'Final',
        toneLabel: 'Tone',
      },
      sectionProgress: (done: number, total: number) =>
        `${done} of ${total} section${total === 1 ? '' : 's'} complete`,
      playReferenceAudio: (label: string) => `Play ${label}`,
    },
    contentState: {
      errorEyebrow: 'Content unavailable',
      errorHeading: 'We couldn’t load the course.',
      errorBody: 'Check your connection and try again.',
      retry: 'Retry',
    },
    common: {
      explanation: 'Explanation',
    },
  },
  fr: {
    explanationLabel: 'Explication',
    languageToggleLabel: 'Langue d’explication',
    nav: {
      siteNavLabel: 'Navigation principale',
      home: 'Accueil',
      pinyin: 'Pinyin',
      journey: 'Parcours',
      culture: 'Culture',
    },
    courseSeries: {
      label: 'Séries de cours',
      pinyinTitle: 'Tons et pinyin du mandarin',
      basicExpressionsTitle: 'Expressions chinoises essentielles pour voyager sereinement',
      cultureTitle: 'Conseils culturels pour les voyageurs en Chine',
    },
    culturePage: {
      heading: 'Conseils culturels pour les voyageurs en Chine',
      subtitle: 'Étiquette et coutumes pratiques pour un voyage serein',
      tablistLabel: 'Sujets culturels',
    },
    homePage: {
      heading: '轻松学中文',
      heroSlogan: 'Apprenez les dialogues essentiels pour voyager en Chine',
      lessonEyebrow: 'Leçon',
      openLesson: 'Ouvrir la leçon',
      comingSoon: 'Bientôt',
      previewPeek: 'Voir un aperçu',
      previewHide: 'Masquer l’aperçu',
      previewGoalLabel: 'Objectif',
      previewKeyPhraseLabel: 'Phrase clé',
      previewMeaningLabel: 'Sens',
      lessonListLabel: 'Liste des leçons',
      learningHighlightsLabel: 'Points clés de l’apprentissage',
      heroPhraseLabel: 'Phrase modèle',
      learningMockupLabel: 'Maquette d’aperçu d’apprentissage',
      courseProgressSummaryLabel: 'Résumé des progrès du cours',
      mockupListenLabel: 'Écouter',
      lessonCount: (count: number) => `${count} leçon${count > 1 ? 's' : ''}`,
      completedLessonCount: (count: number) => `${count} terminée${count > 1 ? 's' : ''}`,
      reviewCount: (count: number) => `${count} à réviser`,
      lessonScenarioBadges: {
        'daily-greetings': 'Salutations',
        'self-intro': 'Arrivée',
        'ask-directions': 'Taxi',
        'order-food': 'Hôtel',
        'phone-and-payment': 'Carte SIM',
        'convenience-store-run': 'Shopping',
        'restaurant-order': 'Restaurant',
        'metro-ticket': 'Métro',
        'pharmacy-help': 'Pharmacie',
        'ask-for-help-problem': 'Aide',
        'train-station-ticket': 'Train',
        'small-talk': 'Conversation',
      },
    },
    lessonPage: {
      notFoundEyebrow: 'Leçon introuvable',
      notFoundHeading: 'Impossible de trouver cette leçon.',
      dialogue: 'Phrases',
      sentencePatterns: 'Structures utiles',
      vocabulary: 'Vocabulaire',
      goToPractice: 'Passer à la pratique',
      backToHome: 'Retour à l’accueil',
      speakerPrefix: 'Interlocuteur',
      listenChinese: 'Écouter le chinois',
      lessonActions: 'Actions de la leçon',
      lessonProgressPreviewLabel: 'Aperçu de progression de la leçon',
      dialoguePracticeLabel: 'Pratique du dialogue',
      dialogueLineLabel: (speaker: string) => `Ligne de dialogue, interlocuteur ${speaker}`,
    },
    practicePage: {
      eyebrow: 'Pratique',
      notFoundEyebrow: 'Pratique introuvable',
      notFoundHeading: 'Impossible de trouver cette série d’exercices.',
      backToLesson: 'Retour à la leçon',
      goToReview: 'Aller à la révision',
      viewProgress: 'Voir les progrès',
      practiceActions: 'Actions de pratique',
    },
    practiceChallenge: {
      playPromptAudio: (current: number) => `Écouter l’audio de la question ${current}`,
      playOptionAudio: (option: string) => `Écouter ${option}`,
      answerOptions: 'Options de réponse',
      correctFeedback: 'Correct !',
      incorrectFeedback: 'Pas tout à fait.',
      correctAnswer: (answer: string) => `Réponse : ${answer}`,
      nextQuestion: 'Question suivante',
      playAgain: 'Rejouer',
      completeLesson: 'Terminer la leçon',
      lessonCompleted: 'Leçon terminée. Les cartes de révision sont prêtes.',
      answerReview: 'Tes réponses',
      answerReviewCorrect: 'Correct',
      answerReviewIncorrect: 'Incorrect',
    },
    reviewPage: {
      eyebrow: 'Révision',
      heading: 'Révision',
      cardsDueToday: (count: number) => `Cartes à revoir aujourd’hui : ${count}`,
      front: 'Recto',
      back: 'Verso',
      markComplete: 'Marquer comme terminée',
      finishedCount: (count: number) => `${count} ${count === 1 ? 'carte terminée.' : 'cartes terminées.'}`,
      queueClear: 'File vide',
      noCards: 'Aucune carte à revoir pour le moment.',
      startLearning: 'Commencer à apprendre',
      viewProgress: 'Voir les progrès',
      reviewActions: 'Actions de révision',
      currentFlashcardLabel: 'Carte de révision en cours',
      frontSideLabel: 'Recto de la carte',
      backSideLabel: 'Verso de la carte',
      statusPanelLabel: 'Panneau d’état de révision',
      dueNow: 'À revoir',
      completedNow: 'Terminées',
    },
    progressPage: {
      eyebrow: 'Progression',
      heading: 'Progression',
      summaryLabel: 'Résumé du parcours',
      statsLabel: 'Indicateurs d’apprentissage',
      progressActionsLabel: 'Actions de progression',
      nextStepEyebrow: 'Prochaine étape',
      completedLessonsLabel: 'Leçons terminées',
      masteryLabel: 'Maîtrise du parcours',
      completedSummary: (done: number, total: number) =>
        `${done} leçon${done > 1 ? 's' : ''} sur ${total} terminée${done > 1 ? 's' : ''}`,
      currentLesson: 'Leçon en cours',
      notStartedYet: 'Pas encore commencée',
      startLearning: 'Commencer à apprendre',
      reviewQueue: 'File de révision',
      reviewItemsWaiting: (count: number) =>
        `${count} carte${count > 1 ? 's' : ''} en attente`,
      lessonStatusComplete: 'Terminée',
      lessonStatusCurrent: 'En cours',
      lessonStatusUpcoming: 'À venir',
      lessonStatusPreview: 'Aperçu',
      previewDisplayOnly: 'Aperçu sans lien',
      openLesson: 'Ouvrir la leçon',
      openJourneyLesson: (title: string) => `Ouvrir ${title}`,
      goToReview: 'Aller à la révision',
    },
    pinyinPage: {
      heading: 'Pinyin（Mandarin Phonetic System）',
      syllableIntro: {
        description:
          'Le pinyin est le système phonétique officiel pour apprendre le mandarin. Une syllabe peut être composée d’une initiale, d’une finale et d’un ton. Les tons changent le sens des mots.',
        figureLabel:
          'Exemple de composition d’une syllabe pinyin : mā se compose de l’initiale m, de la finale a et de la marque du premier ton.',
        pinyinLabel: 'Pinyin',
        initialLabel: 'Initiale',
        finalLabel: 'Finale',
        toneLabel: 'Ton',
      },
      sectionProgress: (done: number, total: number) =>
        `${done} section${done > 1 ? 's' : ''} sur ${total} terminée${done > 1 ? 's' : ''}`,
      playReferenceAudio: (label: string) => `Écouter ${label}`,
    },
    contentState: {
      errorEyebrow: 'Contenu indisponible',
      errorHeading: 'Impossible de charger le cours.',
      errorBody: 'Vérifie ta connexion puis réessaie.',
      retry: 'Réessayer',
    },
    common: {
      explanation: 'Explication',
    },
  },
} as const

export function getUiCopy(language: ExplanationLanguage) {
  return uiCopy[language]
}
