import type { ExplanationLanguage, LocalizedField } from './types'

export const languageNames: Record<ExplanationLanguage, string> = {
  en: 'English',
  fr: 'Français',
}

export function getLocalizedText(
  text: LocalizedField,
  language: ExplanationLanguage,
) {
  return typeof text === 'string' ? text : text[language]
}

export const uiCopy = {
  en: {
    explanationLabel: 'Explanation',
    languageToggleLabel: 'Explanation language',
    selectionPage: {
      eyebrow: 'EN/FR Chinese Entry MVP',
      heading: 'Choose your explanation language',
      lede: 'Learn beginner Chinese through practical scenarios with either English or French guidance.',
      languageOptionsLabel: 'Choose guidance path',
      languageOptionsHeading: 'Choose guidance path',
      languageOptionsDescription: 'Start with the language that makes grammar feel clearest. You can switch anytime.',
      identityLabel: 'Chinese starter phrase',
      identityBadge: 'Light Chinese identity',
      startLearning: 'Start learning',
    },
    homePage: {
      eyebrow: 'Core path',
      heading: 'Home',
      lede: 'Choose one of the three practical lessons, continue where you left off, or jump straight into review.',
      continueLearning: 'Continue learning',
      goToReview: 'Go to review',
      viewProgress: 'View progress',
      lessonEyebrow: 'Lesson',
      openLesson: 'Open lesson',
      lessonListLabel: 'Lesson list',
      learningHighlightsLabel: 'Learning highlights',
      heroPhraseLabel: 'Hero phrase',
      learningMockupLabel: 'Learning preview mockup',
      quickLearningPathsLabel: 'Quick learning paths',
      courseProgressSummaryLabel: 'Course progress summary',
      mockupListenLabel: 'Listen',
      quickEntryContinueMeta: 'Next lesson',
      quickEntryReviewMeta: 'Review queue',
      quickEntryProgressMeta: 'Course map',
      lessonCount: (count: number) => `${count} ${count === 1 ? 'lesson' : 'lessons'}`,
      completedLessonCount: (count: number) => `${count} complete`,
      reviewCount: (count: number) => `${count} review`,
      lessonScenarioBadges: {
        'self-intro': 'Intro',
        'order-food': 'Restaurant',
        'ask-directions': 'Metro',
      },
    },
    lessonPage: {
      eyebrow: 'Lesson',
      notFoundEyebrow: 'Lesson not found',
      notFoundHeading: 'We couldn’t find that lesson.',
      scenarioGoal: 'Scenario goal',
      dialogue: 'Dialogue',
      sentencePatterns: 'Useful patterns',
      vocabulary: 'Vocabulary',
      pronunciation: 'Pronunciation',
      hanziRecognition: 'Hanzi recognition',
      sectionSummary: 'This lesson covers dialogue, patterns, vocabulary, pronunciation, and hanzi recognition.',
      goToPractice: 'Go to practice',
      finishWithShortInput: 'Finish with short input',
      backToHome: 'Back to home',
      speakerPrefix: 'Speaker',
      listenChinese: 'Play Chinese',
      lessonActions: 'Lesson actions',
      lessonOverviewLabel: 'Lesson overview',
      lessonProgressPreviewLabel: 'Lesson progress preview',
      studyLayersCount: (count: number) => `${count} study layers`,
      practiceNext: 'Practice next',
      dialoguePracticeLabel: 'Dialogue practice',
      dialogueLineLabel: (speaker: string) => `Dialogue line speaker ${speaker}`,
    },
    practicePage: {
      eyebrow: 'Practice',
      notFoundEyebrow: 'Practice not found',
      notFoundHeading: 'We couldn’t find that practice set.',
      lede: 'Work through one listening, speaking, and reading step.',
      checklistHeading: 'Today’s checklist',
      checklistLabel: 'Practice checklist',
      listeningReady: 'Listening prompt ready',
      speakingReady: 'Repeat-aloud prompt ready',
      readingReady: 'Reading prompt ready',
      listenAndChoose: 'Listen and choose',
      answer: 'Answer',
      repeatAloud: 'Repeat aloud',
      modelAnswer: 'Model answer',
      selfCheck: 'Self-check: Can you say it once slowly and once at natural speed?',
      matchHanzi: 'Match the hanzi',
      readingGoal: 'Reading goal',
      continueToShortInput: 'Continue to short input',
      backToLesson: 'Back to lesson',
      practiceActions: 'Practice actions',
    },
    shortInputPage: {
      eyebrow: 'Short input',
      notFoundEyebrow: 'Short input not found',
      notFoundHeading: 'We couldn’t find that final step.',
      lede: 'Finish the lesson with one short response and one comprehension check.',
      shortItem: 'Short item',
      targetAnswer: 'Target answer',
      comprehensionPrompt: 'Comprehension prompt',
      comprehensionQuestion: 'What does this answer communicate in the scenario?',
      answerKey: 'Answer key',
      finishButton: 'I finished the short input',
      finishedMessage: 'Lesson complete. Review cards are ready.',
      backToPractice: 'Back to practice',
      goToReview: 'Go to review',
      viewProgress: 'View progress',
      listenChinese: 'Play Chinese',
      shortInputActions: 'Short input actions',
    },
    reviewPage: {
      eyebrow: 'Review',
      heading: 'Review',
      cardsDueToday: (count: number) => `Cards due today: ${count}`,
      front: 'Front',
      back: 'Back',
      markComplete: 'Mark complete',
      finishedCount: (count: number) => `${count} ${count === 1 ? 'card finished.' : 'cards finished.'}`,
      queueClear: 'Queue clear',
      noCards: 'No cards due right now.',
      viewProgress: 'View progress',
      backToHome: 'Back to home',
      reviewActions: 'Review actions',
      currentFlashcardLabel: 'Current review flashcard',
      frontSideLabel: 'Flashcard front',
      backSideLabel: 'Flashcard back',
      statusPanelLabel: 'Review status panel',
      dueNow: 'Due now',
      completedNow: 'Completed now',
    },
    progressPage: {
      eyebrow: 'Progress',
      heading: 'Progress',
      summaryLabel: 'Learning path summary',
      statsLabel: 'Learning indicators',
      lessonProgressLabel: 'Lesson progress',
      progressActionsLabel: 'Progress actions',
      nextStepEyebrow: 'Next step',
      lessonProgressEyebrow: 'Course map',
      completedLessonsLabel: 'Completed lessons',
      masteryLabel: 'Course mastery',
      completedSummary: (done: number, total: number) =>
        `${done} of ${total} lesson${total === 1 ? '' : 's'} completed`,
      currentLesson: 'Current lesson',
      notStartedYet: 'Not started yet',
      reviewQueue: 'Review queue',
      reviewItemsWaiting: (count: number) =>
        `${count} review item${count === 1 ? '' : 's'} waiting`,
      lessonStatusComplete: 'Complete',
      lessonStatusCurrent: 'Current',
      lessonStatusUpcoming: 'Upcoming',
      backToHome: 'Back to home',
      goToReview: 'Go to review',
    },
    common: {
      explanation: 'Explanation',
    },
  },
  fr: {
    explanationLabel: 'Explication',
    languageToggleLabel: 'Langue d’explication',
    selectionPage: {
      eyebrow: 'MVP de chinois débutant EN/FR',
      heading: 'Choisissez votre langue d’explication',
      lede: 'Apprenez le chinois débutant à travers des situations pratiques avec un accompagnement en anglais ou en français.',
      languageOptionsLabel: 'Choisir le parcours d’accompagnement',
      languageOptionsHeading: 'Choisir le parcours d’accompagnement',
      languageOptionsDescription: 'Commencez avec la langue qui rend la grammaire plus claire. Vous pouvez changer à tout moment.',
      identityLabel: 'Phrase de départ en chinois',
      identityBadge: 'Identité chinoise légère',
      startLearning: 'Commencer',
    },
    homePage: {
      eyebrow: 'Parcours principal',
      heading: 'Accueil',
      lede: 'Choisissez l’une des trois leçons pratiques, reprenez où vous vous êtes arrêté ou passez directement à la révision.',
      continueLearning: 'Continuer la leçon',
      goToReview: 'Réviser',
      viewProgress: 'Voir les progrès',
      lessonEyebrow: 'Leçon',
      openLesson: 'Ouvrir la leçon',
      lessonListLabel: 'Liste des leçons',
      learningHighlightsLabel: 'Points clés de l’apprentissage',
      heroPhraseLabel: 'Phrase modèle',
      learningMockupLabel: 'Maquette d’aperçu d’apprentissage',
      quickLearningPathsLabel: 'Accès rapides d’apprentissage',
      courseProgressSummaryLabel: 'Résumé des progrès du cours',
      mockupListenLabel: 'Écouter',
      quickEntryContinueMeta: 'Prochaine leçon',
      quickEntryReviewMeta: 'File de révision',
      quickEntryProgressMeta: 'Carte du cours',
      lessonCount: (count: number) => `${count} leçon${count > 1 ? 's' : ''}`,
      completedLessonCount: (count: number) => `${count} terminée${count > 1 ? 's' : ''}`,
      reviewCount: (count: number) => `${count} à réviser`,
      lessonScenarioBadges: {
        'self-intro': 'Présentation',
        'order-food': 'Restaurant',
        'ask-directions': 'Métro',
      },
    },
    lessonPage: {
      eyebrow: 'Leçon',
      notFoundEyebrow: 'Leçon introuvable',
      notFoundHeading: 'Impossible de trouver cette leçon.',
      scenarioGoal: 'Objectif de la scène',
      dialogue: 'Dialogue',
      sentencePatterns: 'Structures utiles',
      vocabulary: 'Vocabulaire',
      pronunciation: 'Prononciation',
      hanziRecognition: 'Reconnaissance des hanzi',
      sectionSummary: 'Cette leçon couvre le dialogue, les structures, le vocabulaire, la prononciation et les hanzi à reconnaître.',
      goToPractice: 'Passer à la pratique',
      finishWithShortInput: 'Terminer avec la mini-réponse',
      backToHome: 'Retour à l’accueil',
      speakerPrefix: 'Interlocuteur',
      listenChinese: 'Écouter le chinois',
      lessonActions: 'Actions de la leçon',
      lessonOverviewLabel: 'Aperçu de la leçon',
      lessonProgressPreviewLabel: 'Aperçu de progression de la leçon',
      studyLayersCount: (count: number) => `${count} étapes d’étude`,
      practiceNext: 'Pratique ensuite',
      dialoguePracticeLabel: 'Pratique du dialogue',
      dialogueLineLabel: (speaker: string) => `Ligne de dialogue, interlocuteur ${speaker}`,
    },
    practicePage: {
      eyebrow: 'Pratique',
      notFoundEyebrow: 'Pratique introuvable',
      notFoundHeading: 'Impossible de trouver cette série d’exercices.',
      lede: 'Travaillez une étape d’écoute, une étape d’oral et une étape de lecture.',
      checklistHeading: 'Checklist du jour',
      checklistLabel: 'Checklist de pratique',
      listeningReady: 'Étape d’écoute prête',
      speakingReady: 'Étape de répétition prête',
      readingReady: 'Étape de lecture prête',
      listenAndChoose: 'Écouter et choisir',
      answer: 'Réponse',
      repeatAloud: 'Répéter à voix haute',
      modelAnswer: 'Réponse modèle',
      selfCheck: 'Auto-vérification : peux-tu la dire une fois lentement puis une fois à vitesse naturelle ?',
      matchHanzi: 'Associer les hanzi',
      readingGoal: 'Objectif de lecture',
      continueToShortInput: 'Continuer vers la mini-réponse',
      backToLesson: 'Retour à la leçon',
      practiceActions: 'Actions de pratique',
    },
    shortInputPage: {
      eyebrow: 'Mini-réponse',
      notFoundEyebrow: 'Mini-réponse introuvable',
      notFoundHeading: 'Impossible de trouver cette dernière étape.',
      lede: 'Terminez la leçon avec une mini-réponse et une vérification de compréhension.',
      shortItem: 'Mini-réponse',
      targetAnswer: 'Réponse attendue',
      comprehensionPrompt: 'Question de compréhension',
      comprehensionQuestion: 'Que veut dire cette réponse dans la scène ?',
      answerKey: 'Corrigé',
      finishButton: 'J’ai terminé la mini-réponse',
      finishedMessage: 'Leçon terminée. Les cartes de révision sont prêtes.',
      backToPractice: 'Retour à la pratique',
      goToReview: 'Aller à la révision',
      viewProgress: 'Voir les progrès',
      listenChinese: 'Écouter le chinois',
      shortInputActions: 'Actions de la mini-réponse',
    },
    reviewPage: {
      eyebrow: 'Révision',
      heading: 'Révision',
      cardsDueToday: (count: number) => `Cartes à revoir aujourd’hui : ${count}`,
      front: 'Recto',
      back: 'Verso',
      markComplete: 'Marquer comme terminée',
      finishedCount: (count: number) => `${count} ${count === 1 ? 'carte terminée.' : 'cartes terminées.'}`,
      queueClear: 'File vide',
      noCards: 'Aucune carte à revoir pour le moment.',
      viewProgress: 'Voir les progrès',
      backToHome: 'Retour à l’accueil',
      reviewActions: 'Actions de révision',
      currentFlashcardLabel: 'Carte de révision en cours',
      frontSideLabel: 'Recto de la carte',
      backSideLabel: 'Verso de la carte',
      statusPanelLabel: 'Panneau d’état de révision',
      dueNow: 'À revoir',
      completedNow: 'Terminées',
    },
    progressPage: {
      eyebrow: 'Progression',
      heading: 'Progression',
      summaryLabel: 'Résumé du parcours',
      statsLabel: 'Indicateurs d’apprentissage',
      lessonProgressLabel: 'Progression des leçons',
      progressActionsLabel: 'Actions de progression',
      nextStepEyebrow: 'Prochaine étape',
      lessonProgressEyebrow: 'Carte du parcours',
      completedLessonsLabel: 'Leçons terminées',
      masteryLabel: 'Maîtrise du parcours',
      completedSummary: (done: number, total: number) =>
        `${done} leçon${done > 1 ? 's' : ''} sur ${total} terminée${done > 1 ? 's' : ''}`,
      currentLesson: 'Leçon en cours',
      notStartedYet: 'Pas encore commencée',
      reviewQueue: 'File de révision',
      reviewItemsWaiting: (count: number) =>
        `${count} carte${count > 1 ? 's' : ''} en attente`,
      lessonStatusComplete: 'Terminée',
      lessonStatusCurrent: 'En cours',
      lessonStatusUpcoming: 'À venir',
      backToHome: 'Retour à l’accueil',
      goToReview: 'Aller à la révision',
    },
    common: {
      explanation: 'Explication',
    },
  },
} as const

export function getUiCopy(language: ExplanationLanguage) {
  return uiCopy[language]
}
