import type { ExplanationLanguage, LocalizedField } from './types'

export const languageNames: Record<ExplanationLanguage, string> = {
  en: 'English',
  fr: 'Français',
}

export function getLocalizedText(
  text: LocalizedField,
  language: ExplanationLanguage,
) {
  return typeof text === 'string' ? text : text[language]
}

export const uiCopy = {
  en: {
    explanationLabel: 'Explanation',
    languageToggleLabel: 'Explanation language',
    courseSeries: {
      label: 'Course series',
      pinyinTitle: 'Mandarin tones and pinyin',
      basicExpressionsTitle: 'Basic Chinese expressions for a stress-free journey',
    },
    homePage: {
      heading: '轻松学中文',
      heroSlogan: 'Learn Mandarin in real life scenarios',
      lessonEyebrow: 'Lesson',
      openLesson: 'Open lesson',
      comingSoon: 'Coming soon',
      previewPeek: 'Peek inside',
      previewHide: 'Hide preview',
      previewGoalLabel: 'Goal',
      previewKeyPhraseLabel: 'Key phrase',
      previewMeaningLabel: 'Meaning',
      lessonListLabel: 'Lesson list',
      learningHighlightsLabel: 'Learning highlights',
      heroPhraseLabel: 'Hero phrase',
      learningMockupLabel: 'Learning preview mockup',
      courseProgressSummaryLabel: 'Course progress summary',
      mockupListenLabel: 'Listen',
      lessonCount: (count: number) => `${count} ${count === 1 ? 'lesson' : 'lessons'}`,
      completedLessonCount: (count: number) => `${count} complete`,
      reviewCount: (count: number) => `${count} review`,
      lessonScenarioBadges: {
        'self-intro': 'Arrival',
        'ask-directions': 'Taxi',
        'order-food': 'Check-in',
        'phone-and-payment': 'Setup',
        'convenience-store-run': 'Store',
        'restaurant-order': 'Restaurant',
        'metro-ticket': 'Metro',
        'pharmacy-help': 'Pharmacy',
        'ask-for-help-problem': 'Help',
        'train-station-ticket': 'Train',
      },
    },
    lessonPage: {
      eyebrow: 'Lesson',
      notFoundEyebrow: 'Lesson not found',
      notFoundHeading: 'We couldn’t find that lesson.',
      dialogue: 'Dialogue',
      sentencePatterns: 'Useful patterns',
      vocabulary: 'Vocabulary',
      goToPractice: 'Go to practice',
      backToHome: 'Back to home',
      speakerPrefix: 'Speaker',
      listenChinese: 'Play Chinese',
      lessonActions: 'Lesson actions',
      lessonProgressPreviewLabel: 'Lesson progress preview',
      studyLayersCount: (count: number) => `${count} study layers`,
      practiceNext: 'Practice next',
      dialoguePracticeLabel: 'Dialogue practice',
      dialogueLineLabel: (speaker: string) => `Dialogue line speaker ${speaker}`,
    },
    practicePage: {
      eyebrow: 'Practice',
      notFoundEyebrow: 'Practice not found',
      notFoundHeading: 'We couldn’t find that practice set.',
      backToLesson: 'Back to lesson',
      goToReview: 'Go to review',
      viewProgress: 'View progress',
      practiceActions: 'Practice actions',
    },
    practiceChallenge: {
      playPromptAudio: (current: number) => `Play the audio for question ${current}`,
      speakOptions: 'Speak practice options',
      answerOptions: 'Answer options',
      fluentOption: 'I can say it fluently',
      needsPracticeOption: 'I need to practice more',
      showMeOption: 'Show me the model answer',
      correctFeedback: 'Correct!',
      pointsGained: (points: number) => `+${points} points`,
      incorrectFeedback: 'Not quite.',
      correctAnswer: (answer: string) => `Answer: ${answer}`,
      nextQuestion: 'Next question',
      resultHeading: 'Challenge complete',
      finalScore: (score: number) => `Final score: ${score}`,
      ratingLabel: 'Rating',
      ratingValue: (rating: string) => `${rating}`,
      outOfLivesMessage: 'You ran out of lives — the words you saw stay with you.',
      playAgain: 'Play again',
      completeLesson: 'Complete lesson',
      lessonCompleted: 'Lesson complete. Review cards are ready.',
      answerReview: 'Your answers',
      answerReviewCorrect: 'Correct',
      answerReviewIncorrect: 'Incorrect',
      encouragement: (rating: string) => {
        if (rating === 'S') {
          return 'Outstanding — you nailed the challenge.'
        }
        if (rating === 'A') {
          return 'Great work — nearly perfect.'
        }
        if (rating === 'B') {
          return 'Solid effort — keep going.'
        }
        return 'Good start — try again to climb the score.'
      },
    },
    reviewPage: {
      eyebrow: 'Review',
      heading: 'Review',
      cardsDueToday: (count: number) => `Cards due today: ${count}`,
      front: 'Front',
      back: 'Back',
      markComplete: 'Mark complete',
      finishedCount: (count: number) => `${count} ${count === 1 ? 'card finished.' : 'cards finished.'}`,
      queueClear: 'Queue clear',
      noCards: 'No cards due right now.',
      viewProgress: 'View progress',
      backToHome: 'Back to home',
      reviewActions: 'Review actions',
      currentFlashcardLabel: 'Current review flashcard',
      frontSideLabel: 'Flashcard front',
      backSideLabel: 'Flashcard back',
      statusPanelLabel: 'Review status panel',
      dueNow: 'Due now',
      completedNow: 'Completed now',
    },
    progressPage: {
      eyebrow: 'Progress',
      heading: 'Progress',
      summaryLabel: 'Learning path summary',
      statsLabel: 'Learning indicators',
      progressActionsLabel: 'Progress actions',
      nextStepEyebrow: 'Next step',
      completedLessonsLabel: 'Completed lessons',
      masteryLabel: 'Course mastery',
      completedSummary: (done: number, total: number) =>
        `${done} of ${total} lesson${total === 1 ? '' : 's'} completed`,
      currentLesson: 'Current lesson',
      notStartedYet: 'Not started yet',
      reviewQueue: 'Review queue',
      reviewItemsWaiting: (count: number) =>
        `${count} review item${count === 1 ? '' : 's'} waiting`,
      lessonStatusComplete: 'Complete',
      lessonStatusCurrent: 'Current',
      lessonStatusUpcoming: 'Upcoming',
      lessonStatusPreview: 'Preview',
      previewDisplayOnly: 'Display-only preview',
      openLesson: 'Open lesson',
      openJourneyLesson: (title: string) => `Open ${title}`,
      backToHome: 'Back to home',
      goToReview: 'Go to review',
    },
    pinyinPage: {
      eyebrow: 'Pinyin',
      heading: 'Pinyin（零基础第一课）',
      sectionProgress: (done: number, total: number) =>
        `${done} of ${total} section${total === 1 ? '' : 's'} complete`,
      lessonEyebrow: (n: number) => `Lesson ${n}`,
      referenceHeading: 'Reference',
      referenceSummary: 'Build a first sound map from initials, finals, and Mandarin tones.',
      playReferenceAudio: (label: string) => `Play ${label}`,
      goToPractice: 'Go to practice',
      backToHome: 'Back to home',
      lessonActions: 'Pinyin lesson actions',
    },
    common: {
      explanation: 'Explanation',
    },
  },
  fr: {
    explanationLabel: 'Explication',
    languageToggleLabel: 'Langue d’explication',
    courseSeries: {
      label: 'Séries de cours',
      pinyinTitle: 'Tons et pinyin du mandarin',
      basicExpressionsTitle: 'Expressions chinoises essentielles pour voyager sereinement',
    },
    homePage: {
      heading: '轻松学中文',
      heroSlogan: 'Apprenez le mandarin dans la vie quotidienne',
      lessonEyebrow: 'Leçon',
      openLesson: 'Ouvrir la leçon',
      comingSoon: 'Bientôt',
      previewPeek: 'Voir un aperçu',
      previewHide: 'Masquer l’aperçu',
      previewGoalLabel: 'Objectif',
      previewKeyPhraseLabel: 'Phrase clé',
      previewMeaningLabel: 'Sens',
      lessonListLabel: 'Liste des leçons',
      learningHighlightsLabel: 'Points clés de l’apprentissage',
      heroPhraseLabel: 'Phrase modèle',
      learningMockupLabel: 'Maquette d’aperçu d’apprentissage',
      courseProgressSummaryLabel: 'Résumé des progrès du cours',
      mockupListenLabel: 'Écouter',
      lessonCount: (count: number) => `${count} leçon${count > 1 ? 's' : ''}`,
      completedLessonCount: (count: number) => `${count} terminée${count > 1 ? 's' : ''}`,
      reviewCount: (count: number) => `${count} à réviser`,
      lessonScenarioBadges: {
        'self-intro': 'Arrivée',
        'ask-directions': 'Taxi',
        'order-food': 'Check-in',
        'phone-and-payment': 'Installation',
        'convenience-store-run': 'Supérette',
        'restaurant-order': 'Restaurant',
        'metro-ticket': 'Métro',
        'pharmacy-help': 'Pharmacie',
        'ask-for-help-problem': 'Aide',
        'train-station-ticket': 'Train',
      },
    },
    lessonPage: {
      eyebrow: 'Leçon',
      notFoundEyebrow: 'Leçon introuvable',
      notFoundHeading: 'Impossible de trouver cette leçon.',
      dialogue: 'Dialogue',
      sentencePatterns: 'Structures utiles',
      vocabulary: 'Vocabulaire',
      goToPractice: 'Passer à la pratique',
      backToHome: 'Retour à l’accueil',
      speakerPrefix: 'Interlocuteur',
      listenChinese: 'Écouter le chinois',
      lessonActions: 'Actions de la leçon',
      lessonProgressPreviewLabel: 'Aperçu de progression de la leçon',
      studyLayersCount: (count: number) => `${count} étapes d’étude`,
      practiceNext: 'Pratique ensuite',
      dialoguePracticeLabel: 'Pratique du dialogue',
      dialogueLineLabel: (speaker: string) => `Ligne de dialogue, interlocuteur ${speaker}`,
    },
    practicePage: {
      eyebrow: 'Pratique',
      notFoundEyebrow: 'Pratique introuvable',
      notFoundHeading: 'Impossible de trouver cette série d’exercices.',
      backToLesson: 'Retour à la leçon',
      goToReview: 'Aller à la révision',
      viewProgress: 'Voir les progrès',
      practiceActions: 'Actions de pratique',
    },
    practiceChallenge: {
      playPromptAudio: (current: number) => `Écouter l’audio de la question ${current}`,
      speakOptions: 'Options de pratique orale',
      answerOptions: 'Options de réponse',
      fluentOption: 'Je peux le dire couramment',
      needsPracticeOption: 'J’ai besoin de plus de pratique',
      showMeOption: 'Montre-moi la réponse modèle',
      correctFeedback: 'Correct !',
      pointsGained: (points: number) => `+${points} points`,
      incorrectFeedback: 'Pas tout à fait.',
      correctAnswer: (answer: string) => `Réponse : ${answer}`,
      nextQuestion: 'Question suivante',
      resultHeading: 'Défi terminé',
      finalScore: (score: number) => `Score final : ${score}`,
      ratingLabel: 'Niveau',
      ratingValue: (rating: string) => `${rating}`,
      outOfLivesMessage: 'Tu n’as plus de vies — les mots vus restent acquis.',
      playAgain: 'Rejouer',
      completeLesson: 'Terminer la leçon',
      lessonCompleted: 'Leçon terminée. Les cartes de révision sont prêtes.',
      answerReview: 'Tes réponses',
      answerReviewCorrect: 'Correct',
      answerReviewIncorrect: 'Incorrect',
      encouragement: (rating: string) => {
        if (rating === 'S') {
          return 'Exceptionnel — tu as réussi le défi.'
        }
        if (rating === 'A') {
          return 'Excellent travail — presque parfait.'
        }
        if (rating === 'B') {
          return 'Bel effort — continue.'
        }
        return 'Bon début — rejoue pour améliorer ton score.'
      },
    },
    reviewPage: {
      eyebrow: 'Révision',
      heading: 'Révision',
      cardsDueToday: (count: number) => `Cartes à revoir aujourd’hui : ${count}`,
      front: 'Recto',
      back: 'Verso',
      markComplete: 'Marquer comme terminée',
      finishedCount: (count: number) => `${count} ${count === 1 ? 'carte terminée.' : 'cartes terminées.'}`,
      queueClear: 'File vide',
      noCards: 'Aucune carte à revoir pour le moment.',
      viewProgress: 'Voir les progrès',
      backToHome: 'Retour à l’accueil',
      reviewActions: 'Actions de révision',
      currentFlashcardLabel: 'Carte de révision en cours',
      frontSideLabel: 'Recto de la carte',
      backSideLabel: 'Verso de la carte',
      statusPanelLabel: 'Panneau d’état de révision',
      dueNow: 'À revoir',
      completedNow: 'Terminées',
    },
    progressPage: {
      eyebrow: 'Progression',
      heading: 'Progression',
      summaryLabel: 'Résumé du parcours',
      statsLabel: 'Indicateurs d’apprentissage',
      progressActionsLabel: 'Actions de progression',
      nextStepEyebrow: 'Prochaine étape',
      completedLessonsLabel: 'Leçons terminées',
      masteryLabel: 'Maîtrise du parcours',
      completedSummary: (done: number, total: number) =>
        `${done} leçon${done > 1 ? 's' : ''} sur ${total} terminée${done > 1 ? 's' : ''}`,
      currentLesson: 'Leçon en cours',
      notStartedYet: 'Pas encore commencée',
      reviewQueue: 'File de révision',
      reviewItemsWaiting: (count: number) =>
        `${count} carte${count > 1 ? 's' : ''} en attente`,
      lessonStatusComplete: 'Terminée',
      lessonStatusCurrent: 'En cours',
      lessonStatusUpcoming: 'À venir',
      lessonStatusPreview: 'Aperçu',
      previewDisplayOnly: 'Aperçu sans lien',
      openLesson: 'Ouvrir la leçon',
      openJourneyLesson: (title: string) => `Ouvrir ${title}`,
      backToHome: 'Retour à l’accueil',
      goToReview: 'Aller à la révision',
    },
    pinyinPage: {
      eyebrow: 'Pinyin',
      heading: 'Pinyin（零基础第一课）',
      sectionProgress: (done: number, total: number) =>
        `${done} section${done > 1 ? 's' : ''} sur ${total} terminée${done > 1 ? 's' : ''}`,
      lessonEyebrow: (n: number) => `Leçon ${n}`,
      referenceHeading: 'Référence',
      referenceSummary: 'Construisez une première carte sonore à partir des initiales, finales et tons du mandarin.',
      playReferenceAudio: (label: string) => `Écouter ${label}`,
      goToPractice: 'Passer à la pratique',
      backToHome: 'Retour à l’accueil',
      lessonActions: 'Actions de la leçon de pinyin',
    },
    common: {
      explanation: 'Explication',
    },
  },
} as const

export function getUiCopy(language: ExplanationLanguage) {
  return uiCopy[language]
}
