import type { LessonContent } from '../types.js'

export const askForHelpProblemLesson: LessonContent = {
  id: 'ask-for-help-problem',
  title: {
    en: '寻求帮助 / Ask for help',
    fr: '寻求帮助 / Demander de l’aide',
  },
  scenario: {
    en: 'When you need help in a public place, or something urgent has come up, those phrases come in handy.',
    fr: 'Quand tu as besoin d’aide dans un lieu public, ou qu’un problème urgent survient, ces phrases sont bien utiles.',
  },
  dialogue: {
    title: {
      en: 'Solve a phone problem and ask for practical help',
      fr: 'Résoudre un problème de téléphone et demander une aide pratique',
    },
    lines: [
      {
        id: 'ask-for-help-problem-line-01',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请问，你可以帮我吗？',
        pinyin: 'Qǐngwèn, nǐ kěyǐ bāng wǒ ma?',
        translation: { en: 'Excuse me, can you help me?', fr: 'Excusez-moi, pouvez-vous m\'aider ?' },
        explanation: { en: 'Use this to open a polite help request in a public place.', fr: 'Utilise cette structure pour ouvrir une demande d’aide polie dans un lieu public.' },
        audio: '/audio/ask-for-help-problem/line-01.mp3',
      },
      {
        id: 'ask-for-help-problem-line-02',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我护照丢了。',
        pinyin: 'Wǒ hùzhào diū le.',
        translation: { en: 'I lost my passport.', fr: 'J\'ai perdu mon passeport.' },
        explanation: { en: 'Name the lost item after 丢了, like your passport.', fr: 'Nomme l\'objet perdu après 丢了, comme ton passeport.' },
        audio: '/audio/ask-for-help-problem/line-02.mp3',
      },
      {
        id: 'ask-for-help-problem-line-03',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请说慢一点。',
        pinyin: 'Qǐng shuō màn yìdiǎn.',
        translation: { en: 'Please speak slower.', fr: 'Parlez plus lentement, s\'il vous plaît.' },
        explanation: { en: 'Ask 请说慢一点 when the other person speaks too fast.', fr: 'Demande 请说慢一点 quand l\'autre personne parle trop vite.' },
        audio: '/audio/ask-for-help-problem/line-03.mp3',
      },
      {
        id: 'ask-for-help-problem-line-04',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我听不懂。',
        pinyin: 'Wǒ tīngbùdǒng.',
        translation: { en: 'I don\'t understand.', fr: 'Je ne comprends pas.' },
        explanation: { en: 'Say 我听不懂 to let the helper know you need simpler words.', fr: 'Dis 我听不懂 pour indiquer à la personne que tu as besoin de mots plus simples.' },
        audio: '/audio/ask-for-help-problem/line-04.mp3',
      },
      {
        id: 'ask-for-help-problem-line-05',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我手机没电了。',
        pinyin: 'Wǒ shǒujī méidiàn le.',
        translation: { en: 'My phone is dead.', fr: 'Mon téléphone n\'a plus de batterie.' },
        explanation: { en: 'Say 我手机没电了 when your phone has run out of battery.', fr: 'Dis 我手机没电了 quand ton téléphone n\'a plus de batterie.' },
        audio: '/audio/ask-for-help-problem/line-05.mp3',
      },
      {
        id: 'ask-for-help-problem-line-06',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请问哪里可以给手机充电？',
        pinyin: 'Qǐngwèn nǎlǐ kěyǐ gěi shǒujī chōngdiàn?',
        translation: { en: 'Where can I charge my phone?', fr: 'Où puis-je recharger mon téléphone ?' },
        explanation: { en: 'Ask 哪里可以给手机充电 to find a place to charge your phone.', fr: 'Demande 哪里可以给手机充电 pour trouver un endroit où recharger ton téléphone.' },
        audio: '/audio/ask-for-help-problem/line-06.mp3',
      },
      {
        id: 'ask-for-help-problem-line-07',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '您好，共享单车怎么用？',
        pinyin: 'Nín hǎo, gòngxiǎng dānchē zěnme yòng?',
        translation: { en: 'How do I use the shared bike?', fr: 'Bonjour, comment utiliser le vélo partagé ?' },
        explanation: { en: 'Ask 共享单车怎么用 to learn how to use a shared bike.', fr: 'Demande 共享单车怎么用 pour apprendre à utiliser un vélo partagé.' },
        audio: '/audio/ask-for-help-problem/line-07.mp3',
      },
      {
        id: 'ask-for-help-problem-line-08',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '能帮我一个忙吗？',
        pinyin: 'Néng bāng wǒ yí gè máng ma?',
        translation: { en: 'Could you do me a favor?', fr: 'Pouvez-vous me rendre un service ?' },
        explanation: { en: 'Use 能帮我一个忙吗 to ask someone for a favor politely.', fr: 'Utilise 能帮我一个忙吗 pour demander poliment un service.' },
        audio: '/audio/ask-for-help-problem/line-08.mp3',
      },
      {
        id: 'ask-for-help-problem-line-09',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '麻烦你了。',
        pinyin: 'Máfan nǐ le.',
        translation: { en: 'Sorry to trouble you.', fr: 'Désolé de vous déranger.' },
        explanation: { en: 'Say 麻烦你了 to thank someone after asking for their help.', fr: 'Dis 麻烦你了 pour remercier quelqu\'un après lui avoir demandé de l\'aide.' },
        audio: '/audio/ask-for-help-problem/line-09.mp3',
      },
      {
        id: 'ask-for-help-problem-line-10',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '救命！',
        pinyin: 'Jiùmìng!',
        translation: { en: 'Help!', fr: 'Au secours !' },
        explanation: { en: 'Shout 救命 in an emergency to call for urgent help.', fr: 'Crie 救命 en cas d\'urgence pour appeler de l\'aide.' },
        audio: '/audio/ask-for-help-problem/line-10.mp3',
      },
      {
        id: 'ask-for-help-problem-line-11',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我迷路了。',
        pinyin: 'Wǒ mílù le.',
        translation: { en: 'I am lost.', fr: 'Je suis perdu(e).' },
        explanation: { en: 'Say 我迷路了 when you cannot find your way.', fr: 'Dis 我迷路了 quand tu ne trouves pas ton chemin.' },
        audio: '/audio/ask-for-help-problem/line-11.mp3',
      },
      {
        id: 'ask-for-help-problem-line-12',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请给警察打电话。',
        pinyin: 'Qǐng gěi jǐngchá dǎdiànhuà.',
        translation: { en: 'Please call the police.', fr: 'Veuillez appeler la police.' },
        explanation: { en: 'Ask 请给警察打电话 when you need the police in an emergency.', fr: 'Demande 请给警察打电话 quand tu as besoin de la police en urgence.' },
        audio: '/audio/ask-for-help-problem/line-12.mp3',
      },
      {
        id: 'ask-for-help-problem-line-13',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '卫生间在哪里？',
        pinyin: 'Wèishēngjiān zài nǎlǐ?',
        translation: { en: 'Where is the toilet?', fr: 'Où sont les toilettes ?' },
        explanation: { en: 'Ask 卫生间在哪里 to find a restroom in a public place.', fr: 'Demande 卫生间在哪里 pour trouver des toilettes dans un lieu public.' },
        audio: '/audio/ask-for-help-problem/line-13.mp3',
      },
      {
        id: 'ask-for-help-problem-line-14',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '打扰一下,请问最近的便利店在哪里?',
        pinyin: 'Dǎrǎo yíxià, qǐngwèn zuìjìn de biànlìdiàn zài nǎlǐ?',
        translation: { en: 'Excuse me, where is the nearest convenience store?', fr: 'Excusez-moi, où est la supérette la plus proche ?' },
        explanation: { en: 'Ask 最近的便利店在哪里 to find a nearby convenience store.', fr: 'Demande 最近的便利店在哪里 pour trouver une supérette proche.' },
        audio: '/audio/ask-for-help-problem/line-14.mp3',
      },
      {
        id: 'ask-for-help-problem-line-15',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我的手机不见了。',
        pinyin: 'Wǒ de shǒujī bújiàn le.',
        translation: { en: 'I lost my phone.', fr: 'J\'ai perdu mon téléphone.' },
        explanation: { en: 'Say 我的手机不见了 to report a lost phone.', fr: 'Dis 我的手机不见了 pour signaler un téléphone perdu.' },
        audio: '/audio/ask-for-help-problem/line-15.mp3',
      },
      {
        id: 'ask-for-help-problem-line-16',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我的钱包不见了。',
        pinyin: 'Wǒ de qiánbāo bújiàn le.',
        translation: { en: 'I lost my wallet.', fr: 'J\'ai perdu mon portefeuille.' },
        explanation: { en: 'Say 我的钱包不见了 to report a lost wallet.', fr: 'Dis 我的钱包不见了 pour signaler un portefeuille perdu.' },
        audio: '/audio/ask-for-help-problem/line-16.mp3',
      },
    ],
  },
    sentencePatterns: [
    {
      id: 'ask-for-help-problem-pattern-1',
      pattern: '你可以帮我吗？',
      pinyin: 'Nǐ kěyǐ bāng wǒ ma?',
      meaning: {
        en: 'Excuse me, can you help me?',
        fr: 'Pouvez-vous m\'aider ?',
      },
      audio: '/audio/ask-for-help-problem/pattern-01.mp3',
    },
    {
      id: 'ask-for-help-problem-pattern-2',
      pattern: '我的……丢了。',
      pinyin: 'Wǒ de ... diū le.',
      meaning: {
        en: 'I lost my ...',
        fr: 'J\'ai perdu ...',
      },
      audio: '/audio/ask-for-help-problem/pattern-02.mp3',
      examples: [
        {
          fill: '护照',
          fillPinyin: 'hùzhào',
          hanzi: '我的护照丢了。',
          pinyin: 'Wǒ de hùzhào diū le.',
          en: 'passport',
          fr: 'passeport',
        },
        {
          fill: '手机',
          fillPinyin: 'shǒujī',
          hanzi: '我的手机丢了。',
          pinyin: 'Wǒ de shǒujī diū le.',
          en: 'phone',
          fr: 'téléphone',
        },
        {
          fill: '钱包',
          fillPinyin: 'qiánbāo',
          hanzi: '我的钱包丢了。',
          pinyin: 'Wǒ de qiánbāo diū le.',
          en: 'wallet',
          fr: 'portefeuille',
        },
      ],
    },
    {
      id: 'ask-for-help-problem-pattern-3',
      pattern: '请说慢一点。',
      pinyin: 'Qǐng shuō màn yìdiǎn.',
      meaning: {
        en: 'Please speak slower.',
        fr: 'Parlez plus lentement, s\'il vous plaît.',
      },
      audio: '/audio/ask-for-help-problem/pattern-03.mp3',
    },
    {
      id: 'ask-for-help-problem-pattern-4',
      pattern: '我听不懂。',
      pinyin: 'Wǒ tīng bù dǒng.',
      meaning: {
        en: 'I don\'t understand.',
        fr: 'Je ne comprends pas.',
      },
      audio: '/audio/ask-for-help-problem/pattern-04.mp3',
    },
    {
      id: 'ask-for-help-problem-pattern-5',
      pattern: '我迷路了。',
      pinyin: 'Wǒ mílù le.',
      meaning: {
        en: 'I am lost.',
        fr: 'Je suis perdu(e).',
      },
    },
    {
      id: 'ask-for-help-problem-pattern-6',
      pattern: '我手机没电了。',
      pinyin: 'Wǒ shǒujī méi diàn le.',
      meaning: {
        en: 'My phone is dead.',
        fr: 'Mon téléphone n\'a plus de batterie.',
      },
    },
    {
      id: 'ask-for-help-problem-pattern-7',
      pattern: '请问哪里可以给手机充电？',
      pinyin: 'Qǐngwèn nǎlǐ kěyǐ gěi shǒujī chōngdiàn?',
      meaning: {
        en: 'Where can I charge my phone?',
        fr: 'Où puis-je recharger mon téléphone ?',
      },
    },
    {
      id: 'ask-for-help-problem-pattern-8',
      pattern: '您好，共享单车怎么用？',
      pinyin: 'Nín hǎo, gòngxiǎng dānchē zěnme yòng?',
      meaning: {
        en: 'Hello, how do I use the shared bike?',
        fr: 'Bonjour, comment utiliser le vélo partagé ?',
      },
    },
    {
      id: 'ask-for-help-problem-pattern-9',
      pattern: '能帮我一个忙吗？',
      pinyin: 'Néng bāng wǒ yí gè máng ma?',
      meaning: {
        en: 'Could you do me a favor?',
        fr: 'Pouvez-vous me rendre un service ?',
      },
    },
    {
      id: 'ask-for-help-problem-pattern-10',
      pattern: '麻烦你了。',
      pinyin: 'Máfan nǐ le.',
      meaning: {
        en: 'Sorry to trouble you.',
        fr: 'Désolé de vous déranger.',
      },
    },
    {
      id: 'ask-for-help-problem-pattern-11',
      pattern: '救命！',
      pinyin: 'Jiùmìng!',
      meaning: {
        en: 'Help!',
        fr: 'Au secours !',
      },
    },
    {
      id: 'ask-for-help-problem-pattern-12',
      pattern: '请给警察打电话。',
      pinyin: 'Qǐng gěi jǐngchá dǎ diànhuà.',
      meaning: {
        en: 'Please call the police.',
        fr: 'Veuillez appeler la police.',
      },
      audio: '/audio/ask-for-help-problem/pattern-12.mp3',
    },
    {
      id: 'ask-for-help-problem-pattern-13',
      pattern: '卫生间在哪里？',
      pinyin: 'Wèishēngjiān zài nǎlǐ?',
      meaning: {
        en: 'Where is the toilet?',
        fr: 'Où sont les toilettes ?',
      },
      audio: '/audio/ask-for-help-problem/pattern-13.mp3',
    },
    {
      id: 'ask-for-help-problem-pattern-14',
      pattern: '打扰一下，请问最近的便利店在哪里？',
      pinyin: 'Dǎrǎo yíxià, qǐngwèn zuìjìn de biànlìdiàn zài nǎlǐ?',
      meaning: {
        en: 'Excuse me, where is the nearest convenience store?',
        fr: 'Excusez-moi, où est la supérette la plus proche ?',
      },
    },
  ],
  vocabulary: [
    {
      id: 'ask-for-help-problem-vocab-1',
      hanzi: '帮忙',
      pinyin: 'bāngmáng',
      audio: '/audio/ask-for-help-problem/vocab-01.mp3',
      meaning: {
        en: 'help',
        fr: 'aide / aider',
      },
      explanation: {
        en: 'The core idea behind 帮我一下.',
        fr: 'L’idée centrale derrière 帮我一下.',
      },
    },
    {
      id: 'ask-for-help-problem-vocab-2',
      hanzi: '问题',
      pinyin: 'wèntí',
      audio: '/audio/ask-for-help-problem/vocab-02.mp3',
      meaning: {
        en: 'problem / question',
        fr: 'problème / question',
      },
      explanation: {
        en: 'Use 有问题 to say something is wrong.',
        fr: 'Utilise 有问题 pour dire que quelque chose ne va pas.',
      },
    },
    {
      id: 'ask-for-help-problem-vocab-3',
      hanzi: '手机',
      pinyin: 'shǒujī',
      audio: '/audio/ask-for-help-problem/vocab-03.mp3',
      meaning: {
        en: 'phone',
        fr: 'téléphone',
      },
      explanation: {
        en: 'The object with the problem in this scenario.',
        fr: 'L’objet qui a un problème dans cette situation.',
      },
    },
    {
      id: 'ask-for-help-problem-vocab-4',
      hanzi: '不能',
      pinyin: 'bù néng',
      audio: '/audio/ask-for-help-problem/vocab-04.mp3',
      meaning: {
        en: 'cannot',
        fr: 'ne pas pouvoir',
      },
      explanation: {
        en: 'Use it before a blocked action like 支付.',
        fr: 'Utilise-le avant une action bloquée comme 支付.',
      },
    },
    {
      id: 'ask-for-help-problem-vocab-5',
      hanzi: '慢一点',
      pinyin: 'màn yìdiǎn',
      audio: '/audio/ask-for-help-problem/vocab-05.mp3',
      meaning: {
        en: 'a little slower',
        fr: 'un peu plus lentement',
      },
      explanation: {
        en: 'A repair phrase for understanding spoken Chinese.',
        fr: 'Une phrase de réparation pour comprendre le chinois parlé.',
      },
    },
    { id: 'ask-for-help-problem-vocab-6', hanzi: '没电', pinyin: 'méi diàn', audio: '/audio/ask-for-help-problem/vocab-06.mp3', meaning: { en: 'out of battery / no power', fr: 'plus de batterie / pas d\'électricité' }, explanation: { en: 'The key phrase for a dead phone or device.', fr: 'La phrase clé pour un téléphone ou un appareil déchargé.' } },
    { id: 'ask-for-help-problem-vocab-7', hanzi: '无线网', pinyin: 'wúxiànwǎng', audio: '/audio/ask-for-help-problem/vocab-07.mp3', meaning: { en: 'WiFi / wireless network', fr: 'WiFi / réseau sans fil' }, explanation: { en: 'A common word for WiFi you will see on signs.', fr: 'Un mot courant pour le WiFi que tu verras sur les panneaux.' } },
    { id: 'ask-for-help-problem-vocab-8', hanzi: '密码', pinyin: 'mìmǎ', audio: '/audio/ask-for-help-problem/vocab-08.mp3', meaning: { en: 'password / PIN', fr: 'mot de passe / code' }, explanation: { en: 'You will hear this when asking for WiFi access.', fr: 'Tu entendras ce mot en demandant l\'accès au WiFi.' } },
    { id: 'ask-for-help-problem-vocab-9', hanzi: '充电', pinyin: 'chōngdiàn', audio: '/audio/ask-for-help-problem/vocab-09.mp3', meaning: { en: 'charge / recharge', fr: 'charger / recharger' }, explanation: { en: 'The action to restore battery power.', fr: 'L\'action pour restaurer la batterie.' } },
    { id: 'ask-for-help-problem-vocab-10', hanzi: '没关系', pinyin: 'méi guānxi', audio: '/audio/ask-for-help-problem/vocab-10.mp3', meaning: { en: 'no problem / it doesn\'t matter', fr: 'pas de problème / ce n\'est pas grave' }, explanation: { en: 'A friendly phrase to keep the help exchange relaxed.', fr: 'Une phrase amicale pour garder l\'échange d\'aide détendu.' } },
  ],
  practice: {
    listening: [
      {
        id: 'ask-for-help-problem-listening-1',
        prompt: {
          en: 'Listen for the sentence that says the phone has a problem.',
          fr: 'Écoute la phrase qui dit que le téléphone a un problème.',
        },
        target: '我的手机有问题，不能支付。',
        audio: '/audio/ask-for-help-problem/practice-listening-01.mp3',
        explanation: {
          en: 'This is the key explanation after asking for help.',
          fr: 'C’est l’explication clé après la demande d’aide.',
        },
      },
      { id: 'ask-for-help-problem-listening-2', prompt: { en: 'Which phrase warns about low battery?', fr: 'Quelle phrase avertit d\'une batterie faible ?' }, target: '快没电了。', audio: '/audio/ask-for-help-problem/practice-listening-02.mp3', explanation: { en: '快没电了 is the warning you say or hear when battery is low.', fr: '快没电了 est l\'avertissement que tu dis ou entends quand la batterie est faible.' } },
    ],
    speaking: [
      {
        id: 'ask-for-help-problem-speaking-1',
        prompt: {
          en: 'Ask someone to help you for a moment.',
          fr: 'Demande à quelqu’un de t’aider un instant.',
        },
        target: '可以帮我一下吗？',
        audio: '/audio/ask-for-help-problem/practice-speaking-01.mp3',
        explanation: {
          en: 'Open with the polite request before explaining the issue.',
          fr: 'Commence par la demande polie avant d’expliquer le problème.',
        },
      },
      { id: 'ask-for-help-problem-speaking-2', prompt: { en: 'Ask if there is WiFi here.', fr: 'Demande s\'il y a du WiFi ici.' }, target: '这里有WiFi吗？', audio: '/audio/ask-for-help-problem/practice-speaking-02.mp3', explanation: { en: 'A practical question when you need internet access.', fr: 'Une question pratique quand tu as besoin d\'accès internet.' } },
    ],
    reading: [
      {
        id: 'ask-for-help-problem-reading-1',
        prompt: {
          en: 'Read the slower-speech request.',
          fr: 'Lis la demande de parler plus lentement.',
        },
        target: '请慢一点说。',
        audio: '/audio/ask-for-help-problem/practice-reading-01.mp3',
        explanation: {
          en: 'This helps you keep the conversation understandable.',
          fr: 'Cela t’aide à garder la conversation compréhensible.',
        },
      },
      { id: 'ask-for-help-problem-reading-2', prompt: { en: 'Match the phrase for "no problem".', fr: 'Associe la phrase pour "pas de problème".' }, target: '没关系', audio: '/audio/ask-for-help-problem/practice-reading-02.mp3', explanation: { en: '没关系 is a friendly go-to reply in many situations.', fr: '没关系 est une réponse amicale passe-partout dans de nombreuses situations.' } },
    ],
  },
  reviewCards: [
    {
      id: 'ask-for-help-problem-review-1',
      front: '帮我一下',
      back: {
        en: 'help me for a moment',
        fr: 'aidez-moi un instant',
      },
      explanation: {
        en: 'A polite core help request.',
        fr: 'Une demande d’aide centrale et polie.',
      },
    },
    {
      id: 'ask-for-help-problem-review-2',
      front: '有问题',
      back: {
        en: 'has a problem',
        fr: 'a un problème',
      },
      explanation: {
        en: 'Use it after the item with the issue.',
        fr: 'Utilise-le après l’objet qui pose problème.',
      },
    },
    {
      id: 'ask-for-help-problem-review-3',
      front: '慢一点',
      back: {
        en: 'a little slower',
        fr: 'un peu plus lentement',
      },
      explanation: {
        en: 'A repair phrase when speech is too fast.',
        fr: 'Une phrase de réparation si la parole est trop rapide.',
      },
    },
    { id: 'ask-for-help-problem-review-4', front: '没电', back: { en: 'out of battery', fr: 'plus de batterie' }, explanation: { en: 'Say this when your phone is dead.', fr: 'Dis ceci quand ton téléphone est déchargé.' } },
    { id: 'ask-for-help-problem-review-5', front: '密码', back: { en: 'password', fr: 'mot de passe' }, explanation: { en: 'Ask for this when connecting to WiFi.', fr: 'Demande ceci pour te connecter au WiFi.' } },
    { id: 'ask-for-help-problem-review-6', front: '没关系', back: { en: 'no problem', fr: 'pas de problème' }, explanation: { en: 'A friendly reply that keeps the exchange relaxed.', fr: 'Une réponse amicale qui garde l\'échange détendu.' } },
  ],
}
