import type { LessonContent } from '../types.js'

export const convenienceStoreRunLesson: LessonContent = {
  id: 'convenience-store-run',
  title: {
    en: '购物 / Shopping',
    fr: '购物 / Shopping',
  },
  scenario: {
    en: 'Phrases to navigate stores, check prices, bargain and pay smoothly.',
    fr: 'Des phrases pour se repérer en magasin, vérifier les prix, négocier et payer facilement.',
  },
  dialogue: {
    title: {
      en: 'Buy one simple item',
      fr: 'Acheter un article simple',
    },
    lines: [
      {
        id: 'convenience-store-run-line-01',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '这个多少钱?',
        pinyin: 'Zhè ge duō shǎo qián?',
        translation: { en: 'How much is this?', fr: 'C\'est combien ?' },
        explanation: { en: '这个 = this｜多少 = how much｜钱 = money. Point to an item and use this question to ask its price.', fr: '这个 = ceci｜多少 = combien｜钱 = argent. Montrez un article et posez cette question pour demander son prix.' },
        audio: '/audio/convenience-store-run/line-01.mp3',
      },
      {
        id: 'convenience-store-run-line-02',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '太贵了。',
        pinyin: 'Tài guì le.',
        translation: { en: 'It\'s too expensive.', fr: 'C\'est trop cher.' },
        explanation: { en: '太 = too｜贵 = expensive｜了 = emphasis / changed state. Use this to say that a price is higher than you are willing to pay.', fr: '太 = trop｜贵 = cher｜了 = insistance / changement de situation. Utilisez cette phrase pour dire qu’un prix est trop élevé pour vous.' },
        audio: '/audio/convenience-store-run/line-02.mp3',
      },
      {
        id: 'convenience-store-run-line-03',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '可以便宜一点吗?',
        pinyin: 'Kě yǐ pián yi yì diǎn ma?',
        translation: { en: 'Can you make it cheaper?', fr: 'Pouvez-vous baisser un peu le prix ?' },
        explanation: { en: '可以 = can / may｜便宜 = cheap｜一点 = a little｜吗 = yes-or-no question particle. Use this polite question to ask for a small discount.', fr: '可以 = pouvoir｜便宜 = bon marché｜一点 = un peu｜吗 = particule de question fermée. Utilisez cette question polie pour demander une petite réduction.' },
        audio: '/audio/convenience-store-run/line-03.mp3',
      },
      {
        id: 'convenience-store-run-line-04',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我只是看看。',
        pinyin: 'Wǒ zhǐ shì kàn kàn.',
        translation: { en: 'I am just looking.', fr: 'Je regarde juste.' },
        explanation: { en: '我 = I｜只是 = only / just｜看看 = have a look. Say this when browsing without being ready to buy.', fr: '我 = je｜只是 = seulement｜看看 = regarder un peu. Dites cette phrase lorsque vous regardez sans être prêt à acheter.' },
        audio: '/audio/convenience-store-run/line-04.mp3',
      },
      {
        id: 'convenience-store-run-line-05',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '有别的颜色吗?',
        pinyin: 'Yǒu bié de yán sè ma?',
        translation: { en: 'Do you have other colors?', fr: 'Avez-vous d\'autres couleurs ?' },
        explanation: { en: '有 = have / there is｜别的 = other｜颜色 = color｜吗 = yes-or-no question particle. Ask this when you want the item in another color.', fr: '有 = avoir / il y a｜别的 = autre｜颜色 = couleur｜吗 = particule de question fermée. Posez cette question pour demander l’article dans une autre couleur.' },
        audio: '/audio/convenience-store-run/line-05.mp3',
      },
      {
        id: 'convenience-store-run-line-06',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我可以试试吗？',
        pinyin: 'Wǒ kě yǐ shì shì ma?',
        translation: { en: 'Can I try it on?', fr: 'Puis-je l\'essayer ?' },
        explanation: { en: '我 = I｜可以 = may / can｜试试 = try｜吗 = yes-or-no question particle. Ask permission before trying an item on.', fr: '我 = je｜可以 = pouvoir｜试试 = essayer｜吗 = particule de question fermée. Demandez la permission avant d’essayer un article.' },
        audio: '/audio/convenience-store-run/line-06.mp3',
      },
      {
        id: 'convenience-store-run-line-07',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '试衣间在哪里?',
        pinyin: 'Shì yī jiān zài nǎ lǐ?',
        translation: { en: 'Where is the fitting room?', fr: 'Où est la cabine d\'essayage ?' },
        explanation: { en: '试衣间 = fitting room｜在 = be at｜哪里 = where. Ask store staff where the fitting room is.', fr: '试衣间 = cabine d’essayage｜在 = se trouver｜哪里 = où. Demandez au personnel où se trouve la cabine d’essayage.' },
        audio: '/audio/convenience-store-run/line-07.mp3',
      },
      {
        id: 'convenience-store-run-line-08',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '有大号/小号吗?',
        pinyin: 'Yǒu dà hào / xiǎo hào ma?',
        translation: { en: 'Do you have a large/small size?', fr: 'Avez-vous une grande/petite taille ?' },
        explanation: { en: '有 = have｜大号 = large size｜小号 = small size｜吗 = yes-or-no question particle. Use either size word to ask what is available.', fr: '有 = avoir｜大号 = grande taille｜小号 = petite taille｜吗 = particule de question fermée. Utilisez l’une des deux tailles pour demander ce qui est disponible.' },
        audio: '/audio/convenience-store-run/line-08.mp3',
      },
      {
        id: 'convenience-store-run-line-09',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我买这个。',
        pinyin: 'Wǒ mǎi zhè ge.',
        translation: { en: 'I will buy this.', fr: 'Je prends ceci.' },
        explanation: { en: '我 = I｜买 = buy｜这个 = this one. Say this to confirm which item you have chosen to purchase.', fr: '我 = je｜买 = acheter｜这个 = celui-ci. Dites cette phrase pour confirmer l’article que vous avez choisi.' },
        audio: '/audio/convenience-store-run/line-09.mp3',
      },
      {
        id: 'convenience-store-run-line-10',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '有袋子吗?',
        pinyin: 'Yǒu dài zi ma?',
        translation: { en: 'Do you have a bag?', fr: 'Avez-vous un sac ?' },
        explanation: { en: '有 = have / there is｜袋子 = bag｜吗 = yes-or-no question particle. Ask this at checkout when you need a bag.', fr: '有 = avoir / il y a｜袋子 = sac｜吗 = particule de question fermée. Posez cette question à la caisse si vous avez besoin d’un sac.' },
        audio: '/audio/convenience-store-run/line-10.mp3',
      },
      {
        id: 'convenience-store-run-line-11',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '你好，我要一瓶水。',
        pinyin: 'Nǐ hǎo, wǒ yào yì píng shuǐ.',
        translation: { en: 'Hello, I’d like a bottle of water.', fr: 'Bonjour, je voudrais une bouteille d’eau.' },
        explanation: { en: '你好 = hello｜我 = I｜要 = want / would like｜一瓶水 = a bottle of water. Use this at the counter to request the item politely.', fr: '你好 = bonjour｜我 = je｜要 = vouloir｜一瓶水 = une bouteille d’eau. Utilisez cette phrase au comptoir pour demander l’article poliment.' },
        audio: '/audio/convenience-store-run/line-11.mp3',
      },
      {
        id: 'convenience-store-run-line-12',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '一共多少钱?',
        pinyin: 'Yí gòng duō shǎo qián?',
        translation: { en: 'How much is it in total?', fr: 'Combien cela coûte-t-il au total ?' },
        explanation: { en: '一共 = altogether / in total｜多少 = how much｜钱 = money. Ask this at checkout when you want the total price.', fr: '一共 = au total｜多少 = combien｜钱 = argent. Posez cette question à la caisse pour connaître le prix total.' },
        audio: '/audio/convenience-store-run/line-12.mp3',
      },
      {
        id: 'convenience-store-run-line-13',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '可以刷卡吗?',
        pinyin: 'Kě yǐ shuā kǎ ma?',
        translation: { en: 'Can I pay by card?', fr: 'Puis-je payer par carte ?' },
        explanation: { en: '可以 = can / may｜刷卡 = pay by card｜吗 = yes-or-no question particle. Ask this before paying to check whether cards are accepted.', fr: '可以 = pouvoir｜刷卡 = payer par carte｜吗 = particule de question fermée. Posez cette question avant de payer pour vérifier si les cartes sont acceptées.' },
        audio: '/audio/convenience-store-run/line-13.mp3',
      },
      {
        id: 'convenience-store-run-line-14',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我用微信支付 / 支付宝。',
        pinyin: 'Wǒ yòng Wēi xìn zhī fù / Zhī fù bǎo.',
        translation: { en: 'I will use WeChat Pay / Alipay.', fr: 'Je vais utiliser WeChat Pay / Alipay.' },
        explanation: { en: '我 = I｜用 = use｜微信支付 = WeChat Pay｜支付宝 = Alipay. Name one of these services to tell the clerk your payment method.', fr: '我 = je｜用 = utiliser｜微信支付 = WeChat Pay｜支付宝 = Alipay. Nommez l’un de ces services pour indiquer votre moyen de paiement.' },
        audio: '/audio/convenience-store-run/line-14.mp3',
      },
    ],
  },
    sentencePatterns: [
    {
      id: 'convenience-store-run-pattern-1',
      pattern: '……多少钱？',
      pinyin: '... duō shao qián?',
      meaning: {
        en: 'How much is ...?',
        fr: 'Combien coûte ... ?',
      },
      examples: [
        {
          fill: '这个',
          fillPinyin: 'zhè ge',
          hanzi: '这个多少钱？',
          pinyin: 'Zhè ge duō shao qián?',
          en: 'How much is this?',
          fr: 'Combien coûte ceci ?',
          audio: '/audio/convenience-store-run/pattern-01-example-01.mp3',
        },
        {
          fill: '水',
          fillPinyin: 'shuǐ',
          hanzi: '水多少钱？',
          pinyin: 'Shuǐ duō shao qián?',
          en: 'How much is the water?',
          fr: 'Combien coûte l’eau ?',
          audio: '/audio/convenience-store-run/pattern-01-example-02.mp3',
        },
        {
          fill: '面包',
          fillPinyin: 'miàn bāo',
          hanzi: '面包多少钱？',
          pinyin: 'Miàn bāo duō shao qián?',
          en: 'How much is the bread?',
          fr: 'Combien coûte le pain ?',
          audio: '/audio/convenience-store-run/pattern-01-example-03.mp3',
        },
      ],
    },
    {
      id: 'convenience-store-run-pattern-2',
      pattern: '太……了。',
      pinyin: 'Tài ... le.',
      meaning: {
        en: 'It\'s too ...',
        fr: 'C\'est trop ...',
      },
      audio: '/audio/convenience-store-run/pattern-02.mp3',
      examples: [
        {
          fill: '贵',
          fillPinyin: 'guì',
          hanzi: '太贵了。',
          pinyin: 'Tài guì le.',
          en: 'It is too expensive.',
          fr: 'C’est trop cher.',
          audio: '/audio/convenience-store-run/pattern-02-example-01.mp3',
        },
        {
          fill: '便宜',
          fillPinyin: 'pián yi',
          hanzi: '太便宜了。',
          pinyin: 'Tài pián yi le.',
          en: 'It is too cheap.',
          fr: 'C’est trop bon marché.',
          audio: '/audio/convenience-store-run/pattern-02-example-02.mp3',
        },
        {
          fill: '麻烦',
          fillPinyin: 'má fan',
          hanzi: '太麻烦了。',
          pinyin: 'Tài má fan le.',
          en: 'It is too troublesome.',
          fr: 'C’est trop compliqué.',
          audio: '/audio/convenience-store-run/pattern-02-example-03.mp3',
        },
      ],
    },
    {
      id: 'convenience-store-run-pattern-3',
      pattern: '可以……吗？',
      pinyin: 'Kě yǐ ... ma?',
      meaning: {
        en: 'Can / May ...?',
        fr: 'Est-ce que je peux / peut-on ... ?',
      },
      examples: [
        {
          fill: '便宜一点',
          fillPinyin: 'pián yi yì diǎn',
          hanzi: '可以便宜一点吗？',
          pinyin: 'Kě yǐ pián yi yì diǎn ma?',
          en: 'Can it be a little cheaper?',
          fr: 'Est-ce que cela peut être un peu moins cher ?',
          audio: '/audio/convenience-store-run/pattern-03-example-01.mp3',
        },
        {
          fill: '刷卡',
          fillPinyin: 'shuā kǎ',
          hanzi: '可以刷卡吗？',
          pinyin: 'Kě yǐ shuā kǎ ma?',
          en: 'Can I pay by card?',
          fr: 'Puis-je payer par carte ?',
          audio: '/audio/convenience-store-run/pattern-03-example-02.mp3',
        },
        {
          fill: '试试',
          fillPinyin: 'shì shi',
          hanzi: '可以试试吗？',
          pinyin: 'Kě yǐ shì shi ma?',
          en: 'Can I try it?',
          fr: 'Puis-je l’essayer ?',
          audio: '/audio/convenience-store-run/pattern-03-example-03.mp3',
        },
      ],
    },
    {
      id: 'convenience-store-run-pattern-4',
      pattern: '我买这个。',
      pinyin: 'Wǒ mǎi zhè ge.',
      meaning: {
        en: 'I will buy this.',
        fr: 'Je prends ceci.',
      },
      audio: '/audio/convenience-store-run/pattern-04.mp3',
    },
    {
      id: 'convenience-store-run-pattern-5',
      pattern: '有……吗？',
      pinyin: 'Yǒu ... ma?',
      meaning: {
        en: 'Do you have ...?',
        fr: 'Avez-vous ... ?',
      },
      examples: [
        {
          fill: '袋子',
          fillPinyin: 'dài zi',
          hanzi: '有袋子吗？',
          pinyin: 'Yǒu dài zi ma?',
          en: 'Do you have a bag?',
          fr: 'Avez-vous un sac ?',
          audio: '/audio/convenience-store-run/pattern-05-example-01.mp3',
        },
        {
          fill: '热咖啡',
          fillPinyin: 'rè kā fēi',
          hanzi: '有热咖啡吗？',
          pinyin: 'Yǒu rè kā fēi ma?',
          en: 'Do you have hot coffee?',
          fr: 'Avez-vous du café chaud ?',
          audio: '/audio/convenience-store-run/pattern-05-example-02.mp3',
        },
        {
          fill: '别的颜色',
          fillPinyin: 'bié de yán sè',
          hanzi: '有别的颜色吗？',
          pinyin: 'Yǒu bié de yán sè ma?',
          en: 'Do you have other colors?',
          fr: 'Avez-vous d’autres couleurs ?',
          audio: '/audio/convenience-store-run/pattern-05-example-03.mp3',
        },
      ],
    },
    {
      id: 'convenience-store-run-pattern-6',
      pattern: '我只是看看。',
      pinyin: 'Wǒ zhǐ shì kàn kan.',
      meaning: {
        en: 'I am just looking.',
        fr: 'Je regarde juste.',
      },
    
      audio: '/audio/convenience-store-run/line-04.mp3',},
    {
      id: 'convenience-store-run-pattern-7',
      pattern: '有别的颜色吗？',
      pinyin: 'Yǒu bié de yán sè ma?',
      meaning: {
        en: 'Do you have other colors?',
        fr: 'Avez-vous d\'autres couleurs ?',
      },
    
      audio: '/audio/convenience-store-run/pattern-05-example-03.mp3',},
    {
      id: 'convenience-store-run-pattern-8',
      pattern: '我可以试试吗？',
      pinyin: 'Wǒ kě yǐ shì shi ma?',
      meaning: {
        en: 'Can I try it on?',
        fr: 'Puis-je l\'essayer ?',
      },
    
      audio: '/audio/convenience-store-run/line-06.mp3',},
    {
      id: 'convenience-store-run-pattern-9',
      pattern: '试衣间在哪里？',
      pinyin: 'Shì yī jiān zài nǎ lǐ?',
      meaning: {
        en: 'Where is the fitting room?',
        fr: 'Où est la cabine d\'essayage ?',
      },
    
      audio: '/audio/convenience-store-run/pattern-09.mp3',},
    {
      id: 'convenience-store-run-pattern-10',
      pattern: '有大号/小号吗？',
      pinyin: 'Yǒu dà hào / xiǎo hào ma?',
      meaning: {
        en: 'Do you have a large/small size?',
        fr: 'Avez-vous une grande/petite taille ?',
      },
    
      audio: '/audio/convenience-store-run/pattern-10.mp3',},
    {
      id: 'convenience-store-run-pattern-11',
      pattern: '可以刷卡吗？',
      pinyin: 'Kě yǐ shuā kǎ ma?',
      meaning: {
        en: 'Can I pay by card?',
        fr: 'Puis-je payer par carte ?',
      },
    
      audio: '/audio/convenience-store-run/pattern-03-example-02.mp3',},
    {
      id: 'convenience-store-run-pattern-12',
      pattern: '我用微信支付 / 支付宝。',
      pinyin: 'Wǒ yòng Wēi xìn zhī fù / Zhī fù bǎo.',
      meaning: {
        en: 'I will use WeChat Pay / Alipay.',
        fr: 'Je vais utiliser WeChat Pay / Alipay.',
      },
      audio: '/audio/convenience-store-run/pattern-12.mp3',
    },
  ],
  vocabulary: [
    {
      id: 'convenience-store-run-vocab-1',
      hanzi: '一瓶水',
      pinyin: 'yì píng shuǐ',
      audio: '/audio/convenience-store-run/vocab-01.mp3',
      meaning: {
        en: 'a bottle of water',
        fr: 'une bouteille d\'eau',
      },
      explanation: {
        en: 'A common item to request at a convenience store.',
        fr: 'Un article courant à demander dans une supérette.',
      },
    },
    {
      id: 'convenience-store-run-vocab-2',
      hanzi: '还要别的吗',
      pinyin: 'hái yào bié de ma',
      audio: '/audio/convenience-store-run/vocab-02.mp3',
      meaning: {
        en: 'anything else?',
        fr: 'autre chose ?',
      },
      explanation: {
        en: 'Listen for this checkout question after naming your item.',
        fr: 'Écoute cette question à la caisse après avoir nommé ton article.',
      },
    },
    {
      id: 'convenience-store-run-vocab-3',
      hanzi: '不要了',
      pinyin: 'bú yào le',
      audio: '/audio/convenience-store-run/vocab-03.mp3',
      meaning: {
        en: 'no more / nothing else',
        fr: 'rien d\'autre',
      },
      explanation: {
        en: 'Use it to say you do not need anything else.',
        fr: 'Utilise-le pour dire que tu n\'as besoin de rien d\'autre.',
      },
    },
    {
      id: 'convenience-store-run-vocab-4',
      hanzi: '一共',
      pinyin: 'yí gòng',
      audio: '/audio/convenience-store-run/vocab-04.mp3',
      meaning: {
        en: 'altogether / in total',
        fr: 'au total',
      },
      explanation: {
        en: 'Use 一共 to ask for or state the total price of several items.',
        fr: 'Utilisez 一共 pour demander ou indiquer le prix total de plusieurs articles.',
      },
    },
    {
      id: 'convenience-store-run-vocab-5',
      hanzi: '多少钱',
      pinyin: 'duō shao qián',
      audio: '/audio/convenience-store-run/vocab-05.mp3',
      meaning: {
        en: 'how much? / how much does it cost?',
        fr: 'combien ? / combien ça coûte ?',
      },
      explanation: {
        en: 'The key phrase for asking a simple price.',
        fr: 'La phrase clé pour demander un prix simple.',
      },
    },
    { id: 'convenience-store-run-vocab-6', hanzi: '薯片', pinyin: 'shǔ piàn', audio: '/audio/convenience-store-run/vocab-06.mp3', meaning: { en: 'potato chips', fr: 'chips' }, explanation: { en: 'A common snack to buy in convenience stores.', fr: 'Un snack courant à acheter en supérette.' } },
    { id: 'convenience-store-run-vocab-7', hanzi: '袋子', pinyin: 'dài zi', audio: '/audio/convenience-store-run/vocab-07.mp3', meaning: { en: 'bag', fr: 'sac' }, explanation: { en: 'Ask for a 袋子 if you need something to carry your items.', fr: 'Demande un 袋子 si tu as besoin de porter tes articles.' } },
    { id: 'convenience-store-run-vocab-8', hanzi: '扫码', pinyin: 'sǎo mǎ', audio: '/audio/convenience-store-run/vocab-08.mp3', meaning: { en: 'scan a QR code / scan to pay', fr: 'scanner un code QR / scanner pour payer' }, explanation: { en: 'The clerk points to the QR code and says this.', fr: 'L\'employé montre le code QR et dit ceci.' } },
    { id: 'convenience-store-run-vocab-9', hanzi: '毛', pinyin: 'máo', audio: '/audio/convenience-store-run/vocab-09.mp3', meaning: { en: 'jiao / one-tenth of a yuan', fr: 'dixième de yuan' }, explanation: { en: 'A colloquial unit used for tenths of a yuan in prices.', fr: 'Une unité courante correspondant à un dixième de yuan dans les prix.' } },
    { id: 'convenience-store-run-vocab-10', hanzi: '小票', pinyin: 'xiǎo piào', audio: '/audio/convenience-store-run/vocab-10.mp3', meaning: { en: 'receipt', fr: 'ticket de caisse' }, explanation: { en: 'The small receipt you get after paying at a store.', fr: 'Le petit reçu que tu obtiens après avoir payé en magasin.' } },
  ],
  practice: {
    listening: [
      {
        id: 'convenience-store-run-listening-1',
        prompt: {
          en: 'Listen for the phrase that means a bottle of water.',
          fr: 'Écoute la phrase qui signifie une bouteille d\'eau.',
        },
        target: '一瓶水',
        audio: '/audio/convenience-store-run/practice-listening-01.mp3',
        explanation: {
          en: 'A bottle of water is a common item to request at a convenience store.',
          fr: 'Une bouteille d’eau est un article courant à demander dans une supérette.',
        },
      },
      { id: 'convenience-store-run-listening-2', prompt: { en: 'Which phrase asks for a bag?', fr: 'Quelle phrase demande un sac ?' }, target: '有袋子吗？', audio: '/audio/convenience-store-run/practice-listening-02.mp3', explanation: { en: '有 = have｜袋子 = bag｜吗 = yes-or-no question particle. Ask this at checkout to see whether the store provides bags.', fr: '有 = avoir｜袋子 = sac｜吗 = particule de question fermée. Posez cette question à la caisse pour savoir si le magasin fournit des sacs.' } },
    ],
    speaking: [
      {
        id: 'convenience-store-run-speaking-1',
        prompt: {
          en: 'Say you do not need anything else.',
          fr: 'Dis que tu n\'as besoin de rien d\'autre.',
        },
        target: '不要了。',
        audio: '/audio/convenience-store-run/practice-speaking-01.mp3',
        explanation: {
          en: '不要 = do not want / need｜了 = that is all now. Use this to answer the clerk’s ‘Anything else?’ question.',
          fr: '不要 = ne pas vouloir / avoir besoin｜了 = c’est tout maintenant. Utilisez cette réponse lorsque l’employé demande « autre chose ? ».',
        },
      },
      { id: 'convenience-store-run-speaking-2', prompt: { en: 'Ask if they have a bag.', fr: 'Demande s\'ils ont un sac.' }, target: '有袋子吗？', audio: '/audio/convenience-store-run/practice-speaking-02.mp3', explanation: { en: '有 = have｜袋子 = bag｜吗 = yes-or-no question particle. Ask this practical question when you need a bag for your purchases.', fr: '有 = avoir｜袋子 = sac｜吗 = particule de question fermée. Posez cette question pratique si vous avez besoin d’un sac pour vos achats.' } },
    ],
    reading: [
      {
        id: 'convenience-store-run-reading-1',
        prompt: {
          en: 'Choose the phrase for asking the total price.',
          fr: 'Choisis la phrase pour demander le prix total.',
        },
        target: '一共多少钱？',
        audio: '/audio/convenience-store-run/practice-reading-01.mp3',
        explanation: {
          en: '一共 = altogether / in total｜多少 = how much｜钱 = money. Use this at checkout to ask for the total.',
          fr: '一共 = au total｜多少 = combien｜钱 = argent. Utilisez cette question à la caisse pour demander le total.',
        },
      },
      { id: 'convenience-store-run-reading-2', prompt: { en: 'Match the word for potato chips.', fr: 'Associe le mot pour chips.' }, target: '薯片', audio: '/audio/convenience-store-run/practice-reading-02.mp3', explanation: { en: '薯片 is a common snack you will see on shelves.', fr: '薯片 est un snack courant que tu verras dans les rayons.' } },
    ],
  },
  reviewCards: [
    {
      id: 'convenience-store-run-review-1',
      front: '一瓶水',
      back: {
        en: 'a bottle of water',
        fr: 'une bouteille d\'eau',
      },
      explanation: {
        en: 'A practical first convenience store item.',
        fr: 'Un premier article pratique en supérette.',
      },
    },
    {
      id: 'convenience-store-run-review-2',
      front: '多少钱',
      back: {
        en: 'how much? / how much does it cost?',
        fr: 'combien ça coûte ?',
      },
      explanation: {
        en: 'Use this to ask a simple price.',
        fr: 'Utilise cette phrase pour demander un prix simple.',
      },
    },
    {
      id: 'convenience-store-run-review-3',
      front: '不要了',
      back: {
        en: 'no more / nothing else',
        fr: 'rien d\'autre',
      },
      explanation: {
        en: 'A short response when the clerk asks if you want anything else.',
        fr: 'Une réponse courte quand l\'employé demande si tu veux autre chose.',
      },
    },
    { id: 'convenience-store-run-review-4', front: '薯片', back: { en: 'potato chips', fr: 'chips' }, explanation: { en: 'A snack to grab at any convenience store.', fr: 'Un snack à prendre dans n\'importe quelle supérette.' } },
    { id: 'convenience-store-run-review-5', front: '袋子', back: { en: 'bag', fr: 'sac' }, explanation: { en: 'Ask for this when you buy several items.', fr: 'Demande ceci quand tu achètes plusieurs articles.' } },
    { id: 'convenience-store-run-review-6', front: '扫码', back: { en: 'scan to pay', fr: 'scanner pour payer' }, explanation: { en: 'The payment action at the counter.', fr: 'L\'action de paiement au comptoir.' } },
  ],
}
