import type { LessonContent } from '../types.js'

export const convenienceStoreRunLesson: LessonContent = {
  id: 'convenience-store-run',
  title: {
    en: '购物 / Shopping',
    fr: '购物 / Shopping',
  },
  scenario: {
    en: 'Phrases to navigate stores, check prices, bargain and pay smoothly.',
    fr: 'Des phrases pour se repérer en magasin, vérifier les prix, négocier et payer facilement.',
  },
  dialogue: {
    title: {
      en: 'Buy one simple item',
      fr: 'Acheter un article simple',
    },
    lines: [
      {
        id: 'convenience-store-run-line-01',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '这个多少钱?',
        pinyin: 'Zhè ge duō shǎo qián?',
        translation: { en: 'How much is this?', fr: 'C\'est combien ?' },
        explanation: { en: 'Point at an item and ask 这个多少钱 to check the price.', fr: 'Montre un article et demande 这个多少钱 pour vérifier le prix.' },
        audio: '/audio/convenience-store-run/line-01.mp3',
      },
      {
        id: 'convenience-store-run-line-02',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '太贵了。',
        pinyin: 'Tài guì le.',
        translation: { en: 'It\'s too expensive.', fr: 'C\'est trop cher.' },
        explanation: { en: '太贵了 tells the seller the price feels too high.', fr: '太贵了 dit au vendeur que le prix est trop élevé.' },
        audio: '/audio/convenience-store-run/line-02.mp3',
      },
      {
        id: 'convenience-store-run-line-03',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '可以便宜一点吗?',
        pinyin: 'Kě yǐ pián yi yì diǎn ma?',
        translation: { en: 'Can you make it cheaper?', fr: 'Pouvez-vous baisser un peu le prix ?' },
        explanation: { en: 'Use 可以…吗 to ask politely for a lower price or other help.', fr: 'Utilise 可以…吗 pour demander poliment un prix plus bas ou de l\'aide.' },
        audio: '/audio/convenience-store-run/line-03.mp3',
      },
      {
        id: 'convenience-store-run-line-04',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我只是看看。',
        pinyin: 'Wǒ zhǐ shì kàn kàn.',
        translation: { en: 'I am just looking.', fr: 'Je regarde juste.' },
        explanation: { en: 'Say 我只是看看 when you do not want to buy yet.', fr: 'Dis 我只是看看 quand tu ne veux pas encore acheter.' },
        audio: '/audio/convenience-store-run/line-04.mp3',
      },
      {
        id: 'convenience-store-run-line-05',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '有别的颜色吗?',
        pinyin: 'Yǒu bié de yán sè ma?',
        translation: { en: 'Do you have other colors?', fr: 'Avez-vous d\'autres couleurs ?' },
        explanation: { en: 'Ask 有别的颜色吗 to check for other color options.', fr: 'Demande 有别的颜色吗 pour vérifier les autres couleurs.' },
        audio: '/audio/convenience-store-run/line-05.mp3',
      },
      {
        id: 'convenience-store-run-line-06',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我可以试试吗？',
        pinyin: 'Wǒ kě yǐ shì shì ma?',
        translation: { en: 'Can I try it on?', fr: 'Puis-je l\'essayer ?' },
        explanation: { en: 'Ask 我可以试试吗 before trying on clothing.', fr: 'Demande 我可以试试吗 avant d\'essayer des vêtements.' },
        audio: '/audio/convenience-store-run/line-06.mp3',
      },
      {
        id: 'convenience-store-run-line-07',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '试衣间在哪里?',
        pinyin: 'Shì yī jiān zài nǎ lǐ?',
        translation: { en: 'Where is the fitting room?', fr: 'Où est la cabine d\'essayage ?' },
        explanation: { en: 'Ask 试衣间在哪里 to find the fitting room.', fr: 'Demande 试衣间在哪里 pour trouver la cabine d\'essayage.' },
        audio: '/audio/convenience-store-run/line-07.mp3',
      },
      {
        id: 'convenience-store-run-line-08',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '有大号/小号吗?',
        pinyin: 'Yǒu dà hào / xiǎo hào ma?',
        translation: { en: 'Do you have a large/small size?', fr: 'Avez-vous une grande/petite taille ?' },
        explanation: { en: 'Ask 有大号/小号吗 to check available sizes.', fr: 'Demande 有大号/小号吗 pour vérifier les tailles disponibles.' },
        audio: '/audio/convenience-store-run/line-08.mp3',
      },
      {
        id: 'convenience-store-run-line-09',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我买这个。',
        pinyin: 'Wǒ mǎi zhè ge.',
        translation: { en: 'I will buy this.', fr: 'Je prends ceci.' },
        explanation: { en: 'Say 我买这个 to confirm the item you want.', fr: 'Dis 我买这个 pour confirmer l\'article que tu veux.' },
        audio: '/audio/convenience-store-run/line-09.mp3',
      },
      {
        id: 'convenience-store-run-line-10',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '有袋子吗?',
        pinyin: 'Yǒu dài zi ma?',
        translation: { en: 'Do you have a bag?', fr: 'Avez-vous un sac ?' },
        explanation: { en: 'Use 有…吗 to check if an item or service is available.', fr: 'Utilise 有…吗 pour vérifier si un article ou un service est disponible.' },
        audio: '/audio/convenience-store-run/line-10.mp3',
      },
      {
        id: 'convenience-store-run-line-11',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '你好，我要一瓶水。',
        pinyin: 'Nǐ hǎo, wǒ yào yì píng shuǐ.',
        translation: { en: 'A bottle of water please.', fr: 'Bonjour, une bouteille d\'eau, s\'il vous plaît.' },
        explanation: { en: 'Ask for a bottle of water with 我要一瓶水.', fr: 'Demande une bouteille d\'eau avec 我要一瓶水.' },
        audio: '/audio/convenience-store-run/line-11.mp3',
      },
      {
        id: 'convenience-store-run-line-12',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '一共多少钱?',
        pinyin: 'Yí gòng duō shǎo qián?',
        translation: { en: 'How much is it?', fr: 'C\'est combien au total ?' },
        explanation: { en: 'Ask 一共多少钱 to get the total at checkout.', fr: 'Demande 一共多少钱 pour connaître le total à la caisse.' },
        audio: '/audio/convenience-store-run/line-12.mp3',
      },
      {
        id: 'convenience-store-run-line-13',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '可以刷卡吗?',
        pinyin: 'Kě yǐ shuā kǎ ma?',
        translation: { en: 'Can I swipe a card?', fr: 'Puis-je payer par carte ?' },
        explanation: { en: 'Ask 可以刷卡吗 to check if card payment is accepted.', fr: 'Demande 可以刷卡吗 pour vérifier si le paiement par carte est accepté.' },
        audio: '/audio/convenience-store-run/line-13.mp3',
      },
      {
        id: 'convenience-store-run-line-14',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我用微信支付 / 支付宝。',
        pinyin: 'Wǒ yòng Wēi xìn zhī fù / Zhī fù bǎo.',
        translation: { en: 'I will use WeChat Pay / Alipay.', fr: 'Je vais payer avec WeChat / Alipay.' },
        explanation: { en: 'Tell the clerk how you will pay with 微信支付 or 支付宝.', fr: 'Indique au vendeur comment tu vas payer avec 微信支付 ou 支付宝.' },
        audio: '/audio/convenience-store-run/line-14.mp3',
      },
    ],
  },
    sentencePatterns: [
    {
      id: 'convenience-store-run-pattern-1',
      pattern: '……多少钱？',
      pinyin: '... duō shao qián?',
      meaning: {
        en: 'How much is this?',
        fr: 'C\'est combien ?',
      },
      examples: [
        {
          fill: '这个',
          fillPinyin: 'zhège',
          hanzi: '这个多少钱？',
          pinyin: 'Zhè ge duō shao qián?',
          en: 'this',
          fr: 'ceci',
          audio: '/audio/convenience-store-run/pattern-01-example-01.mp3',
        },
        {
          fill: '水',
          fillPinyin: 'shuǐ',
          hanzi: '水多少钱？',
          pinyin: 'Shuǐ duō shao qián?',
          en: 'water',
          fr: 'l\'eau',
          audio: '/audio/convenience-store-run/pattern-01-example-02.mp3',
        },
        {
          fill: '面包',
          fillPinyin: 'miànbāo',
          hanzi: '面包多少钱？',
          pinyin: 'Miàn bāo duō shao qián?',
          en: 'bread',
          fr: 'le pain',
          audio: '/audio/convenience-store-run/pattern-01-example-03.mp3',
        },
      ],
    },
    {
      id: 'convenience-store-run-pattern-2',
      pattern: '太……了。',
      pinyin: 'Tài ... le.',
      meaning: {
        en: 'It\'s too ...',
        fr: 'C\'est trop ...',
      },
      audio: '/audio/convenience-store-run/pattern-02.mp3',
      examples: [
        {
          fill: '贵',
          fillPinyin: 'guì',
          hanzi: '太贵了。',
          pinyin: 'Tài guì le.',
          en: 'expensive',
          fr: 'cher',
          audio: '/audio/convenience-store-run/pattern-02-example-01.mp3',
        },
        {
          fill: '便宜',
          fillPinyin: 'piányi',
          hanzi: '太便宜了。',
          pinyin: 'Tài pián yi le.',
          en: 'cheap',
          fr: 'bon marché',
          audio: '/audio/convenience-store-run/pattern-02-example-02.mp3',
        },
        {
          fill: '麻烦',
          fillPinyin: 'máfan',
          hanzi: '太麻烦了。',
          pinyin: 'Tài má fan le.',
          en: 'troublesome',
          fr: 'compliqué',
          audio: '/audio/convenience-store-run/pattern-02-example-03.mp3',
        },
      ],
    },
    {
      id: 'convenience-store-run-pattern-3',
      pattern: '可以……吗？',
      pinyin: 'Kě yǐ ... ma?',
      meaning: {
        en: 'Can you ...?',
        fr: 'Pouvez-vous ... ?',
      },
      examples: [
        {
          fill: '便宜一点',
          fillPinyin: 'piányi yìdiǎn',
          hanzi: '可以便宜一点吗？',
          pinyin: 'Kě yǐ pián yi yì diǎn ma?',
          en: 'a bit cheaper',
          fr: 'un peu moins cher',
          audio: '/audio/convenience-store-run/pattern-03-example-01.mp3',
        },
        {
          fill: '刷卡',
          fillPinyin: 'shuā kǎ',
          hanzi: '可以刷卡吗？',
          pinyin: 'Kě yǐ shuā kǎ ma?',
          en: 'pay by card',
          fr: 'payer par carte',
          audio: '/audio/convenience-store-run/pattern-03-example-02.mp3',
        },
        {
          fill: '试试',
          fillPinyin: 'shìshi',
          hanzi: '可以试试吗？',
          pinyin: 'Kě yǐ shì shi ma?',
          en: 'try it',
          fr: 'essayer',
          audio: '/audio/convenience-store-run/pattern-03-example-03.mp3',
        },
      ],
    },
    {
      id: 'convenience-store-run-pattern-4',
      pattern: '我买这个。',
      pinyin: 'Wǒ mǎi zhè ge.',
      meaning: {
        en: 'I will buy this.',
        fr: 'Je prends ceci.',
      },
      audio: '/audio/convenience-store-run/pattern-04.mp3',
    },
    {
      id: 'convenience-store-run-pattern-5',
      pattern: '有……吗？',
      pinyin: 'Yǒu ... ma?',
      meaning: {
        en: 'Do you have ...?',
        fr: 'Avez-vous ... ?',
      },
      examples: [
        {
          fill: '袋子',
          fillPinyin: 'dàizi',
          hanzi: '有袋子吗？',
          pinyin: 'Yǒu dài zi ma?',
          en: 'a bag',
          fr: 'un sac',
          audio: '/audio/convenience-store-run/pattern-05-example-01.mp3',
        },
        {
          fill: '热咖啡',
          fillPinyin: 'rè kāfēi',
          hanzi: '有热咖啡吗？',
          pinyin: 'Yǒu rè kā fēi ma?',
          en: 'hot coffee',
          fr: 'du café chaud',
          audio: '/audio/convenience-store-run/pattern-05-example-02.mp3',
        },
        {
          fill: '别的颜色',
          fillPinyin: 'bié de yánsè',
          hanzi: '有别的颜色吗？',
          pinyin: 'Yǒu bié de yán sè ma?',
          en: 'other colors',
          fr: 'd\'autres couleurs',
          audio: '/audio/convenience-store-run/pattern-05-example-03.mp3',
        },
      ],
    },
    {
      id: 'convenience-store-run-pattern-6',
      pattern: '我只是看看。',
      pinyin: 'Wǒ zhǐ shì kàn kan.',
      meaning: {
        en: 'I am just looking.',
        fr: 'Je regarde juste.',
      },
    },
    {
      id: 'convenience-store-run-pattern-7',
      pattern: '有别的颜色吗？',
      pinyin: 'Yǒu bié de yán sè ma?',
      meaning: {
        en: 'Do you have other colors?',
        fr: 'Avez-vous d\'autres couleurs ?',
      },
    },
    {
      id: 'convenience-store-run-pattern-8',
      pattern: '我可以试试吗？',
      pinyin: 'Wǒ kě yǐ shì shi ma?',
      meaning: {
        en: 'Can I try it on?',
        fr: 'Puis-je l\'essayer ?',
      },
    },
    {
      id: 'convenience-store-run-pattern-9',
      pattern: '试衣间在哪里？',
      pinyin: 'Shì yī jiān zài nǎ lǐ?',
      meaning: {
        en: 'Where is the fitting room?',
        fr: 'Où est la cabine d\'essayage ?',
      },
    },
    {
      id: 'convenience-store-run-pattern-10',
      pattern: '有大号/小号吗？',
      pinyin: 'Yǒu dà hào / xiǎo hào ma?',
      meaning: {
        en: 'Do you have a large/small size?',
        fr: 'Avez-vous une grande/petite taille ?',
      },
    },
    {
      id: 'convenience-store-run-pattern-11',
      pattern: '可以刷卡吗？',
      pinyin: 'Kě yǐ shuā kǎ ma?',
      meaning: {
        en: 'Can I pay by card?',
        fr: 'Puis-je payer par carte ?',
      },
    },
    {
      id: 'convenience-store-run-pattern-12',
      pattern: '我用微信支付 / 支付宝。',
      pinyin: 'Wǒ yòng Wēi xìn zhī fù / Zhī fù bǎo.',
      meaning: {
        en: 'I will use WeChat Pay / Alipay.',
        fr: 'Je vais payer avec WeChat / Alipay.',
      },
      audio: '/audio/convenience-store-run/pattern-12.mp3',
    },
  ],
  vocabulary: [
    {
      id: 'convenience-store-run-vocab-1',
      hanzi: '一瓶水',
      pinyin: 'yì píng shuǐ',
      audio: '/audio/convenience-store-run/vocab-01.mp3',
      meaning: {
        en: 'a bottle of water',
        fr: 'une bouteille d\'eau',
      },
      explanation: {
        en: 'A useful first purchase item after arriving.',
        fr: 'Un premier achat utile après l\'arrivée.',
      },
    },
    {
      id: 'convenience-store-run-vocab-2',
      hanzi: '还要别的吗',
      pinyin: 'hái yào bié de ma',
      audio: '/audio/convenience-store-run/vocab-02.mp3',
      meaning: {
        en: 'anything else?',
        fr: 'autre chose ?',
      },
      explanation: {
        en: 'Listen for this checkout question after naming your item.',
        fr: 'Écoute cette question à la caisse après avoir nommé ton article.',
      },
    },
    {
      id: 'convenience-store-run-vocab-3',
      hanzi: '不要了',
      pinyin: 'bú yào le',
      audio: '/audio/convenience-store-run/vocab-03.mp3',
      meaning: {
        en: 'no more / nothing else',
        fr: 'rien d\'autre',
      },
      explanation: {
        en: 'Use it to say you do not need anything else.',
        fr: 'Utilise-le pour dire que tu n\'as besoin de rien d\'autre.',
      },
    },
    {
      id: 'convenience-store-run-vocab-4',
      hanzi: '一共',
      pinyin: 'yí gòng',
      audio: '/audio/convenience-store-run/vocab-04.mp3',
      meaning: {
        en: 'altogether / in total',
        fr: 'au total',
      },
      explanation: {
        en: 'This word prepares the total price question.',
        fr: 'Ce mot prépare la question du prix total.',
      },
    },
    {
      id: 'convenience-store-run-vocab-5',
      hanzi: '多少钱',
      pinyin: 'duō shao qián',
      audio: '/audio/convenience-store-run/vocab-05.mp3',
      meaning: {
        en: 'how much money?',
        fr: 'combien d\'argent ? / combien ça coûte ?',
      },
      explanation: {
        en: 'The key phrase for asking a simple price.',
        fr: 'La phrase clé pour demander un prix simple.',
      },
    },
    { id: 'convenience-store-run-vocab-6', hanzi: '薯片', pinyin: 'shǔ piàn', audio: '/audio/convenience-store-run/vocab-06.mp3', meaning: { en: 'potato chips', fr: 'chips' }, explanation: { en: 'A common snack to buy in convenience stores.', fr: 'Un snack courant à acheter en supérette.' } },
    { id: 'convenience-store-run-vocab-7', hanzi: '袋子', pinyin: 'dài zi', audio: '/audio/convenience-store-run/vocab-07.mp3', meaning: { en: 'bag', fr: 'sac' }, explanation: { en: 'Ask for a 袋子 if you need something to carry your items.', fr: 'Demande un 袋子 si tu as besoin de porter tes articles.' } },
    { id: 'convenience-store-run-vocab-8', hanzi: '扫码', pinyin: 'sǎo mǎ', audio: '/audio/convenience-store-run/vocab-08.mp3', meaning: { en: 'scan code / scan to pay', fr: 'scanner le code / scanner pour payer' }, explanation: { en: 'The clerk points to the QR code and says this.', fr: 'L\'employé montre le code QR et dit ceci.' } },
    { id: 'convenience-store-run-vocab-9', hanzi: '毛', pinyin: 'máo', audio: '/audio/convenience-store-run/vocab-09.mp3', meaning: { en: 'dime / one-tenth of a yuan', fr: 'dixième de yuan' }, explanation: { en: '毛 is the smaller unit when a price is under one yuan.', fr: '毛 est la petite unité quand un prix est inférieur à un yuan.' } },
    { id: 'convenience-store-run-vocab-10', hanzi: '小票', pinyin: 'xiǎo piào', audio: '/audio/convenience-store-run/vocab-10.mp3', meaning: { en: 'receipt', fr: 'ticket de caisse' }, explanation: { en: 'The small receipt you get after paying at a store.', fr: 'Le petit reçu que tu obtiens après avoir payé en magasin.' } },
  ],
  practice: {
    listening: [
      {
        id: 'convenience-store-run-listening-1',
        prompt: {
          en: 'Listen for the phrase that means a bottle of water.',
          fr: 'Écoute la phrase qui signifie une bouteille d\'eau.',
        },
        target: '一瓶水',
        audio: '/audio/convenience-store-run/practice-listening-01.mp3',
        explanation: {
          en: '一瓶水 is the item you are buying.',
          fr: '一瓶水 est l\'article que tu achètes.',
        },
      },
      { id: 'convenience-store-run-listening-2', prompt: { en: 'Which phrase asks for a bag?', fr: 'Quelle phrase demande un sac ?' }, target: '有袋子吗？', audio: '/audio/convenience-store-run/practice-listening-02.mp3', explanation: { en: '有袋子吗 checks if the store provides bags.', fr: '有袋子吗 vérifie si le magasin fournit des sacs.' } },
    ],
    speaking: [
      {
        id: 'convenience-store-run-speaking-1',
        prompt: {
          en: 'Say you do not need anything else.',
          fr: 'Dis que tu n\'as besoin de rien d\'autre.',
        },
        target: '不要了。',
        audio: '/audio/convenience-store-run/practice-speaking-01.mp3',
        explanation: {
          en: '不要了 answers the clerk\'s "anything else?" question.',
          fr: '不要了 répond à la question « autre chose ? » de l\'employé.',
        },
      },
      { id: 'convenience-store-run-speaking-2', prompt: { en: 'Ask if they have a bag.', fr: 'Demande s\'ils ont un sac.' }, target: '有袋子吗？', audio: '/audio/convenience-store-run/practice-speaking-02.mp3', explanation: { en: 'A short practical question when buying several items.', fr: 'Une question pratique et courte quand on achète plusieurs articles.' } },
    ],
    reading: [
      {
        id: 'convenience-store-run-reading-1',
        prompt: {
          en: 'Choose the phrase for asking the total price.',
          fr: 'Choisis la phrase pour demander le prix total.',
        },
        target: '一共多少钱？',
        audio: '/audio/convenience-store-run/practice-reading-01.mp3',
        explanation: {
          en: '一共多少钱？ asks how much the purchase costs altogether.',
          fr: '一共多少钱？ demande combien coûte l\'achat au total.',
        },
      },
      { id: 'convenience-store-run-reading-2', prompt: { en: 'Match the word for potato chips.', fr: 'Associe le mot pour chips.' }, target: '薯片', audio: '/audio/convenience-store-run/practice-reading-02.mp3', explanation: { en: '薯片 is a common snack you will see on shelves.', fr: '薯片 est un snack courant que tu verras dans les rayons.' } },
    ],
  },
  reviewCards: [
    {
      id: 'convenience-store-run-review-1',
      front: '一瓶水',
      back: {
        en: 'a bottle of water',
        fr: 'une bouteille d\'eau',
      },
      explanation: {
        en: 'A practical first convenience store item.',
        fr: 'Un premier article pratique en supérette.',
      },
    },
    {
      id: 'convenience-store-run-review-2',
      front: '多少钱',
      back: {
        en: 'how much money?',
        fr: 'combien ça coûte ?',
      },
      explanation: {
        en: 'Use this to ask a simple price.',
        fr: 'Utilise cette phrase pour demander un prix simple.',
      },
    },
    {
      id: 'convenience-store-run-review-3',
      front: '不要了',
      back: {
        en: 'no more / nothing else',
        fr: 'rien d\'autre',
      },
      explanation: {
        en: 'A short response when the clerk asks if you want anything else.',
        fr: 'Une réponse courte quand l\'employé demande si tu veux autre chose.',
      },
    },
    { id: 'convenience-store-run-review-4', front: '薯片', back: { en: 'potato chips', fr: 'chips' }, explanation: { en: 'A snack to grab at any convenience store.', fr: 'Un snack à prendre dans n\'importe quelle supérette.' } },
    { id: 'convenience-store-run-review-5', front: '袋子', back: { en: 'bag', fr: 'sac' }, explanation: { en: 'Ask for this when you buy several items.', fr: 'Demande ceci quand tu achètes plusieurs articles.' } },
    { id: 'convenience-store-run-review-6', front: '扫码', back: { en: 'scan to pay', fr: 'scanner pour payer' }, explanation: { en: 'The payment action at the counter.', fr: 'L\'action de paiement au comptoir.' } },
  ],
}
