import type { LessonContent } from '../types.js'

export const metroTicketLesson: LessonContent = {
  id: 'metro-ticket',
  title: {
    en: '坐地铁 / Subway ride',
    fr: '坐地铁 / En métro',
  },
  scenario: {
    en: 'Buy a ticket, make a transit, ask for help, go in the right direction and find the right exit.',
    fr: 'Acheter un ticket, faire une correspondance, demander de l\'aide, aller dans la bonne direction et trouver la bonne sortie.',
  },
  dialogue: {
    title: {
      en: 'Ask for a route and ticket',
      fr: 'Demander un itinéraire et un ticket',
    },
    lines: [
      {
        id: 'metro-ticket-line-01',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请问地铁站在哪里？',
        pinyin: 'qǐng wèn dì tiě zhàn zài nǎ lǐ?',
        translation: { en: 'Excuse me, where is the subway station?', fr: 'Excusez-moi, où est la station de métro ?' },
        explanation: { en: '请问 = excuse me / may I ask｜地铁站 = metro station｜在 = be at｜哪里 = where. Use this polite question to ask for the station’s location.', fr: '请问 = excusez-moi｜地铁站 = station de métro｜在 = se trouver｜哪里 = où. Utilisez cette question polie pour demander où se trouve la station.' },
        audio: '/audio/metro-ticket/line-01.mp3',
      },
      {
        id: 'metro-ticket-line-02',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '在哪儿买票？',
        pinyin: 'zài nǎr mǎi piào?',
        translation: { en: 'Where can I buy a ticket?', fr: 'Où puis-je acheter un ticket ?' },
        explanation: { en: '在哪儿 = where｜买 = buy｜票 = ticket. Ask this when looking for a ticket machine or ticket counter.', fr: '在哪儿 = où｜买 = acheter｜票 = ticket. Posez cette question pour trouver un distributeur ou un guichet.' },
        audio: '/audio/metro-ticket/line-02.mp3',
      },
      {
        id: 'metro-ticket-line-03',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '您好，我要一张票。',
        pinyin: 'nín hǎo, wǒ yào yì zhāng piào.',
        translation: { en: 'Hello, I’d like one ticket.', fr: 'Bonjour, je voudrais un ticket.' },
        explanation: { en: '您好 = hello, politely｜我 = I｜要 = want / would like｜一张票 = one ticket. Use this polite sentence at a ticket counter.', fr: '您好 = bonjour, poliment｜我 = je｜要 = vouloir｜一张票 = un ticket. Utilisez cette phrase polie au guichet.' },
        audio: '/audio/metro-ticket/line-03.mp3',
      },
      {
        id: 'metro-ticket-line-04',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我要去天安门广场。',
        pinyin: 'wǒ yào qù tiān ān mén guǎng chǎng.',
        translation: { en: 'I want to go to Tiananmen Square.', fr: 'Je veux aller à la place Tiananmen.' },
        explanation: { en: '我 = I｜要 = want｜去 = go to｜天安门广场 = Tiananmen Square. Use 我要去 plus a place to state your destination.', fr: '我 = je｜要 = vouloir｜去 = aller à｜天安门广场 = place Tiananmen. Utilisez 我要去 suivi d’un lieu pour indiquer votre destination.' },
        audio: '/audio/metro-ticket/line-04.mp3',
      },
      {
        id: 'metro-ticket-line-05',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '自动售票机怎么用？',
        pinyin: 'zì dòng shòu piào jī zěn me yòng?',
        translation: { en: 'How do I use the ticket vending machine?', fr: 'Comment utiliser le distributeur de billets ?' },
        explanation: { en: '自动售票机 = ticket vending machine｜怎么 = how｜用 = use. Ask this when you need help operating the machine.', fr: '自动售票机 = distributeur de tickets｜怎么 = comment｜用 = utiliser. Posez cette question lorsque vous avez besoin d’aide avec la machine.' },
        audio: '/audio/metro-ticket/line-05.mp3',
      },
      {
        id: 'metro-ticket-line-06',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请问在哪儿换乘？',
        pinyin: 'qǐng wèn zài nǎr huàn chéng?',
        translation: { en: 'Excuse me, where do I transfer?', fr: 'Excusez-moi, où dois-je changer de ligne ?' },
        explanation: { en: '请问 = excuse me / may I ask｜在哪儿 = where｜换乘 = transfer. Ask this to find where to change lines.', fr: '请问 = excusez-moi｜在哪儿 = où｜换乘 = faire une correspondance. Posez cette question pour savoir où changer de ligne.' },
        audio: '/audio/metro-ticket/line-06.mp3',
      },
      {
        id: 'metro-ticket-line-07',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我要去这里。',
        pinyin: 'wǒ yào qù zhè lǐ.',
        translation: { en: 'I want to go to this place.', fr: 'Je veux aller à cet endroit.' },
        explanation: { en: '我 = I｜要 = want｜去 = go to｜这里 = here / this place. Point to a map while using this sentence to show your destination.', fr: '我 = je｜要 = vouloir｜去 = aller à｜这里 = ici / cet endroit. Montrez un lieu sur une carte en disant cette phrase.' },
        audio: '/audio/metro-ticket/line-07.mp3',
      },
      {
        id: 'metro-ticket-line-08',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '是这个方向吗？',
        pinyin: 'shì zhè ge fāng xiàng ma?',
        translation: { en: 'Is this the right direction?', fr: 'Est-ce la bonne direction ?' },
        explanation: { en: '是 = is｜这个 = this｜方向 = direction｜吗 = yes-or-no question particle. Use this to confirm that you are heading the right way.', fr: '是 = être｜这个 = ce / cette｜方向 = direction｜吗 = particule de question fermée. Utilisez cette phrase pour confirmer que vous allez dans la bonne direction.' },
        audio: '/audio/metro-ticket/line-08.mp3',
      },
      {
        id: 'metro-ticket-line-09',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请问，哪个出口去？',
        pinyin: 'qǐng wèn, nǎ gè chū kǒu qù?',
        translation: { en: 'Excuse me, which exit should I take?', fr: 'Excusez-moi, quelle sortie dois-je prendre ?' },
        explanation: { en: '请问 = excuse me / may I ask｜哪个 = which｜出口 = exit｜去 = go. Ask station staff which exit to take toward your destination.', fr: '请问 = excusez-moi｜哪个 = quel｜出口 = sortie｜去 = aller. Demandez au personnel quelle sortie prendre vers votre destination.' },
        audio: '/audio/metro-ticket/line-09.mp3',
      },
    ],
  },
    sentencePatterns: [
    {
      id: 'metro-ticket-pattern-1',
      pattern: '……在哪里？',
      pinyin: '... zài nǎ lǐ?',
      meaning: {
        en: 'Where is ...?',
        fr: 'Où est ... ?',
      },
      audio: '/audio/metro-ticket/pattern-01.mp3',
      examples: [
        {
          fill: '地铁站',
          fillPinyin: 'dì tiě zhàn',
          hanzi: '地铁站在哪里？',
          pinyin: 'dì tiě zhàn zài nǎ lǐ?',
          en: 'Where is the metro station?',
          fr: 'Où est la station de métro ?',
          audio: '/audio/metro-ticket/pattern-01-example-01.mp3',
        },
        {
          fill: '售票处',
          fillPinyin: 'shòu piào chù',
          hanzi: '售票处在哪里？',
          pinyin: 'shòu piào chù zài nǎ lǐ?',
          en: 'Where is the ticket office?',
          fr: 'Où est le guichet ?',
          audio: '/audio/metro-ticket/pattern-01-example-02.mp3',
        },
        {
          fill: '卫生间',
          fillPinyin: 'wèi shēng jiān',
          hanzi: '卫生间在哪里？',
          pinyin: 'wèi shēng jiān zài nǎ lǐ?',
          en: 'Where is the restroom?',
          fr: 'Où sont les toilettes ?',
          audio: '/audio/metro-ticket/pattern-01-example-03.mp3',
        },
      ],
    },
    {
      id: 'metro-ticket-pattern-2',
      pattern: '我要去……。',
      pinyin: 'wǒ yào qù ... .',
      meaning: {
        en: 'I want to go to ...',
        fr: 'Je veux aller à ...',
      },
      audio: '/audio/metro-ticket/pattern-02.mp3',
      examples: [
        {
          fill: '天安门广场',
          fillPinyin: 'tiān ān mén guǎng chǎng',
          hanzi: '我要去天安门广场。',
          pinyin: 'wǒ yào qù tiān ān mén guǎng chǎng.',
          en: 'I want to go to Tiananmen Square.',
          fr: 'Je veux aller à la place Tiananmen.',
          audio: '/audio/metro-ticket/pattern-02-example-01.mp3',
        },
        {
          fill: '王府井',
          fillPinyin: 'wáng fǔ jǐng',
          hanzi: '我要去王府井。',
          pinyin: 'wǒ yào qù wáng fǔ jǐng.',
          en: 'I want to go to Wangfujing.',
          fr: 'Je veux aller à Wangfujing.',
          audio: '/audio/metro-ticket/pattern-02-example-02.mp3',
        },
        {
          fill: '三里屯',
          fillPinyin: 'sān lǐ tún',
          hanzi: '我要去三里屯。',
          pinyin: 'wǒ yào qù sān lǐ tún.',
          en: 'I want to go to Sanlitun.',
          fr: 'Je veux aller à Sanlitun.',
          audio: '/audio/metro-ticket/pattern-02-example-03.mp3',
        },
      ],
    },
    {
      id: 'metro-ticket-pattern-3',
      pattern: '……怎么用？',
      pinyin: '... zěn me yòng?',
      meaning: {
        en: 'How do I use ...?',
        fr: 'Comment utiliser ... ?',
      },
      audio: '/audio/metro-ticket/pattern-03.mp3',
      examples: [
        {
          fill: '自动售票机',
          fillPinyin: 'zì dòng shòu piào jī',
          hanzi: '自动售票机怎么用？',
          pinyin: 'zì dòng shòu piào jī zěn me yòng?',
          en: 'How do I use the ticket vending machine?',
          fr: 'Comment utiliser le distributeur de tickets ?',
          audio: '/audio/metro-ticket/pattern-03-example-01.mp3',
        },
        {
          fill: '公交卡',
          fillPinyin: 'gōng jiāo kǎ',
          hanzi: '公交卡怎么用？',
          pinyin: 'gōng jiāo kǎ zěn me yòng?',
          en: 'How do I use the transit card?',
          fr: 'Comment utiliser la carte de transport ?',
          audio: '/audio/metro-ticket/pattern-03-example-02.mp3',
        },
        {
          fill: '共享单车',
          fillPinyin: 'gòng xiǎng dān chē',
          hanzi: '共享单车怎么用？',
          pinyin: 'gòng xiǎng dān chē zěn me yòng?',
          en: 'How do I use the shared bike?',
          fr: 'Comment utiliser le vélo partagé ?',
          audio: '/audio/metro-ticket/pattern-03-example-03.mp3',
        },
      ],
    }
    ],
  vocabulary: [
    {
      id: 'metro-ticket-vocab-1',
      hanzi: '地铁',
      pinyin: 'dì tiě',
      audio: '/audio/metro-ticket/vocab-01.mp3',
      meaning: {
        en: 'metro / subway',
        fr: 'métro',
      },
      explanation: {
        en: 'Use this word when asking for or talking about subway travel.',
        fr: 'Utilisez ce mot pour demander ou parler des déplacements en métro.',
      },
    },
    {
      id: 'metro-ticket-vocab-2',
      hanzi: '票',
      pinyin: 'piào',
      audio: '/audio/metro-ticket/vocab-02.mp3',
      meaning: {
        en: 'ticket',
        fr: 'ticket / billet',
      },
      explanation: {
        en: 'A shared word for metro and train tickets.',
        fr: 'Un mot commun pour les tickets de métro et billets de train.',
      },
    },
    {
      id: 'metro-ticket-vocab-3',
      hanzi: '站',
      pinyin: 'zhàn',
      audio: '/audio/metro-ticket/vocab-03.mp3',
      meaning: {
        en: 'stop / station',
        fr: 'station / arrêt',
      },
      explanation: {
        en: 'Count stops with a number plus 站.',
        fr: 'Compte les stations avec un nombre suivi de 站.',
      },
    },
    {
      id: 'metro-ticket-vocab-4',
      hanzi: '二号线',
      pinyin: 'èr hào xiàn',
      audio: '/audio/metro-ticket/vocab-04.mp3',
      meaning: {
        en: 'Line 2',
        fr: 'ligne 2',
      },
      explanation: {
        en: 'A standard way to name a numbered metro line.',
        fr: 'Une façon courante de nommer une ligne de métro numérotée.',
      },
    },
    {
      id: 'metro-ticket-vocab-5',
      hanzi: '换乘',
      pinyin: 'huàn chéng',
      audio: '/audio/metro-ticket/vocab-05.mp3',
      meaning: {
        en: 'transfer',
        fr: 'correspondance',
      },
      explanation: {
        en: 'Look for this word on signs when you need to change metro lines.',
        fr: 'Repérez ce mot sur les panneaux lorsque vous devez changer de ligne.',
      },
    },
    { id: 'metro-ticket-vocab-6', hanzi: '出口', pinyin: 'chū kǒu', audio: '/audio/metro-ticket/vocab-06.mp3', meaning: { en: 'exit', fr: 'sortie' }, explanation: { en: 'Look for 出口 signs to leave the station.', fr: 'Cherche les panneaux 出口 pour sortir de la station.' } },
    { id: 'metro-ticket-vocab-7', hanzi: '公交卡', pinyin: 'gōng jiāo kǎ', audio: '/audio/metro-ticket/vocab-07.mp3', meaning: { en: 'transit card', fr: 'carte de transport' }, explanation: { en: 'A rechargeable card for bus and metro rides.', fr: 'Une carte rechargeable pour les trajets en bus et métro.' } },
    { id: 'metro-ticket-vocab-8', hanzi: '一张', pinyin: 'yì zhāng', audio: '/audio/metro-ticket/vocab-08.mp3', meaning: { en: 'one (for flat items like tickets)', fr: 'un (pour les objets plats comme les tickets)' }, explanation: { en: 'Use 张 for tickets, paper, and flat objects.', fr: 'Utilise 张 pour les tickets, le papier et les objets plats.' } },
    { id: 'metro-ticket-vocab-9', hanzi: '充值', pinyin: 'chōng zhí', audio: '/audio/metro-ticket/vocab-09.mp3', meaning: { en: 'top up / recharge', fr: 'recharger' }, explanation: { en: 'Use 充值 to add money to your transit card.', fr: 'Utilise 充值 pour ajouter de l\'argent à ta carte de transport.' } },
    { id: 'metro-ticket-vocab-10', hanzi: '方向', pinyin: 'fāng xiàng', audio: '/audio/metro-ticket/vocab-10.mp3', meaning: { en: 'direction', fr: 'direction' }, explanation: { en: 'Check 方向 on metro signs to know which platform to take.', fr: 'Vérifie 方向 sur les panneaux de métro pour savoir quel quai prendre.' } },
    { id: 'metro-ticket-vocab-11', hanzi: '入口', pinyin: 'rù kǒu', audio: '/audio/metro-ticket/vocab-11.mp3', meaning: { en: 'entrance', fr: 'entrée' }, explanation: { en: 'The entrance you use to go into the metro station.', fr: 'L\'entrée que tu utilises pour entrer dans la station de métro.' } },
    { id: 'metro-ticket-vocab-12', hanzi: '自动售票机', pinyin: 'zì dòng shòu piào jī', audio: '/audio/metro-ticket/vocab-12.mp3', meaning: { en: 'ticket vending machine', fr: 'distributeur de tickets' }, explanation: { en: 'At many metro stations, use a ticket vending machine to choose your destination and buy a single-journey ticket; look for the English-language option on screen.', fr: 'Dans de nombreuses stations de métro, utilisez un distributeur pour choisir votre destination et acheter un ticket à l’unité ; cherchez l’option en anglais à l’écran.' } },
    { id: 'metro-ticket-vocab-13', hanzi: '上车', pinyin: 'shàng chē', audio: '/audio/metro-ticket/vocab-13.mp3', meaning: { en: 'get on the train', fr: 'monter dans le train' }, explanation: { en: 'Use this when boarding a bus, metro, or train; let passengers get off before you get on.', fr: 'Utilisez ce mot lorsque vous montez dans un bus, un métro ou un train ; laissez d’abord les passagers descendre.' } },
    { id: 'metro-ticket-vocab-14', hanzi: '下车', pinyin: 'xià chē', audio: '/audio/metro-ticket/vocab-14.mp3', meaning: { en: 'get off the train', fr: 'descendre du train' }, explanation: { en: 'Use this when telling a driver or companion which stop you plan to get off at, and listen for it in transport announcements.', fr: 'Utilisez ce mot pour indiquer à un chauffeur ou à un compagnon de voyage à quel arrêt vous comptez descendre, et repérez-le dans les annonces de transport.' } },
  ],
  practice: {
    listening: [
      {
        id: 'metro-ticket-listening-1',
        prompt: {
          en: 'Listen for the metro ticket to People\'s Square.',
          fr: 'Écoute le ticket de métro pour la Place du Peuple.',
        },
        target: '我要一张去人民广场的票。',
        audio: '/audio/metro-ticket/practice-listening-01.mp3',
        explanation: {
          en: '我要 = I would like｜一张 = one｜去人民广场的票 = ticket to People’s Square. Use this sentence to request a ticket to that destination.',
          fr: '我要 = je voudrais｜一张 = un｜去人民广场的票 = ticket pour la place du Peuple. Utilisez cette phrase pour demander un ticket vers cette destination.',
        },
      },
      { id: 'metro-ticket-listening-2', prompt: { en: 'Which phrase asks about a transfer?', fr: 'Quelle phrase demande une correspondance ?' }, target: '需要换乘吗？', audio: '/audio/metro-ticket/practice-listening-02.mp3', explanation: { en: '需要 = need｜换乘 = transfer｜吗 = yes-or-no question particle. Ask this to confirm whether the route requires changing lines.', fr: '需要 = devoir｜换乘 = faire une correspondance｜吗 = particule de question fermée. Posez cette question pour vérifier s’il faut changer de ligne.' } },
    ],
    speaking: [
      {
        id: 'metro-ticket-speaking-1',
        prompt: {
          en: 'Ask how to get to People\'s Square.',
          fr: 'Demande comment aller à la Place du Peuple.',
        },
        target: '去人民广场怎么走？',
        audio: '/audio/metro-ticket/practice-speaking-01.mp3',
        explanation: {
          en: '去人民广场 = to People’s Square｜怎么走 = how do I get there. Use this to ask for directions to the destination.',
          fr: '去人民广场 = vers la place du Peuple｜怎么走 = comment y aller. Utilisez cette phrase pour demander l’itinéraire vers la destination.',
        },
      },
      { id: 'metro-ticket-speaking-2', prompt: { en: 'Ask which exit to take.', fr: 'Demande quelle sortie prendre.' }, target: '哪个出口出去？', audio: '/audio/metro-ticket/practice-speaking-02.mp3', explanation: { en: '哪个 = which｜出口 = exit｜出去 = go out. Ask this at the destination station to choose the correct exit.', fr: '哪个 = quel｜出口 = sortie｜出去 = sortir. Posez cette question à la station d’arrivée pour choisir la bonne sortie.' } },
    ],
    reading: [
      {
        id: 'metro-ticket-reading-1',
        prompt: {
          en: 'Read the short stop-count question.',
          fr: 'Lis la question courte sur le nombre de stations.',
        },
        target: '要几站？',
        audio: '/audio/metro-ticket/practice-reading-01.mp3',
        explanation: {
          en: '要 = take / require｜几站 = how many stops. Ask this to learn how many stops the trip takes.',
          fr: '要 = nécessiter｜几站 = combien de stations. Posez cette question pour connaître le nombre d’arrêts du trajet.',
        },
      },
      { id: 'metro-ticket-reading-2', prompt: { en: 'Match the word for transit card.', fr: 'Associe le mot pour carte de transport.' }, target: '公交卡', audio: '/audio/metro-ticket/practice-reading-02.mp3', explanation: { en: '公交卡 is a reusable card for buses and metro.', fr: '公交卡 est une carte réutilisable pour les bus et le métro.' } },
    ],
  },
  reviewCards: [
    {
      id: 'metro-ticket-review-1',
      front: '地铁',
      back: {
        en: 'metro / subway',
        fr: 'métro',
      },
      explanation: {
        en: 'The transport word for the lesson.',
        fr: 'Le mot de transport de la leçon.',
      },
    },
    {
      id: 'metro-ticket-review-2',
      front: '二号线',
      back: {
        en: 'Line 2',
        fr: 'ligne 2',
      },
      explanation: {
        en: 'A model for numbered metro lines.',
        fr: 'Un modèle pour les lignes de métro numérotées.',
      },
    },
    {
      id: 'metro-ticket-review-3',
      front: '要几站？',
      back: {
        en: 'How many stops?',
        fr: 'Combien de stations ?',
      },
      explanation: {
        en: '要 = take / require｜几站 = how many stops. Ask this after identifying the line to learn the trip length.',
        fr: '要 = nécessiter｜几站 = combien de stations. Posez cette question après avoir identifié la ligne pour connaître la longueur du trajet.',
      },
    },
    { id: 'metro-ticket-review-4', front: '换乘', back: { en: 'transfer', fr: 'correspondance' }, explanation: { en: 'Look for this on signs when changing lines.', fr: 'Cherche ceci sur les panneaux en changeant de ligne.' } },
    { id: 'metro-ticket-review-5', front: '出口', back: { en: 'exit', fr: 'sortie' }, explanation: { en: 'Follow this sign to leave the station.', fr: 'Suis ce panneau pour quitter la station.' } },
    { id: 'metro-ticket-review-6', front: '公交卡', back: { en: 'transit card', fr: 'carte de transport' }, explanation: { en: 'A card for bus and metro rides.', fr: 'Une carte pour les trajets en bus et métro.' } },
  ],
}
