import type { LessonContent } from '../types.js'

export const pharmacyHelpLesson: LessonContent = {
  id: 'pharmacy-help',
  title: {
    en: '买药，看医生 / Hospital and pharmacy',
    fr: '买药，看医生 / Hôpital et pharmacie',
  },
  scenario: {
    en: 'Describe your discomfort and get the right treatment or medicine.',
    fr: 'Décris ton inconfort et obtiens le bon traitement ou le bon médicament.',
  },
  dialogue: {
    title: {
      en: 'Describe symptoms and buy medicine',
      fr: 'Décrire des symptômes et acheter un médicament',
    },
    lines: [
      {
        id: 'pharmacy-help-line-01',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请问哪里有医院？',
        pinyin: 'qǐng wèn nǎ lǐ yǒu yī yuàn?',
        translation: { en: 'Excuse me, where can I find a hospital?', fr: 'Excusez-moi, où puis-je trouver un hôpital ?' },
        explanation: { en: '请问 = excuse me / may I ask｜哪里 = where｜有 = there is / can find｜医院 = hospital. Use this to ask where you can find a hospital.', fr: '请问 = excusez-moi｜哪里 = où｜有 = il y a / trouver｜医院 = hôpital. Utilisez cette phrase pour demander où trouver un hôpital.' },
        audio: '/audio/pharmacy-help/line-01.mp3',
      },
      {
        id: 'pharmacy-help-line-02',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我要挂号。',
        pinyin: 'wǒ yào guà hào.',
        translation: { en: 'I need to register.', fr: 'Je dois m’inscrire.' },
        explanation: { en: '我 = I｜要 = want / need to｜挂号 = register for a medical visit. Say this at hospital reception before seeing a doctor.', fr: '我 = je｜要 = vouloir / devoir｜挂号 = s’inscrire pour une consultation. Dites cette phrase à l’accueil avant de voir un médecin.' },
        audio: '/audio/pharmacy-help/line-02.mp3',
      },
      {
        id: 'pharmacy-help-line-03',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我头痛。',
        pinyin: 'wǒ tóu tòng.',
        translation: { en: 'I have a headache.', fr: 'J\'ai mal à la tête.' },
        explanation: { en: '我 = I｜头 = head｜痛 = hurt / ache. Use this short sentence to report a headache.', fr: '我 = je｜头 = tête｜痛 = faire mal. Utilisez cette phrase courte pour signaler un mal de tête.' },
        audio: '/audio/pharmacy-help/line-03.mp3',
      },
      {
        id: 'pharmacy-help-line-04',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我发烧了。',
        pinyin: 'wǒ fā shāo le.',
        translation: { en: 'I have a fever.', fr: 'J\'ai de la fièvre.' },
        explanation: { en: '我 = I｜发烧 = have a fever｜了 = changed state. Use this to tell medical staff that you have developed a fever.', fr: '我 = je｜发烧 = avoir de la fièvre｜了 = changement de situation. Utilisez cette phrase pour signaler que vous avez de la fièvre.' },
        audio: '/audio/pharmacy-help/line-04.mp3',
      },
      {
        id: 'pharmacy-help-line-05',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我感冒了。',
        pinyin: 'wǒ gǎn mào le.',
        translation: { en: 'I have a cold.', fr: 'J\'ai attrapé un rhume.' },
        explanation: { en: '我 = I｜感冒 = have a cold｜了 = changed state. Say this to a doctor or pharmacist when you have a cold.', fr: '我 = je｜感冒 = avoir un rhume｜了 = changement de situation. Dites cette phrase au médecin ou au pharmacien si vous êtes enrhumé.' },
        audio: '/audio/pharmacy-help/line-05.mp3',
      },
      {
        id: 'pharmacy-help-line-06',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我肚子疼。',
        pinyin: 'wǒ dù zi téng.',
        translation: { en: 'I have a stomachache.', fr: 'J\'ai mal au ventre.' },
        explanation: { en: '我 = I｜肚子 = stomach / abdomen｜疼 = hurt. Put a body part before 疼 to say where you feel pain.', fr: '我 = je｜肚子 = ventre｜疼 = faire mal. Placez une partie du corps avant 疼 pour indiquer où vous avez mal.' },
        audio: '/audio/pharmacy-help/line-06.mp3',
      },
      {
        id: 'pharmacy-help-line-07',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我拉肚子了。',
        pinyin: 'wǒ lā dù zi le.',
        translation: { en: 'I have diarrhea.', fr: 'J\'ai la diarrhée.' },
        explanation: { en: '我 = I｜拉肚子 = have diarrhea｜了 = changed state. Use this direct sentence when reporting the symptom to medical staff.', fr: '我 = je｜拉肚子 = avoir la diarrhée｜了 = changement de situation. Utilisez cette phrase directe pour signaler le symptôme au personnel médical.' },
        audio: '/audio/pharmacy-help/line-07.mp3',
      },
      {
        id: 'pharmacy-help-line-08',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '谢谢医生。谢谢护士。',
        pinyin: 'xiè xie yī shēng. xiè xie hù shì.',
        translation: { en: 'Thank you, doctor. Thank you, nurse.', fr: 'Merci, docteur. Merci, infirmière.' },
        explanation: { en: '谢谢 = thank you｜医生 = doctor｜护士 = nurse. Use these two sentences to thank the doctor and nurse separately.', fr: '谢谢 = merci｜医生 = médecin｜护士 = infirmier / infirmière. Utilisez ces deux phrases pour remercier séparément le médecin et l’infirmier ou l’infirmière.' },
        audio: '/audio/pharmacy-help/line-08.mp3',
      },
      {
        id: 'pharmacy-help-line-09',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请问去哪里结账？',
        pinyin: 'qǐng wèn qù nǎ lǐ jié zhàng?',
        translation: { en: 'Excuse me, where do I pay?', fr: 'Excusez-moi, où dois-je payer la facture ?' },
        explanation: { en: '请问 = excuse me / may I ask｜去哪里 = where to go｜结账 = pay the bill. Ask this to locate the hospital payment counter.', fr: '请问 = excusez-moi｜去哪里 = où aller｜结账 = régler la facture. Posez cette question pour trouver la caisse de l’hôpital.' },
        audio: '/audio/pharmacy-help/line-09.mp3',
      },
      {
        id: 'pharmacy-help-line-10',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '去哪里取药？',
        pinyin: 'qù nǎ lǐ qǔ yào?',
        translation: { en: 'Where do I pick up the medicine?', fr: 'Où dois-je retirer mon médicament ?' },
        explanation: { en: '去哪里 = where to go｜取药 = collect medicine. Ask this after paying to find the medicine pickup counter.', fr: '去哪里 = où aller｜取药 = retirer les médicaments. Posez cette question après le paiement pour trouver le guichet de retrait.' },
        audio: '/audio/pharmacy-help/line-10.mp3',
      },
      {
        id: 'pharmacy-help-line-11',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我想买药。',
        pinyin: 'wǒ xiǎng mǎi yào.',
        translation: { en: 'I want to buy medicine.', fr: 'Je veux acheter des médicaments.' },
        explanation: { en: '我 = I｜想 = would like / want｜买 = buy｜药 = medicine. Use this at a pharmacy to say what you want to purchase.', fr: '我 = je｜想 = souhaiter / vouloir｜买 = acheter｜药 = médicament. Utilisez cette phrase à la pharmacie pour indiquer ce que vous voulez acheter.' },
        audio: '/audio/pharmacy-help/line-11.mp3',
      },
      {
        id: 'pharmacy-help-line-12',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '饭前吃还是饭后吃？',
        pinyin: 'fàn qián chī hái shì fàn hòu chī?',
        translation: { en: 'Should I take it before or after meals?', fr: 'Dois-je le prendre avant ou après les repas ?' },
        explanation: { en: '饭前 = before meals｜吃 = take / eat｜还是 = or｜饭后 = after meals. Ask this to confirm when the medicine should be taken.', fr: '饭前 = avant les repas｜吃 = prendre / manger｜还是 = ou｜饭后 = après les repas. Posez cette question pour confirmer quand prendre le médicament.' },
        audio: '/audio/pharmacy-help/line-12.mp3',
      },
      {
        id: 'pharmacy-help-line-13',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '多少钱？',
        pinyin: 'duō shǎo qián?',
        translation: { en: 'How much is it?', fr: 'Combien ça coûte ?' },
        explanation: { en: '多少 = how much｜钱 = money. Ask this to check the price of medicine or treatment.', fr: '多少 = combien｜钱 = argent. Posez cette question pour connaître le prix d’un médicament ou d’un soin.' },
        audio: '/audio/pharmacy-help/line-13.mp3',
      },
    ],
  },
    sentencePatterns: [
    {
      id: 'pharmacy-help-pattern-1',
      pattern: '请问哪里有……？',
      pinyin: 'qǐng wèn nǎ lǐ yǒu ... ?',
      meaning: {
        en: 'Excuse me, where can I find ...?',
        fr: 'Excusez-moi, où puis-je trouver ... ?',
      },
      audio: '/audio/pharmacy-help/pattern-01.mp3',
      examples: [
        {
          fill: '医院',
          fillPinyin: 'yī yuàn',
          hanzi: '请问哪里有医院？',
          pinyin: 'qǐng wèn nǎ lǐ yǒu yī yuàn?',
          en: 'Excuse me, where can I find a hospital?',
          fr: 'Excusez-moi, où puis-je trouver un hôpital ?',
          audio: '/audio/pharmacy-help/pattern-01-example-01.mp3',
        },
        {
          fill: '药店',
          fillPinyin: 'yào diàn',
          hanzi: '请问哪里有药店？',
          pinyin: 'qǐng wèn nǎ lǐ yǒu yào diàn?',
          en: 'Excuse me, where can I find a pharmacy?',
          fr: 'Excusez-moi, où puis-je trouver une pharmacie ?',
          audio: '/audio/pharmacy-help/pattern-01-example-02.mp3',
        },
        {
          fill: '卫生间',
          fillPinyin: 'wèi shēng jiān',
          hanzi: '请问哪里有卫生间？',
          pinyin: 'qǐng wèn nǎ lǐ yǒu wèi shēng jiān?',
          en: 'Excuse me, where can I find a restroom?',
          fr: 'Excusez-moi, où puis-je trouver des toilettes ?',
          audio: '/audio/pharmacy-help/pattern-01-example-03.mp3',
        },
      ],
    },
    {
      id: 'pharmacy-help-pattern-2',
      pattern: '我……疼。',
      pinyin: 'wǒ ... téng.',
      meaning: {
        en: 'My ... hurts.',
        fr: 'J\'ai mal à ...',
      },
      audio: '/audio/pharmacy-help/pattern-02.mp3',
      examples: [
        {
          fill: '肚子',
          fillPinyin: 'dù zi',
          hanzi: '我肚子疼。',
          pinyin: 'wǒ dù zi téng.',
          en: 'My stomach hurts.',
          fr: 'J’ai mal au ventre.',
          audio: '/audio/pharmacy-help/pattern-02-example-01.mp3',
        },
        {
          fill: '头',
          fillPinyin: 'tóu',
          hanzi: '我头疼。',
          pinyin: 'wǒ tóu téng.',
          en: 'My head hurts.',
          fr: 'J’ai mal à la tête.',
          audio: '/audio/pharmacy-help/pattern-02-example-02.mp3',
        },
        {
          fill: '牙',
          fillPinyin: 'yá',
          hanzi: '我牙疼。',
          pinyin: 'wǒ yá téng.',
          en: 'My tooth hurts.',
          fr: 'J’ai mal à une dent.',
          audio: '/audio/pharmacy-help/pattern-02-example-03.mp3',
        },
      ],
    },
    {
      id: 'pharmacy-help-pattern-3',
      pattern: '我……了。',
      pinyin: 'wǒ ... le.',
      meaning: {
        en: 'I have ...',
        fr: 'J\'ai ...',
      },
      audio: '/audio/pharmacy-help/pattern-03.mp3',
      examples: [
        {
          fill: '发烧',
          fillPinyin: 'fā shāo',
          hanzi: '我发烧了。',
          pinyin: 'wǒ fā shāo le.',
          en: 'I have a fever.',
          fr: 'J’ai de la fièvre.',
          audio: '/audio/pharmacy-help/pattern-03-example-01.mp3',
        },
        {
          fill: '感冒',
          fillPinyin: 'gǎn mào',
          hanzi: '我感冒了。',
          pinyin: 'wǒ gǎn mào le.',
          en: 'I have a cold.',
          fr: 'J’ai un rhume.',
          audio: '/audio/pharmacy-help/pattern-03-example-02.mp3',
        },
        {
          fill: '拉肚子',
          fillPinyin: 'lā dù zi',
          hanzi: '我拉肚子了。',
          pinyin: 'wǒ lā dù zi le.',
          en: 'I have diarrhea.',
          fr: 'J’ai la diarrhée.',
          audio: '/audio/pharmacy-help/pattern-03-example-03.mp3',
        },
      ],
    },
    {
      id: 'pharmacy-help-pattern-4',
      pattern: '我想买……。',
      pinyin: 'wǒ xiǎng mǎi ... .',
      meaning: {
        en: 'I would like to buy ...',
        fr: 'Je voudrais acheter ...',
      },
      audio: '/audio/pharmacy-help/pattern-04.mp3',
      examples: [
        {
          fill: '药',
          fillPinyin: 'yào',
          hanzi: '我想买药。',
          pinyin: 'wǒ xiǎng mǎi yào.',
          en: 'I would like to buy medicine.',
          fr: 'Je voudrais acheter des médicaments.',
          audio: '/audio/pharmacy-help/pattern-04-example-01.mp3',
        },
        {
          fill: '感冒药',
          fillPinyin: 'gǎn mào yào',
          hanzi: '我想买感冒药。',
          pinyin: 'wǒ xiǎng mǎi gǎn mào yào.',
          en: 'I would like to buy cold medicine.',
          fr: 'Je voudrais acheter un médicament contre le rhume.',
          audio: '/audio/pharmacy-help/pattern-04-example-02.mp3',
        },
        {
          fill: '创可贴',
          fillPinyin: 'chuàng kě tiē',
          hanzi: '我想买创可贴。',
          pinyin: 'wǒ xiǎng mǎi chuàng kě tiē.',
          en: 'I would like to buy adhesive bandages.',
          fr: 'Je voudrais acheter des pansements adhésifs.',
          audio: '/audio/pharmacy-help/pattern-04-example-03.mp3',
        },
      ],
    }
    ],
  vocabulary: [
    {
      id: 'pharmacy-help-vocab-1',
      hanzi: '药店',
      pinyin: 'yào diàn',
      audio: '/audio/pharmacy-help/vocab-01.mp3',
      meaning: {
        en: 'pharmacy',
        fr: 'pharmacie',
      },
      explanation: {
        en: 'The place to buy medicine and ask a pharmacist for advice.',
        fr: 'Le lieu où acheter des médicaments et demander conseil à un pharmacien.',
      },
    },
    {
      id: 'pharmacy-help-vocab-2',
      hanzi: '药',
      pinyin: 'yào',
      audio: '/audio/pharmacy-help/vocab-02.mp3',
      meaning: {
        en: 'medicine',
        fr: 'médicament',
      },
      explanation: {
        en: 'At a pharmacy, tell the pharmacist your symptoms, ask which medicine is suitable, and confirm how much to take and how often.',
        fr: 'À la pharmacie, décrivez vos symptômes, demandez quel médicament convient et confirmez la dose ainsi que la fréquence de prise.',
      },
    },
    {
      id: 'pharmacy-help-vocab-3',
      hanzi: '头疼',
      pinyin: 'tóu téng',
      audio: '/audio/pharmacy-help/vocab-03.mp3',
      meaning: {
        en: 'headache',
        fr: 'mal à la tête',
      },
      explanation: {
        en: 'A common symptom to report to a doctor or pharmacist.',
        fr: 'Un symptôme courant à signaler à un médecin ou à un pharmacien.',
      },
    },
    {
      id: 'pharmacy-help-vocab-4',
      hanzi: '发烧',
      pinyin: 'fā shāo',
      audio: '/audio/pharmacy-help/vocab-04.mp3',
      meaning: {
        en: 'to have a fever',
        fr: 'avoir de la fièvre',
      },
      explanation: {
        en: 'Use this verb to report or ask about a fever.',
        fr: 'Utilisez ce verbe pour signaler ou demander s’il y a de la fièvre.',
      },
    },
    {
      id: 'pharmacy-help-vocab-5',
      hanzi: '过敏',
      pinyin: 'guò mǐn',
      audio: '/audio/pharmacy-help/vocab-05.mp3',
      meaning: {
        en: 'allergy / allergic',
        fr: 'allergie / allergique',
      },
      explanation: {
        en: 'An important safety word when discussing medicine or treatment.',
        fr: 'Un mot de sécurité important lorsqu’on parle de médicaments ou de soins.',
      },
    },
    { id: 'pharmacy-help-vocab-6', hanzi: '肚子疼', pinyin: 'dù zi téng', audio: '/audio/pharmacy-help/vocab-06.mp3', meaning: { en: 'stomach ache', fr: 'mal au ventre' }, explanation: { en: 'Another common symptom to report at the pharmacy.', fr: 'Un autre symptôme courant à signaler à la pharmacie.' } },
    { id: 'pharmacy-help-vocab-7', hanzi: '止疼药', pinyin: 'zhǐ téng yào', audio: '/audio/pharmacy-help/vocab-07.mp3', meaning: { en: 'painkiller', fr: 'antidouleur' }, explanation: { en: 'The kind of medicine you might ask for with a headache.', fr: 'Le type de médicament que tu pourrais demander pour un mal de tête.' } },
    { id: 'pharmacy-help-vocab-8', hanzi: '一次一片', pinyin: 'yí cì yí piàn', audio: '/audio/pharmacy-help/vocab-08.mp3', meaning: { en: 'one tablet per dose', fr: 'un comprimé par prise' }, explanation: { en: 'The dosage instruction you will hear with medicine.', fr: 'La consigne de dosage que tu entendras avec le médicament.' } },
    { id: 'pharmacy-help-vocab-9', hanzi: '饭前', pinyin: 'fàn qián', audio: '/audio/pharmacy-help/vocab-09.mp3', meaning: { en: 'before meals', fr: 'avant les repas' }, explanation: { en: 'One of the two common medicine timing words.', fr: 'Un des deux mots courants pour le moment de prise du médicament.' } },
    { id: 'pharmacy-help-vocab-10', hanzi: '饭后', pinyin: 'fàn hòu', audio: '/audio/pharmacy-help/vocab-10.mp3', meaning: { en: 'after meals', fr: 'après les repas' }, explanation: { en: 'The other common medicine timing word paired with 饭前.', fr: 'L’autre mot courant pour le moment de prise, associé à 饭前.' } },
    { id: 'pharmacy-help-vocab-11', hanzi: '医院', pinyin: 'yī yuàn', audio: '/audio/pharmacy-help/vocab-11.mp3', meaning: { en: 'hospital', fr: 'hôpital' }, explanation: { en: 'A place where you see a doctor or receive medical treatment.', fr: 'Un lieu où vous consultez un médecin ou recevez des soins.' } },
  ],
  practice: {
    listening: [
      {
        id: 'pharmacy-help-listening-1',
        prompt: {
          en: 'Listen for headache and no fever.',
          fr: 'Écoute “mal à la tête” et “pas de fièvre”.',
        },
        target: '我头疼，不发烧。',
        audio: '/audio/pharmacy-help/practice-listening-01.mp3',
        explanation: {
          en: '我头疼 = I have a headache｜不 = not｜发烧 = have a fever. Use this to report one symptom while denying another.',
          fr: '我头疼 = j’ai mal à la tête｜不 = ne… pas｜发烧 = avoir de la fièvre. Utilisez cette phrase pour signaler un symptôme tout en en niant un autre.',
        },
      },
      { id: 'pharmacy-help-listening-2', prompt: { en: 'Which phrase asks about allergies?', fr: 'Quelle phrase demande à propos des allergies ?' }, target: '你对什么过敏吗？', audio: '/audio/pharmacy-help/practice-listening-02.mp3', explanation: { en: '你 = you｜对什么 = to what｜过敏 = be allergic｜吗 = yes-or-no question particle. A pharmacist may ask this safety question before recommending medicine.', fr: '你 = vous｜对什么 = à quoi｜过敏 = être allergique｜吗 = particule de question fermée. Le pharmacien peut poser cette question avant de conseiller un médicament.' } },
    ],
    speaking: [
      {
        id: 'pharmacy-help-speaking-1',
        prompt: {
          en: 'Say that your head hurts.',
          fr: 'Dis que tu as mal à la tête.',
        },
        target: '我头疼。',
        audio: '/audio/pharmacy-help/practice-speaking-01.mp3',
        explanation: {
          en: '我 = I｜头 = head｜疼 = hurt. Use this short, clear sentence to report a headache.',
          fr: '我 = je｜头 = tête｜疼 = faire mal. Utilisez cette phrase courte et claire pour signaler un mal de tête.',
        },
      },
      { id: 'pharmacy-help-speaking-2', prompt: { en: 'Ask whether to take the medicine before or after meals.', fr: 'Demande si le médicament se prend avant ou après les repas.' }, target: '饭前还是饭后？', audio: '/audio/pharmacy-help/practice-speaking-02.mp3', explanation: { en: '饭前 = before meals｜还是 = or｜饭后 = after meals. Ask this concise question to confirm when to take the medicine.', fr: '饭前 = avant les repas｜还是 = ou｜饭后 = après les repas. Posez cette question concise pour confirmer le moment de la prise.' } },
    ],
    reading: [
      {
        id: 'pharmacy-help-reading-1',
        prompt: {
          en: 'Read the medicine frequency phrase.',
          fr: 'Lis la phrase de fréquence du médicament.',
        },
        target: '一天两次。',
        audio: '/audio/pharmacy-help/practice-reading-01.mp3',
        explanation: {
          en: '一天 = one day / per day｜两次 = two times. This dosage instruction means to take the medicine twice a day.',
          fr: '一天 = par jour｜两次 = deux fois. Cette consigne indique de prendre le médicament deux fois par jour.',
        },
      },
      { id: 'pharmacy-help-reading-2', prompt: { en: 'Match the dosage instruction.', fr: 'Associe la consigne de dosage.' }, target: '一次一片', audio: '/audio/pharmacy-help/practice-reading-02.mp3', explanation: { en: '一次 = each time / per dose｜一片 = one tablet. This instruction tells you how many tablets to take per dose.', fr: '一次 = à chaque prise｜一片 = un comprimé. Cette consigne indique le nombre de comprimés à prendre à chaque fois.' } },
    ],
  },
  reviewCards: [
    {
      id: 'pharmacy-help-review-1',
      front: '药店',
      back: {
        en: 'pharmacy',
        fr: 'pharmacie',
      },
      explanation: {
        en: 'The place where you buy medicine and speak with a pharmacist.',
        fr: 'Le lieu où vous achetez des médicaments et parlez à un pharmacien.',
      },
    },
    {
      id: 'pharmacy-help-review-2',
      front: '头疼',
      back: {
        en: 'headache',
        fr: 'mal à la tête',
      },
      explanation: {
        en: 'Say 我头疼 to report it.',
        fr: 'Dis 我头疼 pour le signaler.',
      },
    },
    {
      id: 'pharmacy-help-review-3',
      front: '一天两次',
      back: {
        en: 'twice a day',
        fr: 'deux fois par jour',
      },
      explanation: {
        en: '一天 = per day｜两次 = twice. This is a common instruction for medicine frequency.',
        fr: '一天 = par jour｜两次 = deux fois. C’est une fréquence de prise courante pour un médicament.',
      },
    },
    { id: 'pharmacy-help-review-4', front: '肚子疼', back: { en: 'stomach ache', fr: 'mal au ventre' }, explanation: { en: 'Another symptom you can report with 我……疼.', fr: 'Un autre symptôme que tu peux signaler avec 我……疼.' } },
    { id: 'pharmacy-help-review-5', front: '过敏', back: { en: 'allergy / allergic', fr: 'allergie / allergique' }, explanation: { en: 'A safety word the pharmacist will check.', fr: 'Un mot de sécurité que le pharmacien vérifiera.' } },
    { id: 'pharmacy-help-review-6', front: '饭后', back: { en: 'after meals', fr: 'après les repas' }, explanation: { en: 'A common medicine timing instruction.', fr: 'Une consigne courante pour le moment de prise.' } },
  ],
}
