import type { LessonContent } from '../types.js'

export const pharmacyHelpLesson: LessonContent = {
  id: 'pharmacy-help',
  title: {
    en: '买药，看医生 / Hospital and pharmacy',
    fr: '买药，看医生 / Hôpital et pharmacie',
  },
  scenario: {
    en: 'Describe your discomfort and get the right treatment or medicine.',
    fr: 'Décris ton inconfort et obtiens le bon traitement ou le bon médicament.',
  },
  dialogue: {
    title: {
      en: 'Describe symptoms and buy medicine',
      fr: 'Décrire des symptômes et acheter un médicament',
    },
    lines: [
      {
        id: 'pharmacy-help-line-01',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请问哪里有医院？',
        pinyin: 'Qǐngwèn nǎlǐ yǒu yīyuàn?',
        translation: { en: 'Where is the hospital?', fr: 'Où se trouve l\'hôpital ?' },
        explanation: { en: 'Use 哪里有 to ask where a place like a hospital or pharmacy is.', fr: 'Utilise 哪里有 pour demander où se trouve un lieu comme un hôpital ou une pharmacie.' },
        audio: '/audio/pharmacy-help/line-01.mp3',
      },
      {
        id: 'pharmacy-help-line-02',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我要挂号。',
        pinyin: 'Wǒ yào guàhào.',
        translation: { en: 'I want to register.', fr: 'Je dois m\'inscrire / enregistrer.' },
        explanation: { en: 'Say 我要挂号 to register at a hospital reception.', fr: 'Dis 我要挂号 pour t\'inscrire à l\'accueil de l\'hôpital.' },
        audio: '/audio/pharmacy-help/line-02.mp3',
      },
      {
        id: 'pharmacy-help-line-03',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我头痛。',
        pinyin: 'Wǒ tóutòng.',
        translation: { en: 'I have a headache.', fr: 'J\'ai mal à la tête.' },
        explanation: { en: 'Describe a headache with 我头痛.', fr: 'Décris un mal de tête avec 我头痛.' },
        audio: '/audio/pharmacy-help/line-03.mp3',
      },
      {
        id: 'pharmacy-help-line-04',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我发烧了。',
        pinyin: 'Wǒ fāshāo le.',
        translation: { en: 'I have a fever.', fr: 'J\'ai de la fièvre.' },
        explanation: { en: 'Use 我……了 to state a symptom like a fever, cold, or diarrhea.', fr: 'Utilise 我……了 pour indiquer un symptôme comme la fièvre, un rhume ou la diarrhée.' },
        audio: '/audio/pharmacy-help/line-04.mp3',
      },
      {
        id: 'pharmacy-help-line-05',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我感冒了。',
        pinyin: 'Wǒ gǎnmào le.',
        translation: { en: 'I have a cold.', fr: 'J\'ai attrapé un rhume.' },
        explanation: { en: 'Say 我感冒了 to tell the doctor or pharmacist you have a cold.', fr: 'Dis 我感冒了 pour dire au médecin ou au pharmacien que tu as un rhume.' },
        audio: '/audio/pharmacy-help/line-05.mp3',
      },
      {
        id: 'pharmacy-help-line-06',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我肚子疼。',
        pinyin: 'Wǒ dùzi téng.',
        translation: { en: 'I have a stomachache.', fr: 'J\'ai mal au ventre.' },
        explanation: { en: 'Put the body part before 疼 to describe where it hurts.', fr: 'Place la partie du corps avant 疼 pour décrire où tu as mal.' },
        audio: '/audio/pharmacy-help/line-06.mp3',
      },
      {
        id: 'pharmacy-help-line-07',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我拉肚子了。',
        pinyin: 'Wǒ lādùzi le.',
        translation: { en: 'I have diarrhea.', fr: 'J\'ai la diarrhée.' },
        explanation: { en: 'Report a stomach problem with 我拉肚子了.', fr: 'Signale un problème de ventre avec 我拉肚子了.' },
        audio: '/audio/pharmacy-help/line-07.mp3',
      },
      {
        id: 'pharmacy-help-line-08',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '谢谢医生。谢谢护士。',
        pinyin: 'Xièxie yīshēng. xièxie hùshì.',
        translation: { en: 'Thank you doctor. Thank you nurse.', fr: 'Merci, docteur. Merci, infirmière.' },
        explanation: { en: 'Thank the medical staff with 谢谢医生 and 谢谢护士.', fr: 'Remercie le personnel médical avec 谢谢医生 et 谢谢护士.' },
        audio: '/audio/pharmacy-help/line-08.mp3',
      },
      {
        id: 'pharmacy-help-line-09',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请问去哪里结账？',
        pinyin: 'Qǐngwèn qù nǎlǐ jiézhàng?',
        translation: { en: 'Where do I pay?', fr: 'Où dois-je payer la facture ?' },
        explanation: { en: 'Ask 请问去哪里结账 to find the payment counter.', fr: 'Demande 请问去哪里结账 pour trouver la caisse.' },
        audio: '/audio/pharmacy-help/line-09.mp3',
      },
      {
        id: 'pharmacy-help-line-10',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '去哪里取药？',
        pinyin: 'Qù nǎlǐ qǔyào?',
        translation: { en: 'Where do I pick up the medicine?', fr: 'Où retirer mon médicament ?' },
        explanation: { en: 'Ask 去哪里取药 to find where to collect your medicine.', fr: 'Demande 去哪里取药 pour savoir où récupérer ton médicament.' },
        audio: '/audio/pharmacy-help/line-10.mp3',
      },
      {
        id: 'pharmacy-help-line-11',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我想买药。',
        pinyin: 'Wǒ xiǎng mǎiyào.',
        translation: { en: 'I want to buy medicine.', fr: 'Je veux acheter des médicaments.' },
        explanation: { en: 'Use 我想买 to ask for medicine at a pharmacy.', fr: 'Utilise 我想买 pour demander un médicament à la pharmacie.' },
        audio: '/audio/pharmacy-help/line-11.mp3',
      },
      {
        id: 'pharmacy-help-line-12',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '饭前吃还是饭后吃？',
        pinyin: 'Fànqián chī háishi fànhòu chī?',
        translation: { en: 'Should I take it before or after meals?', fr: 'Dois-je le prendre avant ou après les repas ?' },
        explanation: { en: 'Ask this to confirm when to take your medicine.', fr: 'Demande ceci pour confirmer quand prendre ton médicament.' },
        audio: '/audio/pharmacy-help/line-12.mp3',
      },
      {
        id: 'pharmacy-help-line-13',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '多少钱？',
        pinyin: 'Duōshǎo qián?',
        translation: { en: 'How much is it?', fr: 'Combien ça coûte ?' },
        explanation: { en: 'Ask 多少钱 to check the price of medicine or treatment.', fr: 'Demande 多少钱 pour connaître le prix du médicament ou du traitement.' },
        audio: '/audio/pharmacy-help/line-13.mp3',
      },
    ],
  },
    sentencePatterns: [
    {
      id: 'pharmacy-help-pattern-1',
      pattern: '请问哪里有……？',
      pinyin: 'Qǐngwèn nǎlǐ yǒu ... ?',
      meaning: {
        en: 'Where is the ...?',
        fr: 'Où est ... ?',
      },
      audio: '/audio/pharmacy-help/pattern-01.mp3',
      examples: [
        {
          fill: '医院',
          fillPinyin: 'yīyuàn',
          hanzi: '请问哪里有医院？',
          pinyin: 'Qǐngwèn nǎlǐ yǒu yīyuàn?',
          en: 'hospital',
          fr: 'l\'hôpital',
        },
        {
          fill: '药店',
          fillPinyin: 'yàodiàn',
          hanzi: '请问哪里有药店？',
          pinyin: 'Qǐngwèn nǎlǐ yǒu yàodiàn?',
          en: 'pharmacy',
          fr: 'la pharmacie',
        },
        {
          fill: '卫生间',
          fillPinyin: 'wèishēngjiān',
          hanzi: '请问哪里有卫生间？',
          pinyin: 'Qǐngwèn nǎlǐ yǒu wèishēngjiān?',
          en: 'toilet',
          fr: 'les toilettes',
        },
      ],
    },
    {
      id: 'pharmacy-help-pattern-2',
      pattern: '我……疼。',
      pinyin: 'Wǒ ... téng.',
      meaning: {
        en: 'My ... hurts.',
        fr: 'J\'ai mal à ...',
      },
      audio: '/audio/pharmacy-help/pattern-02.mp3',
      examples: [
        {
          fill: '肚子',
          fillPinyin: 'dùzi',
          hanzi: '我肚子疼。',
          pinyin: 'Wǒ dùzi téng.',
          en: 'stomach',
          fr: 'au ventre',
        },
        {
          fill: '头',
          fillPinyin: 'tóu',
          hanzi: '我头疼。',
          pinyin: 'Wǒ tóu téng.',
          en: 'head',
          fr: 'à la tête',
        },
        {
          fill: '牙',
          fillPinyin: 'yá',
          hanzi: '我牙疼。',
          pinyin: 'Wǒ yá téng.',
          en: 'tooth',
          fr: 'à la dent',
        },
      ],
    },
    {
      id: 'pharmacy-help-pattern-3',
      pattern: '我……了。',
      pinyin: 'Wǒ ... le.',
      meaning: {
        en: 'I have ...',
        fr: 'J\'ai ...',
      },
      audio: '/audio/pharmacy-help/pattern-03.mp3',
      examples: [
        {
          fill: '发烧',
          fillPinyin: 'fāshāo',
          hanzi: '我发烧了。',
          pinyin: 'Wǒ fāshāo le.',
          en: 'a fever',
          fr: 'de la fièvre',
        },
        {
          fill: '感冒',
          fillPinyin: 'gǎnmào',
          hanzi: '我感冒了。',
          pinyin: 'Wǒ gǎnmào le.',
          en: 'a cold',
          fr: 'un rhume',
        },
        {
          fill: '拉肚子',
          fillPinyin: 'lādùzi',
          hanzi: '我拉肚子了。',
          pinyin: 'Wǒ lādùzi le.',
          en: 'diarrhea',
          fr: 'la diarrhée',
        },
      ],
    },
    {
      id: 'pharmacy-help-pattern-4',
      pattern: '我想买……。',
      pinyin: 'Wǒ xiǎng mǎi ... .',
      meaning: {
        en: 'I want to buy ...',
        fr: 'Je veux acheter ...',
      },
      audio: '/audio/pharmacy-help/pattern-04.mp3',
      examples: [
        {
          fill: '药',
          fillPinyin: 'yào',
          hanzi: '我想买药。',
          pinyin: 'Wǒ xiǎng mǎi yào.',
          en: 'medicine',
          fr: 'des médicaments',
        },
        {
          fill: '感冒药',
          fillPinyin: 'gǎnmào yào',
          hanzi: '我想买感冒药。',
          pinyin: 'Wǒ xiǎng mǎi gǎnmào yào.',
          en: 'cold medicine',
          fr: 'un médicament contre le rhume',
        },
        {
          fill: '创可贴',
          fillPinyin: 'chuàngkětiē',
          hanzi: '我想买创可贴。',
          pinyin: 'Wǒ xiǎng mǎi chuàngkětiē.',
          en: 'band-aid',
          fr: 'des pansements',
        },
      ],
    },
    {
      id: 'pharmacy-help-pattern-5',
      pattern: '饭前吃还是饭后吃？',
      pinyin: 'Fàn qián chī háishì fàn hòu chī?',
      meaning: {
        en: 'Should I take it before or after meals?',
        fr: 'Dois-je le prendre avant ou après les repas ?',
      },
      audio: '/audio/pharmacy-help/pattern-05.mp3',
    },
    {
      id: 'pharmacy-help-pattern-6',
      pattern: '我要挂号。',
      pinyin: 'Wǒ yào guàhào.',
      meaning: {
        en: 'I need to register.',
        fr: 'Je dois m\'inscrire / enregistrer.',
      },
      audio: '/audio/pharmacy-help/pattern-06.mp3',
    },
    {
      id: 'pharmacy-help-pattern-7',
      pattern: '我头痛。',
      pinyin: 'Wǒ tóutòng.',
      meaning: {
        en: 'I have a headache.',
        fr: 'J\'ai mal à la tête.',
      },
    },
    {
      id: 'pharmacy-help-pattern-8',
      pattern: '我感冒了。',
      pinyin: 'Wǒ gǎnmào le.',
      meaning: {
        en: 'I caught a cold.',
        fr: 'J\'ai attrapé un rhume.',
      },
    },
    {
      id: 'pharmacy-help-pattern-9',
      pattern: '我拉肚子了。',
      pinyin: 'Wǒ lādùzi le.',
      meaning: {
        en: 'I have diarrhea.',
        fr: 'J\'ai la diarrhée.',
      },
    },
    {
      id: 'pharmacy-help-pattern-10',
      pattern: '谢谢医生。谢谢护士。',
      pinyin: 'Xièxie yīshēng. Xièxie hùshi.',
      meaning: {
        en: 'Thank you, doctor. Thank you, nurse.',
        fr: 'Merci, docteur. Merci, infirmière.',
      },
    },
    {
      id: 'pharmacy-help-pattern-11',
      pattern: '请问去哪里结账？',
      pinyin: 'Qǐngwèn qù nǎlǐ jiézhàng?',
      meaning: {
        en: 'Where do I pay the bill?',
        fr: 'Où dois-je payer la facture ?',
      },
    },
    {
      id: 'pharmacy-help-pattern-12',
      pattern: '去哪里取药？',
      pinyin: 'Qù nǎlǐ qǔ yào?',
      meaning: {
        en: 'Where do I pick up my prescription?',
        fr: 'Où retirer mon médicament ?',
      },
    },
    {
      id: 'pharmacy-help-pattern-13',
      pattern: '多少钱？',
      pinyin: 'Duōshao qián?',
      meaning: {
        en: 'How much is it?',
        fr: 'Combien ça coûte ?',
      },
    },
  ],
  vocabulary: [
    {
      id: 'pharmacy-help-vocab-1',
      hanzi: '药店',
      pinyin: 'yàodiàn',
      audio: '/audio/pharmacy-help/vocab-01.mp3',
      meaning: {
        en: 'pharmacy',
        fr: 'pharmacie',
      },
      explanation: {
        en: 'The place to ask for simple medicine help.',
        fr: 'Le lieu pour demander une aide simple avec un médicament.',
      },
    },
    {
      id: 'pharmacy-help-vocab-2',
      hanzi: '药',
      pinyin: 'yào',
      audio: '/audio/pharmacy-help/vocab-02.mp3',
      meaning: {
        en: 'medicine',
        fr: 'médicament',
      },
      explanation: {
        en: 'A core word in pharmacy instructions.',
        fr: 'Un mot essentiel dans les consignes de pharmacie.',
      },
    },
    {
      id: 'pharmacy-help-vocab-3',
      hanzi: '头疼',
      pinyin: 'tóu téng',
      audio: '/audio/pharmacy-help/vocab-03.mp3',
      meaning: {
        en: 'headache',
        fr: 'mal à la tête',
      },
      explanation: {
        en: 'The mild symptom used in the dialogue.',
        fr: 'Le symptôme léger utilisé dans le dialogue.',
      },
    },
    {
      id: 'pharmacy-help-vocab-4',
      hanzi: '发烧',
      pinyin: 'fāshāo',
      audio: '/audio/pharmacy-help/vocab-04.mp3',
      meaning: {
        en: 'to have a fever',
        fr: 'avoir de la fièvre',
      },
      explanation: {
        en: 'A common follow-up symptom question.',
        fr: 'Une question de symptôme fréquente.',
      },
    },
    {
      id: 'pharmacy-help-vocab-5',
      hanzi: '过敏',
      pinyin: 'guòmǐn',
      audio: '/audio/pharmacy-help/vocab-05.mp3',
      meaning: {
        en: 'allergy / allergic',
        fr: 'allergie / allergique',
      },
      explanation: {
        en: 'A safety word to recognize even in a mild-health lesson.',
        fr: 'Un mot de sécurité à reconnaître même dans une leçon de santé légère.',
      },
    },
    { id: 'pharmacy-help-vocab-6', hanzi: '肚子疼', pinyin: 'dùzi téng', audio: '/audio/pharmacy-help/vocab-06.mp3', meaning: { en: 'stomach ache', fr: 'mal au ventre' }, explanation: { en: 'Another common symptom to report at the pharmacy.', fr: 'Un autre symptôme courant à signaler à la pharmacie.' } },
    { id: 'pharmacy-help-vocab-7', hanzi: '止疼药', pinyin: 'zhǐténg yào', audio: '/audio/pharmacy-help/vocab-07.mp3', meaning: { en: 'painkiller', fr: 'antidouleur' }, explanation: { en: 'The kind of medicine you might ask for with a headache.', fr: 'Le type de médicament que tu pourrais demander pour un mal de tête.' } },
    { id: 'pharmacy-help-vocab-8', hanzi: '一次一片', pinyin: 'yí cì yí piàn', audio: '/audio/pharmacy-help/vocab-08.mp3', meaning: { en: 'one tablet per dose', fr: 'un comprimé par prise' }, explanation: { en: 'The dosage instruction you will hear with medicine.', fr: 'La consigne de dosage que tu entendras avec le médicament.' } },
    { id: 'pharmacy-help-vocab-9', hanzi: '饭前', pinyin: 'fàn qián', audio: '/audio/pharmacy-help/vocab-09.mp3', meaning: { en: 'before meals', fr: 'avant les repas' }, explanation: { en: 'One of the two common medicine timing words.', fr: 'Un des deux mots courants pour le moment de prise du médicament.' } },
    { id: 'pharmacy-help-vocab-10', hanzi: '饭后', pinyin: 'fàn hòu', audio: '/audio/pharmacy-help/vocab-10.mp3', meaning: { en: 'after meals', fr: 'après les repas' }, explanation: { en: 'The other common medicine timing word paired with 饭前.', fr: 'L’autre mot courant pour le moment de prise, associé à 饭前.' } },
    { id: 'pharmacy-help-vocab-11', hanzi: '医院', pinyin: 'yīyuàn', audio: '/audio/pharmacy-help/vocab-11.mp3', meaning: { en: 'hospital', fr: 'hôpital' }, explanation: { en: 'The place where you see a doctor or go to a pharmacy.', fr: 'Le lieu où tu vois un médecin ou tu vas à la pharmacie.' } },
  ],
  practice: {
    listening: [
      {
        id: 'pharmacy-help-listening-1',
        prompt: {
          en: 'Listen for headache and no fever.',
          fr: 'Écoute “mal à la tête” et “pas de fièvre”.',
        },
        target: '我头疼，不发烧。',
        audio: '/audio/pharmacy-help/practice-listening-01.mp3',
        explanation: {
          en: 'This combines the symptom and the negative fever answer.',
          fr: 'Cela combine le symptôme et la réponse négative sur la fièvre.',
        },
      },
      { id: 'pharmacy-help-listening-2', prompt: { en: 'Which phrase asks about allergies?', fr: 'Quelle phrase demande à propos des allergies ?' }, target: '你对什么过敏吗？', audio: '/audio/pharmacy-help/practice-listening-02.mp3', explanation: { en: 'This is a safety question you will hear at the pharmacy.', fr: 'C’est une question de sécurité que tu entendras à la pharmacie.' } },
    ],
    speaking: [
      {
        id: 'pharmacy-help-speaking-1',
        prompt: {
          en: 'Say that your head hurts.',
          fr: 'Dis que tu as mal à la tête.',
        },
        target: '我头疼。',
        audio: '/audio/pharmacy-help/practice-speaking-01.mp3',
        explanation: {
          en: 'Start with the shortest clear symptom sentence.',
          fr: 'Commence par la phrase de symptôme la plus courte et claire.',
        },
      },
      { id: 'pharmacy-help-speaking-2', prompt: { en: 'Ask whether to take the medicine before or after meals.', fr: 'Demande si le médicament se prend avant ou après les repas.' }, target: '饭前还是饭后？', audio: '/audio/pharmacy-help/practice-speaking-02.mp3', explanation: { en: 'This confirms the correct timing for the medicine.', fr: 'Cela confirme le bon moment pour prendre le médicament.' } },
    ],
    reading: [
      {
        id: 'pharmacy-help-reading-1',
        prompt: {
          en: 'Read the medicine frequency phrase.',
          fr: 'Lis la phrase de fréquence du médicament.',
        },
        target: '一天两次。',
        audio: '/audio/pharmacy-help/practice-reading-01.mp3',
        explanation: {
          en: 'Recognize how many times per day the medicine is used.',
          fr: 'Reconnais combien de fois par jour le médicament est utilisé.',
        },
      },
      { id: 'pharmacy-help-reading-2', prompt: { en: 'Match the dosage instruction.', fr: 'Associe la consigne de dosage.' }, target: '一次一片', audio: '/audio/pharmacy-help/practice-reading-02.mp3', explanation: { en: '一次一片 is the pill count per dose.', fr: '一次一片 est le nombre de comprimés par prise.' } },
    ],
  },
  reviewCards: [
    {
      id: 'pharmacy-help-review-1',
      front: '药店',
      back: {
        en: 'pharmacy',
        fr: 'pharmacie',
      },
      explanation: {
        en: 'The place for the help request.',
        fr: 'Le lieu de la demande d’aide.',
      },
    },
    {
      id: 'pharmacy-help-review-2',
      front: '头疼',
      back: {
        en: 'headache',
        fr: 'mal à la tête',
      },
      explanation: {
        en: 'Say 我头疼 to report it.',
        fr: 'Dis 我头疼 pour le signaler.',
      },
    },
    {
      id: 'pharmacy-help-review-3',
      front: '一天两次',
      back: {
        en: 'twice a day',
        fr: 'deux fois par jour',
      },
      explanation: {
        en: 'A common medicine frequency.',
        fr: 'Une fréquence courante pour un médicament.',
      },
    },
    { id: 'pharmacy-help-review-4', front: '肚子疼', back: { en: 'stomach ache', fr: 'mal au ventre' }, explanation: { en: 'Another symptom you can report with 我……疼.', fr: 'Un autre symptôme que tu peux signaler avec 我……疼.' } },
    { id: 'pharmacy-help-review-5', front: '过敏', back: { en: 'allergy / allergic', fr: 'allergie / allergique' }, explanation: { en: 'A safety word the pharmacist will check.', fr: 'Un mot de sécurité que le pharmacien vérifiera.' } },
    { id: 'pharmacy-help-review-6', front: '饭后', back: { en: 'after meals', fr: 'après les repas' }, explanation: { en: 'A common medicine timing instruction.', fr: 'Une consigne courante pour le moment de prise.' } },
  ],
}
