import type { LessonContent } from '../types.js'

export const phoneAndPaymentLesson: LessonContent = {
  id: 'phone-and-payment',
  title: {
    en: '中国电话卡 / SIM card setup',
    fr: '中国电话卡 / Configuration de la carte SIM',
  },
  scenario: {
    en: 'Ask for a SIM card, set it up, buy data plan and top up.',
    fr: 'Demander une carte SIM, la configurer, acheter un forfait data et recharger.',
  },
  dialogue: {
    title: {
      en: 'Ask about phone and payment setup',
      fr: 'Demander de l\'aide pour le téléphone et le paiement',
    },
    lines: [
      {
        id: 'phone-and-payment-line-01',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我要买一个 SIM 卡。',
        pinyin: 'Wǒ yào mǎi yí gè SIM kǎ.',
        translation: { en: 'I want to buy a SIM card.', fr: 'Je veux acheter une carte SIM.' },
        explanation: { en: 'Start the SIM card request with 我要买一个 SIM 卡.', fr: 'Commence la demande de carte SIM avec 我要买一个 SIM 卡.' },
        audio: '/audio/phone-and-payment/line-01.mp3',
      },
      {
        id: 'phone-and-payment-line-02',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '能帮我安装一下吗？',
        pinyin: 'Néng bāng wǒ ān zhuāng yí xià ma?',
        translation: { en: 'Please help me install it.', fr: 'Pouvez-vous m\'aider à l\'installer ?' },
        explanation: { en: 'Use 能帮我…吗 to ask for help installing or setting something up.', fr: 'Utilise 能帮我…吗 pour demander de l\'aide pour installer ou configurer quelque chose.' },
        audio: '/audio/phone-and-payment/line-02.mp3',
      },
      {
        id: 'phone-and-payment-line-03',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我需要流量。',
        pinyin: 'Wǒ xū yào liú liàng.',
        translation: { en: 'I need mobile data.', fr: 'J\'ai besoin de forfait data.' },
        explanation: { en: 'Say 我需要流量 to ask for mobile data.', fr: 'Dis 我需要流量 pour demander de la data mobile.' },
        audio: '/audio/phone-and-payment/line-03.mp3',
      },
      {
        id: 'phone-and-payment-line-04',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '这个套餐有多少流量？',
        pinyin: 'Zhè ge tào cān yǒu duō shǎo liú liàng?',
        translation: { en: 'How much data does this plan have?', fr: 'Combien de data ce forfait inclut-il ?' },
        explanation: { en: 'Ask about the data allowance of a plan with 有多少流量.', fr: 'Demande le volume de data d\'un forfait avec 有多少流量.' },
        audio: '/audio/phone-and-payment/line-04.mp3',
      },
      {
        id: 'phone-and-payment-line-05',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '多少钱？',
        pinyin: 'Duō shǎo qián?',
        translation: { en: 'How much is it?', fr: 'Combien ça coûte ?' },
        explanation: { en: 'Ask 多少钱 to get the price of a SIM card or data plan.', fr: 'Demande 多少钱 pour connaître le prix d\'une carte SIM ou d\'un forfait.' },
        audio: '/audio/phone-and-payment/line-05.mp3',
      },
      {
        id: 'phone-and-payment-line-06',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '怎么充值？',
        pinyin: 'Zěn me chōng zhí?',
        translation: { en: 'How do I top up?', fr: 'Comment faire une recharge ?' },
        explanation: { en: 'Use 怎么 before a verb to ask how to do something, like 充值.', fr: 'Utilise 怎么 avant un verbe pour demander comment faire quelque chose, comme 充值.' },
        audio: '/audio/phone-and-payment/line-06.mp3',
      },
      {
        id: 'phone-and-payment-line-07',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '帮我设置一下网络好吗？',
        pinyin: 'Bāng wǒ shè zhì yí xià wǎng luò hǎo ma?',
        translation: { en: 'Could you help me set up the Internet?', fr: 'Pouvez-vous m\'aider à configurer Internet ?' },
        explanation: { en: 'Use 帮我设置一下 to ask for help setting up a network or phone.', fr: 'Utilise 帮我设置一下 pour demander de l\'aide pour configurer un réseau ou un téléphone.' },
        audio: '/audio/phone-and-payment/line-07.mp3',
      },
      {
        id: 'phone-and-payment-line-08',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '没有网络。',
        pinyin: 'Méi yǒu wǎng luò.',
        translation: { en: 'There is no internet.', fr: 'Il n\'y a pas de connexion Internet.' },
        explanation: { en: 'Say 没有网络 to explain you have no internet connection.', fr: 'Dis 没有网络 pour expliquer que tu n\'as pas de connexion Internet.' },
        audio: '/audio/phone-and-payment/line-08.mp3',
      },
      {
        id: 'phone-and-payment-line-09',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '没有信号。',
        pinyin: 'Méi yǒu xìn hào.',
        translation: { en: 'There is no signal.', fr: 'Il n\'y a pas de signal.' },
        explanation: { en: 'Say 没有信号 when your phone shows no network signal.', fr: 'Dis 没有信号 quand ton téléphone n\'affiche aucun signal.' },
        audio: '/audio/phone-and-payment/line-09.mp3',
      },
    ],
  },
    sentencePatterns: [
    {
      id: 'phone-and-payment-pattern-1',
      pattern: '我要买一个……。',
      pinyin: 'Wǒ yào mǎi yí gè ... .',
      meaning: {
        en: 'I want to buy a ...',
        fr: 'Je veux acheter un / une ...',
      },
      audio: '/audio/phone-and-payment/pattern-01.mp3',
      examples: [
        {
          fill: 'SIM',
          fillPinyin: '卡 SIM kǎ',
          hanzi: '我要买一个 SIM 卡。',
          pinyin: 'Wǒ yào mǎi yí gè SIM kǎ.',
          en: 'SIM card',
          fr: 'carte SIM',
        },
        {
          fill: '手机卡',
          fillPinyin: 'shǒujīkǎ',
          hanzi: '我要买一个手机卡。',
          pinyin: 'Wǒ yào mǎi yí gè shǒu jī kǎ.',
          en: 'phone card',
          fr: 'carte téléphonique',
        },
        {
          fill: '套餐',
          fillPinyin: 'tàocān',
          hanzi: '我要买一个套餐。',
          pinyin: 'Wǒ yào mǎi yí gè tào cān.',
          en: 'plan',
          fr: 'forfait',
        },
      ],
    },
    {
      id: 'phone-and-payment-pattern-2',
      pattern: '能帮我……吗？',
      pinyin: 'Néng bāng wǒ ... ma?',
      meaning: {
        en: 'Could you help me ...?',
        fr: 'Pouvez-vous m\'aider à ... ?',
      },
      audio: '/audio/phone-and-payment/pattern-02.mp3',
      examples: [
        {
          fill: '安装一下',
          fillPinyin: 'ānzhuāng yíxià',
          hanzi: '能帮我安装一下吗？',
          pinyin: 'Néng bāng wǒ ān zhuāng yí xià ma?',
          en: 'install it',
          fr: 'installer',
        },
        {
          fill: '设置一下',
          fillPinyin: 'shèzhì yíxià',
          hanzi: '能帮我设置一下吗？',
          pinyin: 'Néng bāng wǒ shè zhì yí xià ma?',
          en: 'set it up',
          fr: 'configurer',
        },
        {
          fill: '激活一下',
          fillPinyin: 'jīhuó yíxià',
          hanzi: '能帮我激活一下吗？',
          pinyin: 'Néng bāng wǒ jī huó yí xià ma?',
          en: 'activate it',
          fr: 'activer',
        },
      ],
    },
    {
      id: 'phone-and-payment-pattern-3',
      pattern: '我需要……。',
      pinyin: 'Wǒ xū yào ... .',
      meaning: {
        en: 'I need ...',
        fr: 'J\'ai besoin de ...',
      },
      audio: '/audio/phone-and-payment/pattern-03.mp3',
      examples: [
        {
          fill: '流量',
          fillPinyin: 'liúliàng',
          hanzi: '我需要流量。',
          pinyin: 'Wǒ xū yào liú liàng.',
          en: 'mobile data',
          fr: 'des données mobiles',
        },
        {
          fill: '一个手机号码',
          fillPinyin: 'yí gè shǒujī hàomǎ',
          hanzi: '我需要一个手机号码。',
          pinyin: 'Wǒ xū yào yí gè shǒu jī hào mǎ.',
          en: 'a phone number',
          fr: 'un numéro de téléphone',
        },
        {
          fill: '更多流量',
          fillPinyin: 'gèng duō liúliàng',
          hanzi: '我需要更多流量。',
          pinyin: 'Wǒ xū yào gèng duō liú liàng.',
          en: 'more data',
          fr: 'plus de données',
        },
      ],
    },
    {
      id: 'phone-and-payment-pattern-4',
      pattern: '……有多少流量？',
      pinyin: '... yǒu duō shao liú liàng?',
      meaning: {
        en: 'How much data does ... have?',
        fr: 'Combien de data a ... ?',
      },
      audio: '/audio/phone-and-payment/pattern-04.mp3',
      examples: [
        {
          fill: '这个套餐',
          fillPinyin: 'zhège tàocān',
          hanzi: '这个套餐有多少流量？',
          pinyin: 'Zhè ge tào cān yǒu duō shao liú liàng?',
          en: 'this plan',
          fr: 'ce forfait',
        },
        {
          fill: '这个手机卡',
          fillPinyin: 'zhège shǒujīkǎ',
          hanzi: '这个手机卡有多少流量？',
          pinyin: 'Zhè ge shǒu jī kǎ yǒu duō shao liú liàng?',
          en: 'this phone card',
          fr: 'cette carte téléphonique',
        },
        {
          fill: '每月套餐',
          fillPinyin: 'měi yuè tàocān',
          hanzi: '每月套餐有多少流量？',
          pinyin: 'Měi yuè tào cān yǒu duō shao liú liàng?',
          en: 'monthly plan',
          fr: 'forfait mensuel',
        },
      ],
    },
    {
      id: 'phone-and-payment-pattern-5',
      pattern: '怎么……？',
      pinyin: 'Zěn me ... ?',
      meaning: {
        en: 'How do I ...?',
        fr: 'Comment ... ?',
      },
      audio: '/audio/phone-and-payment/pattern-05.mp3',
      examples: [
        {
          fill: '充值',
          fillPinyin: 'chōngzhí',
          hanzi: '怎么充值？',
          pinyin: 'Zěn me chōng zhí?',
          en: 'top up',
          fr: 'recharger',
        },
        {
          fill: '缴费',
          fillPinyin: 'jiǎofèi',
          hanzi: '怎么缴费？',
          pinyin: 'Zěn me jiǎo fèi?',
          en: 'pay the bill',
          fr: 'payer la facture',
        },
        {
          fill: '使用',
          fillPinyin: 'shǐyòng',
          hanzi: '怎么使用？',
          pinyin: 'Zěn me shǐ yòng?',
          en: 'use',
          fr: 'utiliser',
        },
      ],
    },
    {
      id: 'phone-and-payment-pattern-6',
      pattern: '多少钱？',
      pinyin: 'Duō shao qián?',
      meaning: {
        en: 'How much is it?',
        fr: 'Combien ça coûte ?',
      },
    },
    {
      id: 'phone-and-payment-pattern-7',
      pattern: '帮我设置一下网络好吗？',
      pinyin: 'Bāng wǒ shè zhì yí xià wǎng luò hǎo ma?',
      meaning: {
        en: 'Could you help me set up the Internet?',
        fr: 'Pouvez-vous m\'aider à configurer Internet ?',
      },
    },
    {
      id: 'phone-and-payment-pattern-8',
      pattern: '没有网络。',
      pinyin: 'Méi yǒu wǎng luò.',
      meaning: {
        en: 'There is no internet.',
        fr: 'Il n\'y a pas de connexion Internet.',
      },
    },
    {
      id: 'phone-and-payment-pattern-9',
      pattern: '没有信号。',
      pinyin: 'Méi yǒu xìn hào.',
      meaning: {
        en: 'There is no signal.',
        fr: 'Il n\'y a pas de signal.',
      },
    },
  ],
  vocabulary: [
    {
      id: 'phone-and-payment-vocab-1',
      hanzi: '手机卡',
      pinyin: 'shǒu jī kǎ',
      audio: '/audio/phone-and-payment/vocab-01.mp3',
      meaning: {
        en: 'SIM card / phone card',
        fr: 'carte SIM / carte de téléphone',
      },
      explanation: {
        en: 'The practical word for asking about phone service after arrival.',
        fr: 'Le mot pratique pour demander un service téléphonique après l\'arrivée.',
      },
    },
    {
      id: 'phone-and-payment-vocab-2',
      hanzi: '手机号码',
      pinyin: 'shǒu jī hào mǎ',
      audio: '/audio/phone-and-payment/vocab-02.mp3',
      meaning: {
        en: 'phone number',
        fr: 'numéro de téléphone',
      },
      explanation: {
        en: 'Recognize it when someone confirms the number attached to the phone.',
        fr: 'Reconnais-le quand quelqu\'un confirme le numéro lié au téléphone.',
      },
    },
    {
      id: 'phone-and-payment-vocab-3',
      hanzi: '支付',
      pinyin: 'zhī fù',
      audio: '/audio/phone-and-payment/vocab-03.mp3',
      meaning: {
        en: 'pay / payment',
        fr: 'payer / paiement',
      },
      explanation: {
        en: 'A core word for mobile payment questions.',
        fr: 'Un mot central pour les questions de paiement mobile.',
      },
    },
    {
      id: 'phone-and-payment-vocab-4',
      hanzi: '现金',
      pinyin: 'xiàn jīn',
      audio: '/audio/phone-and-payment/vocab-04.mp3',
      meaning: {
        en: 'cash',
        fr: 'espèces',
      },
      explanation: {
        en: 'A useful fallback if phone payment is not ready.',
        fr: 'Une solution utile si le paiement mobile n\'est pas prêt.',
      },
    },
    {
      id: 'phone-and-payment-vocab-5',
      hanzi: '可以',
      pinyin: 'kě yǐ',
      audio: '/audio/phone-and-payment/vocab-05.mp3',
      meaning: {
        en: 'can / may',
        fr: 'pouvoir / être possible',
      },
      explanation: {
        en: 'Use it to ask if an action or payment method is possible.',
        fr: 'Utilise-le pour demander si une action ou un moyen de paiement est possible.',
      },
    },
    { id: 'phone-and-payment-vocab-6', hanzi: '流量', pinyin: 'liú liàng', audio: '/audio/phone-and-payment/vocab-06.mp3', meaning: { en: 'data / mobile data', fr: 'données mobiles' }, explanation: { en: 'The key word when choosing a phone plan.', fr: 'Le mot clé pour choisir un forfait téléphonique.' } },
    { id: 'phone-and-payment-vocab-7', hanzi: '套餐', pinyin: 'tào cān', audio: '/audio/phone-and-payment/vocab-07.mp3', meaning: { en: 'plan / package', fr: 'forfait' }, explanation: { en: '套餐 means a bundled plan for phone, data, or even meals.', fr: '套餐 désigne un forfait groupé pour le téléphone, les données ou même les repas.' } },
    { id: 'phone-and-payment-vocab-8', hanzi: '充值', pinyin: 'chōng zhí', audio: '/audio/phone-and-payment/vocab-08.mp3', meaning: { en: 'top up / recharge', fr: 'recharger' }, explanation: { en: 'Use 充值 when you need to add credit to your phone or transit card.', fr: 'Utilise 充值 quand tu dois ajouter du crédit à ton téléphone ou ta carte de transport.' } },
    { id: 'phone-and-payment-vocab-9', hanzi: '微信', pinyin: 'Wēi xìn', audio: '/audio/phone-and-payment/vocab-09.mp3', meaning: { en: 'WeChat', fr: 'WeChat' }, explanation: { en: 'The most common messaging and payment app in China.', fr: 'L\'application de messagerie et de paiement la plus courante en Chine.' } },
    { id: 'phone-and-payment-vocab-10', hanzi: '余额', pinyin: 'yú é', audio: '/audio/phone-and-payment/vocab-10.mp3', meaning: { en: 'balance', fr: 'solde' }, explanation: { en: 'Check your 余额 to know how much credit you have left.', fr: 'Vérifie ton 余额 pour savoir combien de crédit il te reste.' } },
  ],
  practice: {
    listening: [
      {
        id: 'phone-and-payment-listening-1',
        prompt: {
          en: 'Listen for the word that means SIM card.',
          fr: 'Écoute le mot qui signifie carte SIM.',
        },
        target: '手机卡',
        audio: '/audio/phone-and-payment/practice-listening-01.mp3',
        explanation: {
          en: '手机卡 is the phone card or SIM card in this service exchange.',
          fr: '手机卡 désigne la carte SIM dans cet échange de service.',
        },
      },
      { id: 'phone-and-payment-listening-2', prompt: { en: 'Which phrase asks about data plans?', fr: 'Quelle phrase demande les forfaits data ?' }, target: '有什么流量套餐？', audio: '/audio/phone-and-payment/practice-listening-02.mp3', explanation: { en: '有什么流量套餐 helps you compare phone plan options.', fr: '有什么流量套餐 t\'aide à comparer les forfaits téléphoniques.' } },
    ],
    speaking: [
      {
        id: 'phone-and-payment-speaking-1',
        prompt: {
          en: 'Ask whether phone payment is possible.',
          fr: 'Demande si le paiement par téléphone est possible.',
        },
        target: '可以用手机支付吗？',
        audio: '/audio/phone-and-payment/practice-speaking-01.mp3',
        explanation: {
          en: 'This question is the safest short way to check mobile payment.',
          fr: 'Cette question est la manière courte la plus sûre de vérifier le paiement mobile.',
        },
      },
      { id: 'phone-and-payment-speaking-2', prompt: { en: 'Ask how to top up your phone.', fr: 'Demande comment recharger ton téléphone.' }, target: '怎么充值？', audio: '/audio/phone-and-payment/practice-speaking-02.mp3', explanation: { en: '怎么充值 is the fastest way to ask about adding credit.', fr: '怎么充值 est la façon la plus rapide de demander comment ajouter du crédit.' } },
    ],
    reading: [
      {
        id: 'phone-and-payment-reading-1',
        prompt: {
          en: 'Match 手机号码 with its meaning.',
          fr: 'Associe 手机号码 à son sens.',
        },
        target: '手机号码',
        audio: '/audio/phone-and-payment/practice-reading-01.mp3',
        explanation: {
          en: '手机号码 means phone number.',
          fr: '手机号码 signifie numéro de téléphone.',
        },
      },
      { id: 'phone-and-payment-reading-2', prompt: { en: 'Match the payment app name.', fr: 'Associe le nom de l\'appli de paiement.' }, target: '微信', audio: '/audio/phone-and-payment/practice-reading-02.mp3', explanation: { en: '微信 is the most important app name to recognize in China.', fr: '微信 est le nom d\'application le plus important à reconnaître en Chine.' } },
    ],
  },
  reviewCards: [
    {
      id: 'phone-and-payment-review-1',
      front: '手机卡',
      back: {
        en: 'SIM card / phone card',
        fr: 'carte SIM / carte de téléphone',
      },
      explanation: {
        en: 'Use this when asking for basic phone service.',
        fr: 'Utilise ce mot pour demander un service téléphonique de base.',
      },
    },
    {
      id: 'phone-and-payment-review-2',
      front: '手机号码',
      back: {
        en: 'phone number',
        fr: 'numéro de téléphone',
      },
      explanation: {
        en: 'This is the number attached to the phone or SIM card.',
        fr: 'C\'est le numéro lié au téléphone ou à la carte SIM.',
      },
    },
    {
      id: 'phone-and-payment-review-3',
      front: '可以用手机支付吗？',
      back: {
        en: 'Can I pay by phone?',
        fr: 'Puis-je payer avec mon téléphone ?',
      },
      explanation: {
        en: 'A short practical question for shops and counters.',
        fr: 'Une question courte et pratique dans les magasins et aux comptoirs.',
      },
    },
    { id: 'phone-and-payment-review-4', front: '流量', back: { en: 'mobile data', fr: 'données mobiles' }, explanation: { en: 'The word for mobile data.', fr: 'Le mot pour les données mobiles.' } },
    { id: 'phone-and-payment-review-5', front: '充值', back: { en: 'top up / recharge', fr: 'recharger' }, explanation: { en: 'How to add credit to your phone.', fr: 'Comment ajouter du crédit à ton téléphone.' } },
    { id: 'phone-and-payment-review-6', front: '微信', back: { en: 'WeChat', fr: 'WeChat' }, explanation: { en: 'The essential messaging and payment app.', fr: 'L\'application essentielle de messagerie et de paiement.' } },
  ],
}
