import type { LessonContent } from '../types.js'

export const phoneAndPaymentLesson: LessonContent = {
  id: 'phone-and-payment',
  title: {
    en: '中国电话卡 / SIM card setup',
    fr: '中国电话卡 / Configuration de la carte SIM',
  },
  scenario: {
    en: 'Ask for a SIM card, set it up, buy data plan and top up.',
    fr: 'Demander une carte SIM, la configurer, acheter un forfait data et recharger.',
  },
  dialogue: {
    title: {
      en: 'Ask about phone and payment setup',
      fr: 'Demander de l\'aide pour le téléphone et le paiement',
    },
    intro: {
      en: "In China, all SIM cards require real-name registration with your passport. Only official service centers work; small shops can’t help. There are four major telecom operators: China Mobile, China Unicom, China Telecom and China Broadnet. Each operator offers various mobile SIM card options. To monitor your communication expenses, download the operator's app or follow their official WeChat account to check call charges and data usage. Pay attention to billing rules inside and outside your plan, as data charges beyond your plan can be high. Cancel your SIM card at the official store before you leave China. Unpaid debt may prevent you from buying a Chinese SIM card later.",
      fr: 'En Chine, toutes les cartes SIM doivent être enregistrées nominativement avec votre passeport. Seuls les centres de service officiels peuvent vous aider ; les petites boutiques ne le peuvent pas. Il existe quatre grands opérateurs de télécommunications : China Mobile, China Unicom, China Telecom et China Broadnet. Chaque opérateur propose différentes options de cartes SIM mobiles. Pour suivre vos frais de communication, téléchargez l’application de l’opérateur ou suivez son compte WeChat officiel afin de vérifier le coût des appels et l’utilisation des données. Faites attention aux règles de facturation dans et hors de votre forfait, car les données consommées au-delà du forfait peuvent coûter cher. Résiliez votre carte SIM dans la boutique officielle avant de quitter la Chine. Des impayés peuvent vous empêcher d’acheter une carte SIM chinoise plus tard.',
    },
    lines: [
      {
        id: 'phone-and-payment-line-01',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我要买一个 SIM 卡。',
        pinyin: 'wǒ yào mǎi yí gè SIM kǎ.',
        translation: { en: 'I want to buy a SIM card.', fr: 'Je veux acheter une carte SIM.' },
        explanation: { en: '我 = I｜要 = want to｜买 = to buy｜一个 = one (measure word)｜SIM 卡 = SIM card. Use it to tell the shop you want to buy a SIM card.', fr: '我 = je｜要 = vouloir｜买 = acheter｜一个 = un / une (classificateur)｜SIM 卡 = carte SIM. Utilisez-la pour dire au magasin que vous voulez acheter une carte SIM.' },
        audio: '/audio/phone-and-payment/line-01.mp3',
      },
      {
        id: 'phone-and-payment-line-10',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '外国人可以办理吗？',
        pinyin: 'wài guó rén kě yǐ bàn lǐ ma?',
        translation: { en: 'Do you offer services for foreigners?', fr: 'Proposez-vous des services aux étrangers ?' },
        explanation: { en: '外国人 = foreigner｜可以 = can / may｜办理 = to handle / provide a service｜吗 = question particle. Use it to ask whether foreigners can apply for the service.', fr: '外国人 = étranger｜可以 = pouvoir｜办理 = effectuer / fournir un service｜吗 = particule interrogative. Utilisez-la pour demander si les étrangers peuvent bénéficier de ce service.' },
        audio: '/audio/phone-and-payment/line-10.mp3',
      },
      {
        id: 'phone-and-payment-line-02',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '能帮我安装一下吗？',
        pinyin: 'néng bāng wǒ ān zhuāng yí xià ma?',
        translation: { en: 'Could you help me install it?', fr: 'Pouvez-vous m\'aider à l\'installer ?' },
        explanation: { en: '能 = can / to be able to｜帮 = to help｜我 = me｜安装 = to install｜一下 = a bit / a moment｜吗 = question particle. Use it to ask for help installing something.', fr: '能 = pouvoir｜帮 = aider｜我 = moi｜安装 = installer｜一下 = un peu / un instant｜吗 = particule interrogative. Utilisez-la pour demander de l’aide pour installer quelque chose.' },
        audio: '/audio/phone-and-payment/line-02.mp3',
      },
      {
        id: 'phone-and-payment-line-03',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我需要流量。',
        pinyin: 'wǒ xū yào liú liàng.',
        translation: { en: 'I need mobile data.', fr: 'J’ai besoin de données mobiles.' },
        explanation: { en: '我 = I｜需要 = to need｜流量 = data / mobile data. Use it to tell the shop you need mobile data.', fr: '我 = je｜需要 = avoir besoin de｜流量 = données mobiles. Utilisez-la pour dire au magasin que vous avez besoin de données mobiles.' },
        audio: '/audio/phone-and-payment/line-03.mp3',
      },
      {
        id: 'phone-and-payment-line-04',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '这个套餐有多少流量？',
        pinyin: 'zhè ge tào cān yǒu duō shǎo liú liàng?',
        translation: { en: 'How much data does this plan have?', fr: 'Combien de data ce forfait inclut-il ?' },
        explanation: { en: '这个 = this｜套餐 = plan / package｜有 = to have｜多少 = how much｜流量 = data. Use it to ask how much data a plan includes.', fr: '这个 = ce / cet｜套餐 = forfait｜有 = avoir｜多少 = combien｜流量 = données. Utilisez-la pour demander combien de données un forfait inclut.' },
        audio: '/audio/phone-and-payment/line-04.mp3',
      },
      {
        id: 'phone-and-payment-line-05',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '多少钱？',
        pinyin: 'duō shǎo qián?',
        translation: { en: 'How much is it?', fr: 'Combien ça coûte ?' },
        explanation: { en: '多少 = how much｜钱 = money. Use it to ask the price of a SIM card or plan.', fr: '多少 = combien｜钱 = argent. Utilisez-la pour demander le prix d’une carte SIM ou d’un forfait.' },
        audio: '/audio/phone-and-payment/line-05.mp3',
      },
      {
        id: 'phone-and-payment-line-06',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '怎么充值？',
        pinyin: 'zěn me chōng zhí?',
        translation: { en: 'How do I top up?', fr: 'Comment faire une recharge ?' },
        explanation: { en: '怎么 = how｜充值 = to top up / recharge. Use it to ask how to top up your phone.', fr: '怎么 = comment｜充值 = recharger. Utilisez-la pour demander comment recharger votre téléphone.' },
        audio: '/audio/phone-and-payment/line-06.mp3',
      },
      {
        id: 'phone-and-payment-line-07',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '帮我设置一下网络好吗？',
        pinyin: 'bāng wǒ shè zhì yí xià wǎng luò hǎo ma?',
        translation: { en: 'Could you help me set up the Internet?', fr: 'Pouvez-vous m\'aider à configurer Internet ?' },
        explanation: { en: '帮 = to help｜我 = me｜设置 = to set up｜一下 = a bit / a moment｜网络 = network / internet｜好吗 = okay? / is that all right? Use it to politely ask for help setting up the internet.', fr: '帮 = aider｜我 = moi｜设置 = configurer｜一下 = un peu / un instant｜网络 = réseau / Internet｜好吗 = d’accord ? Utilisez-la pour demander poliment de l’aide pour configurer Internet.' },
        audio: '/audio/phone-and-payment/line-07.mp3',
      },
      {
        id: 'phone-and-payment-line-08',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '没有网络。',
        pinyin: 'méi yǒu wǎng luò.',
        translation: { en: 'There is no internet.', fr: 'Il n\'y a pas de connexion Internet.' },
        explanation: { en: '没有 = to not have / there is no｜网络 = network / internet. Use it to say there is no internet connection.', fr: '没有 = il n’y a pas / ne pas avoir｜网络 = réseau / Internet. Utilisez-la pour dire qu’il n’y a pas de connexion Internet.' },
        audio: '/audio/phone-and-payment/line-08.mp3',
      },
      {
        id: 'phone-and-payment-line-09',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '没有信号。',
        pinyin: 'méi yǒu xìn hào.',
        translation: { en: 'There is no signal.', fr: 'Il n\'y a pas de signal.' },
        explanation: { en: '没有 = to not have / there is no｜信号 = signal. Use it to say your phone shows no signal.', fr: '没有 = il n’y a pas / ne pas avoir｜信号 = signal. Utilisez-la pour dire que votre téléphone n’a pas de signal.' },
        audio: '/audio/phone-and-payment/line-09.mp3',
      },
    ],
  },
    sentencePatterns: [
    {
      id: 'phone-and-payment-pattern-1',
      pattern: '我要买一个……。',
      pinyin: 'wǒ yào mǎi yí gè ... .',
      meaning: {
        en: 'I want to buy a ...',
        fr: 'Je veux acheter un / une ...',
      },
      audio: '/audio/phone-and-payment/pattern-01.mp3',
      examples: [
        {
          fill: 'SIM 卡',
          fillPinyin: 'SIM kǎ',
          hanzi: '我要买一个 SIM 卡。',
          pinyin: 'wǒ yào mǎi yí gè SIM kǎ.',
          en: 'I want to buy a SIM card.',
          fr: 'Je veux acheter une carte SIM.',
          audio: '/audio/phone-and-payment/pattern-01-example-01.mp3',
        },
        {
          fill: '手机卡',
          fillPinyin: 'shǒu jī kǎ',
          hanzi: '我要买一个手机卡。',
          pinyin: 'wǒ yào mǎi yí gè shǒu jī kǎ.',
          en: 'I want to buy a SIM card.',
          fr: 'Je veux acheter une carte SIM.',
          audio: '/audio/phone-and-payment/pattern-01-example-02.mp3',
        },
        {
          fill: '套餐',
          fillPinyin: 'tào cān',
          hanzi: '我要买一个套餐。',
          pinyin: 'wǒ yào mǎi yí gè tào cān.',
          en: 'I want to buy a plan.',
          fr: 'Je veux acheter un forfait.',
          audio: '/audio/phone-and-payment/pattern-01-example-03.mp3',
        },
      ],
    },
    {
      id: 'phone-and-payment-pattern-2',
      pattern: '能帮我……吗？',
      pinyin: 'néng bāng wǒ ... ma?',
      meaning: {
        en: 'Could you help me ...?',
        fr: 'Pouvez-vous m\'aider à ... ?',
      },
      audio: '/audio/phone-and-payment/pattern-02.mp3',
      examples: [
        {
          fill: '安装一下',
          fillPinyin: 'ān zhuāng yí xià',
          hanzi: '能帮我安装一下吗？',
          pinyin: 'néng bāng wǒ ān zhuāng yí xià ma?',
          en: 'Could you help me install it?',
          fr: 'Pouvez-vous m’aider à l’installer ?',
          audio: '/audio/phone-and-payment/pattern-02-example-01.mp3',
        },
        {
          fill: '设置一下',
          fillPinyin: 'shè zhì yí xià',
          hanzi: '能帮我设置一下吗？',
          pinyin: 'néng bāng wǒ shè zhì yí xià ma?',
          en: 'Could you help me set it up?',
          fr: 'Pouvez-vous m’aider à le configurer ?',
          audio: '/audio/phone-and-payment/pattern-02-example-02.mp3',
        },
        {
          fill: '激活一下',
          fillPinyin: 'jī huó yí xià',
          hanzi: '能帮我激活一下吗？',
          pinyin: 'néng bāng wǒ jī huó yí xià ma?',
          en: 'Could you help me activate it?',
          fr: 'Pouvez-vous m’aider à l’activer ?',
          audio: '/audio/phone-and-payment/pattern-02-example-03.mp3',
        },
      ],
    },
    {
      id: 'phone-and-payment-pattern-3',
      pattern: '我需要……。',
      pinyin: 'wǒ xū yào ... .',
      meaning: {
        en: 'I need ...',
        fr: 'J\'ai besoin de ...',
      },
      audio: '/audio/phone-and-payment/pattern-03.mp3',
      examples: [
        {
          fill: '流量',
          fillPinyin: 'liú liàng',
          hanzi: '我需要流量。',
          pinyin: 'wǒ xū yào liú liàng.',
          en: 'I need mobile data.',
          fr: 'J’ai besoin de données mobiles.',
          audio: '/audio/phone-and-payment/pattern-03-example-01.mp3',
        },
        {
          fill: '一个手机号码',
          fillPinyin: 'yí gè shǒu jī hào mǎ',
          hanzi: '我需要一个手机号码。',
          pinyin: 'wǒ xū yào yí gè shǒu jī hào mǎ.',
          en: 'I need a phone number.',
          fr: 'J’ai besoin d’un numéro de téléphone.',
          audio: '/audio/phone-and-payment/pattern-03-example-02.mp3',
        },
        {
          fill: '更多流量',
          fillPinyin: 'gèng duō liú liàng',
          hanzi: '我需要更多流量。',
          pinyin: 'wǒ xū yào gèng duō liú liàng.',
          en: 'I need more data.',
          fr: 'J’ai besoin de plus de données.',
          audio: '/audio/phone-and-payment/pattern-03-example-03.mp3',
        },
      ],
    },
    {
      id: 'phone-and-payment-pattern-4',
      pattern: '……有多少流量？',
      pinyin: '... yǒu duō shǎo liú liàng?',
      meaning: {
        en: 'How much data does ... have?',
        fr: 'Combien de data a ... ?',
      },
      audio: '/audio/phone-and-payment/pattern-04.mp3',
      examples: [
        {
          fill: '这个套餐',
          fillPinyin: 'zhè ge tào cān',
          hanzi: '这个套餐有多少流量？',
          pinyin: 'zhè ge tào cān yǒu duō shǎo liú liàng?',
          en: 'How much data does this plan have?',
          fr: 'Combien de data ce forfait inclut-il ?',
          audio: '/audio/phone-and-payment/pattern-04-example-01.mp3',
        },
        {
          fill: '这个手机卡',
          fillPinyin: 'zhè ge shǒu jī kǎ',
          hanzi: '这个手机卡有多少流量？',
          pinyin: 'zhè ge shǒu jī kǎ yǒu duō shǎo liú liàng?',
          en: 'How much data does this SIM card have?',
          fr: 'Combien de données cette carte SIM inclut-elle ?',
          audio: '/audio/phone-and-payment/pattern-04-example-02.mp3',
        },
        {
          fill: '每月套餐',
          fillPinyin: 'měi yuè tào cān',
          hanzi: '每月套餐有多少流量？',
          pinyin: 'měi yuè tào cān yǒu duō shǎo liú liàng?',
          en: 'How much data does the monthly plan have?',
          fr: 'Combien de data le forfait mensuel inclut-il ?',
          audio: '/audio/phone-and-payment/pattern-04-example-03.mp3',
        },
      ],
    },
    {
      id: 'phone-and-payment-pattern-5',
      pattern: '怎么……？',
      pinyin: 'zěn me ... ?',
      meaning: {
        en: 'How do I ...?',
        fr: 'Comment ... ?',
      },
      audio: '/audio/phone-and-payment/pattern-05.mp3',
      examples: [
        {
          fill: '充值',
          fillPinyin: 'chōng zhí',
          hanzi: '怎么充值？',
          pinyin: 'zěn me chōng zhí?',
          en: 'How do I top up?',
          fr: 'Comment recharger ?',
          audio: '/audio/phone-and-payment/pattern-05-example-01.mp3',
        },
        {
          fill: '缴费',
          fillPinyin: 'jiǎo fèi',
          hanzi: '怎么缴费？',
          pinyin: 'zěn me jiǎo fèi?',
          en: 'How do I pay the bill?',
          fr: 'Comment payer la facture ?',
          audio: '/audio/phone-and-payment/pattern-05-example-02.mp3',
        },
        {
          fill: '使用',
          fillPinyin: 'shǐ yòng',
          hanzi: '怎么使用？',
          pinyin: 'zěn me shǐ yòng?',
          en: 'How do I use it?',
          fr: 'Comment l’utiliser ?',
          audio: '/audio/phone-and-payment/pattern-05-example-03.mp3',
        },
      ],
    }
    ],
  vocabulary: [
    {
      id: 'phone-and-payment-vocab-1',
      hanzi: '手机卡',
      pinyin: 'shǒu jī kǎ',
      audio: '/audio/phone-and-payment/vocab-01.mp3',
      meaning: {
        en: 'SIM card',
        fr: 'carte SIM',
      },
      explanation: {
        en: 'A SIM card connects your phone to a mobile network.',
        fr: 'Le mot pratique pour demander un service téléphonique après l\'arrivée.',
      },
    },
    {
      id: 'phone-and-payment-vocab-2',
      hanzi: '手机号码',
      pinyin: 'shǒu jī hào mǎ',
      audio: '/audio/phone-and-payment/vocab-02.mp3',
      meaning: {
        en: 'phone number',
        fr: 'numéro de téléphone',
      },
      explanation: {
        en: 'The number assigned to your mobile phone line.',
        fr: 'Reconnais-le quand quelqu\'un confirme le numéro lié au téléphone.',
      },
    },
    {
      id: 'phone-and-payment-vocab-3',
      hanzi: '支付',
      pinyin: 'zhī fù',
      audio: '/audio/phone-and-payment/vocab-03.mp3',
      meaning: {
        en: 'pay / payment',
        fr: 'payer / paiement',
      },
      explanation: {
        en: 'The act of paying for a product or service.',
        fr: 'Un mot central pour les questions de paiement mobile.',
      },
    },
    {
      id: 'phone-and-payment-vocab-4',
      hanzi: '现金',
      pinyin: 'xiàn jīn',
      audio: '/audio/phone-and-payment/vocab-04.mp3',
      meaning: {
        en: 'cash',
        fr: 'espèces',
      },
      explanation: {
        en: 'Physical money in the form of notes and coins.',
        fr: 'Une solution utile si le paiement mobile n\'est pas prêt.',
      },
    },
    {
      id: 'phone-and-payment-vocab-5',
      hanzi: '可以',
      pinyin: 'kě yǐ',
      audio: '/audio/phone-and-payment/vocab-05.mp3',
      meaning: {
        en: 'can / may',
        fr: 'pouvoir / être possible',
      },
      explanation: {
        en: 'A word used to say that something is possible or permitted.',
        fr: 'Utilise-le pour demander si une action ou un moyen de paiement est possible.',
      },
    },
    {
      id: 'phone-and-payment-vocab-6',
      hanzi: '流量',
      pinyin: 'liú liàng',
      audio: '/audio/phone-and-payment/vocab-06.mp3',
      meaning: {
        en: 'data / mobile data',
        fr: 'données mobiles',
      },
      explanation: {
        en: 'The amount of mobile internet usage. In China, it\'s commonly referred to as "data".',
        fr: 'La quantité de données Internet mobiles utilisées. En Chine, on parle généralement de « data ».',
      },
    },
    {
      id: 'phone-and-payment-vocab-7',
      hanzi: '套餐',
      pinyin: 'tào cān',
      audio: '/audio/phone-and-payment/vocab-07.mp3',
      meaning: {
        en: 'plan / package',
        fr: 'forfait',
      },
      explanation: {
        en: 'Service plans offered by telecom operators, including combinations of call minutes, SMS and data. Most plans auto-renew unless you change or cancel them. You can choose a plan based on your needs.',
        fr: 'Les forfaits proposés par les opérateurs télécoms, qui combinent notamment des minutes d’appel, des SMS et des données. La plupart se renouvellent automatiquement, sauf si vous les modifiez ou les résiliez. Vous pouvez choisir un forfait selon vos besoins.',
      },
    },
    {
      id: 'phone-and-payment-vocab-8',
      hanzi: '充值',
      pinyin: 'chōng zhí',
      audio: '/audio/phone-and-payment/vocab-08.mp3',
      meaning: { en: 'top up / recharge', fr: 'recharger' },
      explanation: { en: 'The act of adding credit to a phone account or prepaid service.', fr: 'L’action d’ajouter du crédit à un compte téléphonique ou à un service prépayé.' },
    },
    {
      id: 'phone-and-payment-vocab-9',
      hanzi: '微信',
      pinyin: 'wēi xìn',
      audio: '/audio/phone-and-payment/vocab-09.mp3',
      meaning: { en: 'WeChat', fr: 'WeChat' },
      explanation: { en: 'A messaging and payment app commonly used in China.', fr: 'Une application de messagerie et de paiement très utilisée en Chine.' },
    },
    {
      id: 'phone-and-payment-vocab-10',
      hanzi: '余额',
      pinyin: 'yú é',
      audio: '/audio/phone-and-payment/vocab-10.mp3',
      meaning: { en: 'account balance', fr: 'solde du compte' },
      explanation: { en: 'The amount of credit or money remaining in an account.', fr: 'Le montant de crédit ou d’argent restant sur un compte.' },
    },
    {
      id: 'phone-and-payment-vocab-11',
      hanzi: '话费',
      pinyin: 'huà fèi',
      audio: '/audio/phone-and-payment/vocab-11.mp3',
      meaning: {
        en: 'call charges / phone fees',
        fr: 'frais d’appel / frais de téléphone',
      },
      explanation: {
        en: 'The fees incurred for communication services.',
        fr: 'Les frais engagés pour les services de communication.',
      },
    },
  ],
  practice: {
    listening: [
      {
        id: 'phone-and-payment-listening-1',
        prompt: {
          en: 'Listen for the word that means SIM card.',
          fr: 'Écoute le mot qui signifie carte SIM.',
        },
        target: '手机卡',
        audio: '/audio/phone-and-payment/practice-listening-01.mp3',
        explanation: {
          en: '手机 = mobile phone｜卡 = card. Use it for the SIM card in this service exchange.',
          fr: '手机 = téléphone portable｜卡 = carte. Utilisez-le pour la carte SIM dans cet échange de service.',
        },
      },
      { id: 'phone-and-payment-listening-2', prompt: { en: 'Which phrase asks about data plans?', fr: 'Quelle phrase demande les forfaits data ?' }, target: '有什么流量套餐？', audio: '/audio/phone-and-payment/practice-listening-02.mp3', explanation: { en: '有 = to have / there is｜什么 = what｜流量 = data｜套餐 = plan. Use it to compare phone plan options.', fr: '有 = avoir / il y a｜什么 = quoi / que｜流量 = données｜套餐 = forfait. Utilisez-la pour comparer les forfaits téléphoniques.' } },
    ],
    speaking: [
      {
        id: 'phone-and-payment-speaking-1',
        prompt: {
          en: 'Ask whether phone payment is possible.',
          fr: 'Demande si le paiement par téléphone est possible.',
        },
        target: '可以用手机支付吗？',
        audio: '/audio/phone-and-payment/practice-speaking-01.mp3',
        explanation: {
          en: '可以 = can / may｜用 = to use｜手机 = mobile phone｜支付 = to pay｜吗 = question particle. Use it as the safest short way to check if mobile payment is accepted.',
          fr: '可以 = pouvoir｜用 = utiliser｜手机 = téléphone portable｜支付 = payer｜吗 = particule interrogative. Utilisez-la comme la manière courte la plus sûre de vérifier le paiement mobile.',
        },
      },
      { id: 'phone-and-payment-speaking-2', prompt: { en: 'Ask how to top up your phone.', fr: 'Demande comment recharger ton téléphone.' }, target: '怎么充值？', audio: '/audio/phone-and-payment/practice-speaking-02.mp3', explanation: { en: '怎么 = how｜充值 = to top up. Use it as the fastest way to ask how to add credit.', fr: '怎么 = comment｜充值 = recharger. Utilisez-la comme la façon la plus rapide de demander comment ajouter du crédit.' } },
    ],
    reading: [
      {
        id: 'phone-and-payment-reading-1',
        prompt: {
          en: 'Match 手机号码 with its meaning.',
          fr: 'Associe 手机号码 à son sens.',
        },
        target: '手机号码',
        audio: '/audio/phone-and-payment/practice-reading-01.mp3',
        explanation: {
          en: '手机 = mobile phone｜号码 = number. Use it for the phone number attached to your SIM.',
          fr: '手机 = téléphone portable｜号码 = numéro. Utilisez-le pour le numéro de téléphone lié à votre carte SIM.',
        },
      },
      { id: 'phone-and-payment-reading-2', prompt: { en: 'Match the payment app name.', fr: 'Associe le nom de l\'appli de paiement.' }, target: '微信', audio: '/audio/phone-and-payment/practice-reading-02.mp3', explanation: { en: '微 = tiny / micro｜信 = message. Use it for the most important app name to recognize in China.', fr: '微 = minuscule / micro｜信 = message. Utilisez-le pour le nom d’application le plus important à reconnaître en Chine.' } },
    ],
  },
  reviewCards: [
    {
      id: 'phone-and-payment-review-1',
      front: '手机卡',
      back: {
        en: 'SIM card',
        fr: 'carte SIM',
      },
        explanation: {
          en: '手机 = mobile phone｜卡 = card. Use it when asking for basic phone service.',
          fr: '手机 = téléphone portable｜卡 = carte. Utilisez-le pour demander un service téléphonique de base.',
        },
    },
    {
      id: 'phone-and-payment-review-2',
      front: '手机号码',
      back: {
        en: 'phone number',
        fr: 'numéro de téléphone',
      },
        explanation: {
          en: '手机 = mobile phone｜号码 = number. Use it for the number attached to your phone or SIM card.',
          fr: '手机 = téléphone portable｜号码 = numéro. Utilisez-le pour le numéro lié à votre téléphone ou à votre carte SIM.',
        },
    },
    {
      id: 'phone-and-payment-review-3',
      front: '可以用手机支付吗？',
      back: {
        en: 'Can I pay by phone?',
        fr: 'Puis-je payer avec mon téléphone ?',
      },
        explanation: {
          en: '可以 = can / may｜用 = to use｜手机 = mobile phone｜支付 = to pay｜吗 = question particle. Use it as a short practical question at shops and counters.',
          fr: '可以 = pouvoir｜用 = utiliser｜手机 = téléphone portable｜支付 = payer｜吗 = particule interrogative. Utilisez-la comme question courte et pratique dans les magasins et aux comptoirs.',
        },
    },
    { id: 'phone-and-payment-review-4', front: '流量', back: { en: 'mobile data', fr: 'données mobiles' }, explanation: { en: '流 = to flow｜量 = amount. Use it for mobile data.', fr: '流 = couler / circuler｜量 = quantité. Utilisez-le pour les données mobiles.' } },
    { id: 'phone-and-payment-review-5', front: '充值', back: { en: 'top up / recharge', fr: 'recharger' }, explanation: { en: '充 = to top up / fill｜值 = value. Use it to add credit to your phone.', fr: '充 = recharger / remplir｜值 = valeur. Utilisez-le pour ajouter du crédit à votre téléphone.' } },
    { id: 'phone-and-payment-review-6', front: '微信', back: { en: 'WeChat', fr: 'WeChat' }, explanation: { en: '微 = tiny / micro｜信 = message. Use it for the essential messaging and payment app in China.', fr: '微 = minuscule / micro｜信 = message. Utilisez-le pour l’application essentielle de messagerie et de paiement.' } },
  ],
}
