import type { LessonContent } from '../types.js'

export const restaurantOrderLesson: LessonContent = {
  id: 'restaurant-order',
  title: {
    en: '点餐 / Order a meal',
    fr: '点餐 / Commander un repas',
  },
  scenario: {
    en: 'Ask for a menu, order food and drinks, specify your preference and make the payment.',
    fr: 'Demander un menu, commander plats et boissons, préciser sa préférence et régler l\'addition.',
  },
  dialogue: {
    title: {
      en: 'Order noodles in a small restaurant',
      fr: 'Commander des nouilles dans un petit restaurant',
    },
    lines: [
      {
        id: 'restaurant-order-line-01',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '服务员！',
        pinyin: 'fú wù yuán!',
        translation: { en: 'Waiter!', fr: 'Serveur !' },
        explanation: { en: '服务员 = waiter. Use it to get a server\'s attention in a restaurant.', fr: '服务员 = serveur. Utilisez-le pour attirer l\'attention d\'un serveur au restaurant.' },
        audio: '/audio/restaurant-order/line-01.mp3',
      },
      {
        id: 'restaurant-order-line-02',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请给我菜单。',
        pinyin: 'qǐng gěi wǒ cài dān.',
        translation: { en: 'Can I have the menu, please?', fr: 'Puis-je avoir le menu, s\'il vous plaît ?' },
        explanation: { en: '请 = please｜给 = to give｜我 = me｜菜单 = menu. Use it to ask for the menu.', fr: '请 = s\'il vous plaît｜给 = donner｜我 = moi｜菜单 = menu. Utilisez-la pour demander le menu.' },
        audio: '/audio/restaurant-order/line-02.mp3',
      },
      {
        id: 'restaurant-order-line-03',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '可以点餐了吗？',
        pinyin: 'kě yǐ diǎn cān le ma?',
        translation: { en: 'Can I order now?', fr: 'Puis-je commander maintenant ?' },
        explanation: { en: '可以 = may/can｜点餐 = order food｜了 = now / change of state｜吗 = question particle. Use it when you are ready to order.', fr: '可以 = pouvoir｜点餐 = commander｜了 = maintenant / changement d’état｜吗 = particule interrogative. Utilisez-la lorsque vous êtes prêt à commander.' },
        audio: '/audio/restaurant-order/line-03.mp3',
      },
      {
        id: 'restaurant-order-line-04',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我要这个。',
        pinyin: 'wǒ yào zhè ge.',
        translation: { en: 'I want this one.', fr: 'Je veux ceci.' },
        explanation: { en: '我 = I｜要 = want｜这个 = this one. Use it to point at a dish and order it.', fr: '我 = je｜要 = vouloir｜这个 = celui-ci. Utilisez-la pour commander en montrant un plat.' },
        audio: '/audio/restaurant-order/line-04.mp3',
      },
      {
        id: 'restaurant-order-line-05',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我要一碗面条。',
        pinyin: 'wǒ yào yì wǎn miàn tiáo.',
        translation: { en: 'I’d like a bowl of noodles.', fr: 'Je voudrais un bol de nouilles.' },
        explanation: { en: '我 = I｜要 = want｜一 = one｜碗 = bowl｜面条 = noodles. Use it to order a bowl of noodles.', fr: '我 = je｜要 = vouloir｜一 = un｜碗 = bol｜面条 = nouilles. Utilisez-la pour commander un bol de nouilles.' },
        audio: '/audio/restaurant-order/line-05.mp3',
      },
      {
        id: 'restaurant-order-line-06',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '来一碗米饭。',
        pinyin: 'lái yì wǎn mǐ fàn.',
        translation: { en: 'A bowl of rice, please.', fr: 'Un bol de riz, s\'il vous plaît.' },
        explanation: { en: '来 = to bring/give me｜一 = one｜碗 = bowl｜米饭 = rice. Use it to order a bowl of rice.', fr: '来 = apporter｜一 = un｜碗 = bol｜米饭 = riz. Utilisez-la pour commander un bol de riz.' },
        audio: '/audio/restaurant-order/line-06.mp3',
      },
      {
        id: 'restaurant-order-line-07',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请给我一杯水。',
        pinyin: 'qǐng gěi wǒ yì bēi shuǐ.',
        translation: { en: 'Please give me a glass of water.', fr: 'Veuillez me donner un verre d’eau.' },
        explanation: { en: '请 = please｜给 = to give｜我 = me｜一 = one｜杯 = glass｜水 = water. Use it to ask for a glass of water.', fr: '请 = s\'il vous plaît｜给 = donner｜我 = moi｜一 = un｜杯 = verre｜水 = eau. Utilisez-la pour demander un verre d\'eau.' },
        audio: '/audio/restaurant-order/line-07.mp3',
      },
      {
        id: 'restaurant-order-line-08',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '不要辣。',
        pinyin: 'bú yào là.',
        translation: { en: 'Not spicy, please.', fr: 'Sans piment, s\'il vous plaît.' },
        explanation: { en: '不 = not｜要 = want｜辣 = spicy. Use it to ask for a dish without spice.', fr: '不 = ne pas｜要 = vouloir｜辣 = pimenté. Utilisez-la pour demander un plat sans piment.' },
        audio: '/audio/restaurant-order/line-08.mp3',
      },
      {
        id: 'restaurant-order-line-09',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '微辣。',
        pinyin: 'wēi là.',
        translation: { en: 'Mildly spicy.', fr: 'Légèrement épicé.' },
        explanation: { en: '微 = mild/slightly｜辣 = spicy. Use it to ask for a mild level of spice.', fr: '微 = léger/légèrement｜辣 = pimenté. Utilisez-la pour demander un niveau de piment léger.' },
        audio: '/audio/restaurant-order/line-09.mp3',
      },
      {
        id: 'restaurant-order-line-10',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我对花生过敏。',
        pinyin: 'wǒ duì huā shēng guò mǐn.',
        translation: { en: 'I am allergic to peanuts.', fr: 'Je suis allergique aux cacahuètes.' },
        explanation: { en: '我 = I｜对 = toward/to｜花生 = peanut｜过敏 = allergic. Use it to name a peanut allergy before ordering.', fr: '我 = je｜对 = envers/à｜花生 = cacahuète｜过敏 = allergique. Utilisez-la pour signaler une allergie avant de commander.' },
        audio: '/audio/restaurant-order/line-10.mp3',
      },
      {
        id: 'restaurant-order-line-11',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我是素食主义者。',
        pinyin: 'wǒ shì sù shí zhǔ yì zhě.',
        translation: { en: 'I am vegetarian.', fr: 'Je suis végétarien(ne).' },
        explanation: { en: '我 = I｜是 = am/to be｜素食主义 = vegetarianism｜者 = -ist/person. Use it to tell the server you are vegetarian.', fr: '我 = je｜是 = être｜素食主义 = végétarisme｜者 = personne/iste. Utilisez-la pour dire au serveur que vous êtes végétarien.' },
        audio: '/audio/restaurant-order/line-11.mp3',
      },
      {
        id: 'restaurant-order-line-12',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '您好，结账。',
        pinyin: 'nín hǎo, jié zhàng.',
        translation: { en: 'Hello, could I have the check, please?', fr: 'Bonjour, l\'addition, s\'il vous plaît.' },
        explanation: { en: '您 = you (formal)｜好 = good/hello｜结账 = to pay the bill. Use it to ask for the bill at the end of a meal.', fr: '您 = vous (forme polie)｜好 = bon/bonjour｜结账 = régler l\'addition. Utilisez-la pour demander l\'addition à la fin du repas.' },
        audio: '/audio/restaurant-order/line-12.mp3',
      },
      {
        id: 'restaurant-order-line-13',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我吃饱了。',
        pinyin: 'wǒ chī bǎo le.',
        translation: { en: 'I am full.', fr: 'Je suis rassasié(e).' },
        explanation: { en: '我 = I｜吃饱 = eat one’s fill / be full｜了 = change-of-state particle. Use it to let the server know you have eaten enough.', fr: '我 = je｜吃饱 = manger à sa faim / être rassasié｜了 = particule de changement d’état. Utilisez-la pour dire au serveur que vous avez assez mangé.' },
        audio: '/audio/restaurant-order/line-13.mp3',
      },
      {
        id: 'restaurant-order-line-14',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '可以打包带走吗？',
        pinyin: 'kě yǐ dǎ bāo dài zǒu ma?',
        translation: { en: 'Could you pack it for takeaway?', fr: 'Pouvez-vous l\'emballer pour emporter ?' },
        explanation: { en: '可以 = may/can｜打包 = to pack up｜带走 = to take away｜吗 = (question particle). Use it to ask if you can take the food away.', fr: '可以 = pouvoir｜打包 = emballer｜带走 = emporter｜吗 = (particule interrogative). Utilisez-la pour demander si vous pouvez emporter votre repas.' },
        audio: '/audio/restaurant-order/line-14.mp3',
      },
    ],
  },
    sentencePatterns: [
    {
      id: 'restaurant-order-pattern-1',
      pattern: '请给我……。',
      pinyin: 'qǐng gěi wǒ ... .',
      meaning: {
        en: 'Could I have ... please?',
        fr: 'Puis-je avoir ... ?',
      },
      audio: '/audio/restaurant-order/pattern-01.mp3',
      examples: [
        {
          fill: '菜单',
          fillPinyin: 'cài dān',
          hanzi: '请给我菜单。',
          pinyin: 'qǐng gěi wǒ cài dān.',
          en: 'Can I have the menu, please?',
          fr: 'Puis-je avoir le menu, s\'il vous plaît ?',
          audio: '/audio/restaurant-order/pattern-01-example-01.mp3',
        },
        {
          fill: '一杯水',
          fillPinyin: 'yì bēi shuǐ',
          hanzi: '请给我一杯水。',
          pinyin: 'qǐng gěi wǒ yì bēi shuǐ.',
          en: 'Can I have a glass of water, please?',
          fr: 'Puis-je avoir un verre d\'eau, s\'il vous plaît ?',
          audio: '/audio/restaurant-order/pattern-01-example-02.mp3',
        },
        {
          fill: '一碗米饭',
          fillPinyin: 'yì wǎn mǐ fàn',
          hanzi: '请给我一碗米饭。',
          pinyin: 'qǐng gěi wǒ yì wǎn mǐ fàn.',
          en: 'Can I have a bowl of rice, please?',
          fr: 'Puis-je avoir un bol de riz, s\'il vous plaît ?',
          audio: '/audio/restaurant-order/pattern-01-example-03.mp3',
        },
      ],
    },
    {
      id: 'restaurant-order-pattern-2',
      pattern: '我要一碗……。',
      pinyin: 'wǒ yào yì wǎn ... .',
      meaning: {
        en: 'A bowl of ..., please.',
        fr: 'Un bol de ..., s\'il vous plaît.',
      },
      audio: '/audio/restaurant-order/pattern-02.mp3',
      examples: [
        {
          fill: '面条',
          fillPinyin: 'miàn tiáo',
          hanzi: '我要一碗面条。',
          pinyin: 'wǒ yào yì wǎn miàn tiáo.',
          en: 'I want a bowl of noodles.',
          fr: 'Je veux un bol de nouilles.',
          audio: '/audio/restaurant-order/pattern-02-example-01.mp3',
        },
        {
          fill: '米饭',
          fillPinyin: 'mǐ fàn',
          hanzi: '我要一碗米饭。',
          pinyin: 'wǒ yào yì wǎn mǐ fàn.',
          en: 'I want a bowl of rice.',
          fr: 'Je veux un bol de riz.',
          audio: '/audio/restaurant-order/pattern-02-example-02.mp3',
        },
        {
          fill: '汤',
          fillPinyin: 'tāng',
          hanzi: '我要一碗汤。',
          pinyin: 'wǒ yào yì wǎn tāng.',
          en: 'I want a bowl of soup.',
          fr: 'Je veux un bol de soupe.',
          audio: '/audio/restaurant-order/pattern-02-example-03.mp3',
        },
      ],
    },
    {
      id: 'restaurant-order-pattern-3',
      pattern: '不要……。',
      pinyin: 'bú yào ... .',
      meaning: {
        en: 'No ..., please.',
        fr: 'Sans ..., s\'il vous plaît.',
      },
      audio: '/audio/restaurant-order/pattern-03.mp3',
      examples: [
        {
          fill: '辣',
          fillPinyin: 'là',
          hanzi: '不要辣。',
          pinyin: 'bú yào là.',
          en: 'No spice, please.',
          fr: 'Sans piment, s\'il vous plaît.',
          audio: '/audio/restaurant-order/pattern-03-example-01.mp3',
        },
        {
          fill: '葱',
          fillPinyin: 'cōng',
          hanzi: '不要葱。',
          pinyin: 'bú yào cōng.',
          en: 'No green onions, please.',
          fr: 'Sans oignons verts, s’il vous plaît.',
          audio: '/audio/restaurant-order/pattern-03-example-02.mp3',
        },
        {
          fill: '香菜',
          fillPinyin: 'xiāng cài',
          hanzi: '不要香菜。',
          pinyin: 'bú yào xiāng cài.',
          en: 'No cilantro, please.',
          fr: 'Sans coriandre, s\'il vous plaît.',
          audio: '/audio/restaurant-order/pattern-03-example-03.mp3',
        },
      ],
    },
    {
      id: 'restaurant-order-pattern-4',
      pattern: '我对……过敏。',
      pinyin: 'wǒ duì ... guò mǐn.',
      meaning: {
        en: 'I am allergic to ...',
        fr: 'Je suis allergique à ...',
      },
      audio: '/audio/restaurant-order/pattern-04.mp3',
      examples: [
        {
          fill: '花生',
          fillPinyin: 'huā shēng',
          hanzi: '我对花生过敏。',
          pinyin: 'wǒ duì huā shēng guò mǐn.',
          en: 'I am allergic to peanuts.',
          fr: 'Je suis allergique aux cacahuètes.',
          audio: '/audio/restaurant-order/pattern-04-example-01.mp3',
        },
        {
          fill: '海鲜',
          fillPinyin: 'hǎi xiān',
          hanzi: '我对海鲜过敏。',
          pinyin: 'wǒ duì hǎi xiān guò mǐn.',
          en: 'I am allergic to seafood.',
          fr: 'Je suis allergique aux fruits de mer.',
          audio: '/audio/restaurant-order/pattern-04-example-02.mp3',
        },
        {
          fill: '牛奶',
          fillPinyin: 'niú nǎi',
          hanzi: '我对牛奶过敏。',
          pinyin: 'wǒ duì niú nǎi guò mǐn.',
          en: 'I am allergic to milk.',
          fr: 'Je suis allergique au lait.',
          audio: '/audio/restaurant-order/pattern-04-example-03.mp3',
        },
      ],
    }
    ],
  vocabulary: [
    {
      id: 'restaurant-order-vocab-1',
      hanzi: '菜单',
      pinyin: 'cài dān',
      audio: '/audio/restaurant-order/vocab-01.mp3',
      meaning: {
        en: 'menu',
        fr: 'menu',
      },
      explanation: {
        en: 'The first word to ask for in a restaurant.',
        fr: 'Le premier mot à demander au restaurant.',
      },
    },
    {
      id: 'restaurant-order-vocab-2',
      hanzi: '牛肉面',
      pinyin: 'niú ròu miàn',
      audio: '/audio/restaurant-order/vocab-02.mp3',
      meaning: {
        en: 'beef noodles',
        fr: 'nouilles au bœuf',
      },
      explanation: {
        en: 'A common noodle dish made with beef.',
        fr: 'Un plat courant de nouilles au bœuf.',
      },
    },
    {
      id: 'restaurant-order-vocab-3',
      hanzi: '一碗',
      pinyin: 'yì wǎn',
      audio: '/audio/restaurant-order/vocab-03.mp3',
      meaning: {
        en: 'one bowl',
        fr: 'un bol',
      },
      explanation: {
        en: 'Use it when ordering noodles, rice, or soup by the bowl.',
        fr: 'Utilise-le pour commander des nouilles, du riz ou une soupe au bol.',
      },
    },
    {
      id: 'restaurant-order-vocab-4',
      hanzi: '辣',
      pinyin: 'là',
      audio: '/audio/restaurant-order/vocab-04.mp3',
      meaning: {
        en: 'spicy',
        fr: 'pimenté / épicé',
      },
      explanation: {
        en: 'Pair it with 不要 if you need no spice.',
        fr: 'Associe-le à 不要 si tu ne veux pas de piment.',
      },
    },
    {
      id: 'restaurant-order-vocab-5',
      hanzi: '筷子',
      pinyin: 'kuài zi',
      audio: '/audio/restaurant-order/vocab-05.mp3',
      meaning: {
        en: 'chopsticks',
        fr: 'baguettes',
      },
      explanation: {
        en: 'A useful table item to request with your meal.',
        fr: 'Un objet utile à demander avec le repas.',
      },
    },
    { id: 'restaurant-order-vocab-6', hanzi: '大份', pinyin: 'dà fèn', audio: '/audio/restaurant-order/vocab-06.mp3', meaning: { en: 'large portion', fr: 'grande portion' }, explanation: { en: 'Choose 大份 for a bigger serving.', fr: 'Choisis 大份 pour une plus grande portion.' } },
    { id: 'restaurant-order-vocab-7', hanzi: '小份', pinyin: 'xiǎo fèn', audio: '/audio/restaurant-order/vocab-07.mp3', meaning: { en: 'small portion', fr: 'petite portion' }, explanation: { en: 'Choose 小份 for a smaller serving.', fr: 'Choisis 小份 pour une plus petite portion.' } },
    { id: 'restaurant-order-vocab-8', hanzi: '可乐', pinyin: 'kě lè', audio: '/audio/restaurant-order/vocab-08.mp3', meaning: { en: 'cola', fr: 'cola' }, explanation: { en: 'A common drink to order in restaurants.', fr: 'Une boisson courante à commander au restaurant.' } },
    { id: 'restaurant-order-vocab-9', hanzi: '带走', pinyin: 'dài zǒu', audio: '/audio/restaurant-order/vocab-09.mp3', meaning: { en: 'take away', fr: 'à emporter' }, explanation: { en: 'Use it when you want to take the food with you.', fr: 'Utilise-le quand tu veux emporter la nourriture.' } },
    { id: 'restaurant-order-vocab-10', hanzi: '买单', pinyin: 'mǎi dān', audio: '/audio/restaurant-order/vocab-10.mp3', meaning: { en: 'pay the bill', fr: 'payer l\'addition' }, explanation: { en: 'Say 买单 to ask for the bill at the end of a meal.', fr: 'Dis 买单 pour demander l\'addition à la fin du repas.' } },
  ],
  practice: {
    listening: [
      {
        id: 'restaurant-order-listening-1',
        prompt: {
          en: 'Listen for the request to see the menu and order beef noodles.',
          fr: 'Écoute la demande du menu et la commande de nouilles au bœuf.',
        },
        target: '有菜单吗？我要一碗牛肉面。',
        audio: '/audio/restaurant-order/practice-listening-01.mp3',
        explanation: {
          en: '有 = do you have｜菜单 = menu｜吗 = (question particle)｜我 = I｜要 = want｜一 = one｜碗 = bowl｜牛肉 = beef｜面 = noodles. Use it to ask for the menu and order beef noodles.',
          fr: '有 = avoir｜菜单 = menu｜吗 = (particule interrogative)｜我 = je｜要 = vouloir｜一 = un｜碗 = bol｜牛肉 = bœuf｜面 = nouilles. Utilisez-la pour demander le menu et commander des nouilles au bœuf.',
        },
      },
      { id: 'restaurant-order-listening-2', prompt: { en: 'Which phrase means take away?', fr: 'Quelle phrase signifie à emporter ?' }, target: '带走', audio: '/audio/restaurant-order/practice-listening-02.mp3', explanation: { en: '带 = to carry｜走 = to go/away. Use it to take the food to go.', fr: '带 = emporter/porter｜走 = partir. Utilisez-le pour emporter la nourriture.' } },
    ],
    speaking: [
      {
        id: 'restaurant-order-speaking-1',
        prompt: {
          en: 'Say you want one bowl of beef noodles and no spice.',
          fr: 'Dis que tu veux un bol de nouilles au bœuf sans piment.',
        },
        target: '我要一碗牛肉面，不要辣。',
        audio: '/audio/restaurant-order/practice-speaking-01.mp3',
        explanation: {
          en: '我 = I｜要 = want｜一 = one｜碗 = bowl｜牛肉 = beef｜面 = noodles｜不 = not｜要 = want｜辣 = spicy. Use it to order a bowl of beef noodles without spice.',
          fr: '我 = je｜要 = vouloir｜一 = un｜碗 = bol｜牛肉 = bœuf｜面 = nouilles｜不 = ne pas｜要 = vouloir｜辣 = pimenté. Utilisez-la pour commander un bol de nouilles au bœuf sans piment.',
        },
      },
      { id: 'restaurant-order-speaking-2', prompt: { en: 'Ask if they have cola.', fr: 'Demande s\'ils ont du cola.' }, target: '有可乐吗？', audio: '/audio/restaurant-order/practice-speaking-02.mp3', explanation: { en: '有 = do you have｜可乐 = cola｜吗 = (question particle). Use it to ask if they have cola.', fr: '有 = avoir｜可乐 = cola｜吗 = (particule interrogative). Utilisez-la pour demander s\'ils ont du cola.' } },
    ],
    reading: [
      {
        id: 'restaurant-order-reading-1',
        prompt: {
          en: 'Match the total-price question on a small bill.',
          fr: 'Associe la question du prix total sur une petite addition.',
        },
        target: '一共多少钱？',
        audio: '/audio/restaurant-order/practice-reading-01.mp3',
        explanation: {
          en: '一共 = in total｜多少 = how much｜钱 = money. Use it to ask for the total price.',
          fr: '一共 = au total｜多少 = combien｜钱 = argent. Utilisez-la pour demander le prix total.',
        },
      },
      { id: 'restaurant-order-reading-2', prompt: { en: 'Match the word for paying the bill.', fr: 'Associe le mot pour payer l\'addition.' }, target: '买单', audio: '/audio/restaurant-order/practice-reading-02.mp3', explanation: { en: '买 = to buy/pay｜单 = bill. Use it to ask for the check.', fr: '买 = acheter/payer｜单 = addition. Utilisez-le pour demander l\'addition.' } },
    ],
  },
  reviewCards: [
    {
      id: 'restaurant-order-review-1',
      front: '菜单',
      back: {
        en: 'menu',
        fr: 'menu',
      },
      explanation: {
        en: '菜单 = menu. Use it to ask for the menu.',
        fr: '菜单 = menu. Utilisez-le pour demander le menu.',
      },
    },
    {
      id: 'restaurant-order-review-2',
      front: '牛肉面',
      back: {
        en: 'beef noodles',
        fr: 'nouilles au bœuf',
      },
      explanation: {
        en: '牛 = beef｜肉 = meat｜面 = noodles. Use it to order beef noodles.',
        fr: '牛 = bœuf｜肉 = viande｜面 = nouilles. Utilisez-le pour commander des nouilles au bœuf.',
      },
    },
    {
      id: 'restaurant-order-review-3',
      front: '不要辣',
      back: {
        en: 'not spicy / no chili',
        fr: 'sans piment',
      },
      explanation: {
        en: '不 = not｜要 = want｜辣 = spicy. Use it to ask for a dish without spice.',
        fr: '不 = ne pas｜要 = vouloir｜辣 = pimenté. Utilisez-le pour demander un plat sans piment.',
      },
    },
    { id: 'restaurant-order-review-4', front: '大份 / 小份', back: { en: 'large / small portion', fr: 'grande / petite portion' }, explanation: { en: '大 = big/large｜份 = portion｜小 = small｜份 = portion. Use it to choose your portion size when ordering.', fr: '大 = grand/grande｜份 = portion｜小 = petit/petite｜份 = portion. Utilisez-le pour choisir la taille de votre portion en commandant.' } },
    { id: 'restaurant-order-review-5', front: '带走', back: { en: 'take away', fr: 'à emporter' }, explanation: { en: '带 = to carry｜走 = to go/away. Use it to take the food with you.', fr: '带 = emporter/porter｜走 = partir. Utilisez-le pour emporter la nourriture.' } },
    { id: 'restaurant-order-review-6', front: '买单', back: { en: 'pay the bill', fr: 'payer l\'addition' }, explanation: { en: '买 = to buy/pay｜单 = bill. Use it to ask the server for the check.', fr: '买 = acheter/payer｜单 = addition. Utilisez-le pour demander l\'addition au serveur.' } },
  ],
}
