import type { LessonContent } from '../types.js'

export const trainStationTicketLesson: LessonContent = {
  id: 'train-station-ticket',
  title: {
    en: '坐火车 / Take the train',
    fr: '坐火车 / Prendre le train',
  },
  scenario: {
    en: 'Most train tickets are booked online, but these phrases help you navigate the station.',
    fr: 'La plupart des billets de train se réservent en ligne, mais ces phrases t\'aident à te repérer en gare.',
  },
  dialogue: {
    title: {
      en: 'Buy a train ticket and find your platform',
      fr: 'Acheter un billet de train et trouver son quai',
    },
    lines: [
      {
        id: 'train-station-ticket-line-01',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '火车站在哪里？',
        pinyin: 'Huǒchēzhàn zài nǎlǐ?',
        translation: { en: 'Where is the train station?', fr: 'Où est la gare ?' },
        explanation: { en: 'Ask 在哪里 to find the station, ticket office, or dining car.', fr: 'Demande 在哪里 pour trouver la gare, le guichet ou la voiture-restaurant.' },
        audio: '/audio/train-station-ticket/line-01.mp3',
      },
      {
        id: 'train-station-ticket-line-02',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '售票处在哪里？',
        pinyin: 'Shòupiàochù zài nǎlǐ?',
        translation: { en: 'Where is the ticket office?', fr: 'Où est le guichet de billets ?' },
        explanation: { en: 'Ask 售票处在哪里 to find the ticket office at the station.', fr: 'Demande 售票处在哪里 pour trouver le guichet de billets en gare.' },
        audio: '/audio/train-station-ticket/line-02.mp3',
      },
      {
        id: 'train-station-ticket-line-03',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我要一张去[北京]的票。',
        pinyin: 'Wǒ yào yì zhāng qù [Běijīng] de piào.',
        translation: { en: 'I want to buy one ticket to [Beijing].', fr: 'Je veux acheter un billet pour [Beijing].' },
        explanation: { en: 'Swap in the city name for 北京 to name your destination.', fr: 'Remplace 北京 par le nom de ta ville pour indiquer ta destination.' },
        audio: '/audio/train-station-ticket/line-03.mp3',
      },
      {
        id: 'train-station-ticket-line-04',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '这是我的护照。',
        pinyin: 'Zhè shì wǒ de hùzhào.',
        translation: { en: 'This is my passport.', fr: 'Voici mon passeport.' },
        explanation: { en: 'Hand over your passport with 这是我的护照 when buying a ticket.', fr: 'Présente ton passeport avec 这是我的护照 quand tu achètes un billet.' },
        audio: '/audio/train-station-ticket/line-04.mp3',
      },
      {
        id: 'train-station-ticket-line-05',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '火车几点开？',
        pinyin: 'Huǒchē jǐ diǎn kāi?',
        translation: { en: 'What time does the train leave?', fr: 'À quelle heure part le train ?' },
        explanation: { en: 'Ask 几点开 to check when the train departs.', fr: 'Demande 几点开 pour vérifier l\'heure de départ du train.' },
        audio: '/audio/train-station-ticket/line-05.mp3',
      },
      {
        id: 'train-station-ticket-line-06',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '餐车在哪里？',
        pinyin: 'Cānchē zài nǎlǐ?',
        translation: { en: 'Where is the dining car?', fr: 'Où est la voiture-restaurant ?' },
        explanation: { en: 'Ask 餐车在哪里 to find the dining car on the train.', fr: 'Demande 餐车在哪里 pour trouver la voiture-restaurant dans le train.' },
        audio: '/audio/train-station-ticket/line-06.mp3',
      },
      {
        id: 'train-station-ticket-line-07',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '火车晚点了吗？',
        pinyin: 'Huǒchē wǎndiǎn le ma?',
        translation: { en: 'Is the train delayed?', fr: 'Le train est-il en retard ?' },
        explanation: { en: 'Ask 晚点了吗 to check if the train is running late.', fr: 'Demande 晚点了吗 pour vérifier si le train est en retard.' },
        audio: '/audio/train-station-ticket/line-07.mp3',
      },
      {
        id: 'train-station-ticket-line-08',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '请问怎么换乘？',
        pinyin: 'Qǐngwèn zěnme huànchéng?',
        translation: { en: 'How do I make a transit?', fr: 'Comment faire une correspondance ?' },
        explanation: { en: 'Ask 怎么换乘 when you need to change trains.', fr: 'Demande 怎么换乘 quand tu dois changer de train.' },
        audio: '/audio/train-station-ticket/line-08.mp3',
      },
      {
        id: 'train-station-ticket-line-09',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我误车了。',
        pinyin: 'Wǒ wùchē le.',
        translation: { en: 'I missed my train.', fr: 'J\'ai raté mon train.' },
        explanation: { en: 'Say 我误车了 to tell staff you missed your train.', fr: 'Dis 我误车了 pour dire au personnel que tu as raté ton train.' },
        audio: '/audio/train-station-ticket/line-09.mp3',
      },
      {
        id: 'train-station-ticket-line-10',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '我没赶上火车。',
        pinyin: 'Wǒ méi gǎnshàng huǒchē.',
        translation: { en: 'I missed my train.', fr: 'J\'ai raté le train.' },
        explanation: { en: 'Another way to say 我没赶上火车 when you arrived too late.', fr: 'Une autre façon de dire que tu es arrivé trop tard pour le train.' },
        audio: '/audio/train-station-ticket/line-10.mp3',
      },
      {
        id: 'train-station-ticket-line-11',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '能改签下一辆车吗？',
        pinyin: 'Néng gǎiqiān xià yíliàngchē ma?',
        translation: { en: 'Can I change my ticket for a later train?', fr: 'Puis-je modifier mon billet pour un train suivant ?' },
        explanation: { en: 'Ask 能改签 to exchange your ticket for a later train.', fr: 'Demande 能改签 pour échanger ton billet contre un train suivant.' },
        audio: '/audio/train-station-ticket/line-11.mp3',
      },
      {
        id: 'train-station-ticket-line-12',
        speaker: { en: 'Traveler', fr: 'Voyageur' },
        hanzi: '如何退票退款呢？',
        pinyin: 'Rúhé tuìpiào tuìkuǎn ne?',
        translation: { en: 'How can I get ticket cancellation and refund?', fr: 'Comment obtenir l\'annulation et le remboursement du billet ?' },
        explanation: { en: 'Ask 如何退票退款 to learn how to cancel and get a refund.', fr: 'Demande 如何退票退款 pour savoir comment annuler et te faire rembourser.' },
        audio: '/audio/train-station-ticket/line-12.mp3',
      },
    ],
  },
    sentencePatterns: [
    {
      id: 'train-station-ticket-pattern-1',
      pattern: '……在哪里？',
      pinyin: '... zài nǎlǐ?',
      meaning: {
        en: 'Where is ...?',
        fr: 'Où est ... ?',
      },
      audio: '/audio/train-station-ticket/pattern-01.mp3',
      examples: [
        {
          fill: '火车站',
          fillPinyin: 'huǒchēzhàn',
          hanzi: '火车站在哪里？',
          pinyin: 'Huǒchēzhàn zài nǎlǐ?',
          en: 'train station',
          fr: 'la gare',
        },
        {
          fill: '售票处',
          fillPinyin: 'shòupiàochù',
          hanzi: '售票处在哪里？',
          pinyin: 'Shòupiàochù zài nǎlǐ?',
          en: 'ticket office',
          fr: 'le guichet',
        },
        {
          fill: '餐车',
          fillPinyin: 'cānchē',
          hanzi: '餐车在哪里？',
          pinyin: 'Cānchē zài nǎlǐ?',
          en: 'dining car',
          fr: 'la voiture-restaurant',
        },
      ],
    },
    {
      id: 'train-station-ticket-pattern-2',
      pattern: '我要一张去……的票。',
      pinyin: 'Wǒ yào yì zhāng qù ... de piào.',
      meaning: {
        en: 'I want to buy one ticket to ...',
        fr: 'Je veux acheter un billet pour ...',
      },
      audio: '/audio/train-station-ticket/pattern-02.mp3',
      examples: [
        {
          fill: '北京',
          fillPinyin: 'Běijīng',
          hanzi: '我要一张去北京的票。',
          pinyin: 'Wǒ yào yì zhāng qù Běijīng de piào.',
          en: 'Beijing',
          fr: 'Pékin',
        },
        {
          fill: '上海',
          fillPinyin: 'Shànghǎi',
          hanzi: '我要一张去上海的票。',
          pinyin: 'Wǒ yào yì zhāng qù Shànghǎi de piào.',
          en: 'Shanghai',
          fr: 'Shanghai',
        },
        {
          fill: '广州',
          fillPinyin: 'Guǎngzhōu',
          hanzi: '我要一张去广州的票。',
          pinyin: 'Wǒ yào yì zhāng qù Guǎngzhōu de piào.',
          en: 'Guangzhou',
          fr: 'Canton',
        },
      ],
    },
    {
      id: 'train-station-ticket-pattern-3',
      pattern: '……几点开？',
      pinyin: '... jǐ diǎn kāi?',
      meaning: {
        en: 'What time does ... leave?',
        fr: 'À quelle heure part ... ?',
      },
      audio: '/audio/train-station-ticket/pattern-03.mp3',
      examples: [
        {
          fill: '火车',
          fillPinyin: 'huǒchē',
          hanzi: '火车几点开？',
          pinyin: 'Huǒchē jǐ diǎn kāi?',
          en: 'the train',
          fr: 'le train',
        },
        {
          fill: '高铁',
          fillPinyin: 'gāotiě',
          hanzi: '高铁几点开？',
          pinyin: 'Gāotiě jǐ diǎn kāi?',
          en: 'the high-speed train',
          fr: 'le TGV',
        },
        {
          fill: '动车',
          fillPinyin: 'dòngchē',
          hanzi: '动车几点开？',
          pinyin: 'Dòngchē jǐ diǎn kāi?',
          en: 'the bullet train',
          fr: 'le train rapide',
        },
      ],
    },
    {
      id: 'train-station-ticket-pattern-4',
      pattern: '……晚点了吗？',
      pinyin: '... wǎndiǎn le ma?',
      meaning: {
        en: 'Is ... delayed?',
        fr: '... est-il en retard ?',
      },
      audio: '/audio/train-station-ticket/pattern-04.mp3',
      examples: [
        {
          fill: '火车',
          fillPinyin: 'huǒchē',
          hanzi: '火车晚点了吗？',
          pinyin: 'Huǒchē wǎndiǎn le ma?',
          en: 'the train',
          fr: 'le train',
        },
        {
          fill: '高铁',
          fillPinyin: 'gāotiě',
          hanzi: '高铁晚点了吗？',
          pinyin: 'Gāotiě wǎndiǎn le ma?',
          en: 'the high-speed train',
          fr: 'le TGV',
        },
      ],
    },
    {
      id: 'train-station-ticket-pattern-5',
      pattern: '怎么换乘？',
      pinyin: 'Zěnme huànchéng?',
      meaning: {
        en: 'How do I make a transit?',
        fr: 'Comment faire une correspondance ?',
      },
      audio: '/audio/train-station-ticket/pattern-05.mp3',
    },
    {
      id: 'train-station-ticket-pattern-6',
      pattern: '售票处在哪里？',
      pinyin: 'Shòupiàochù zài nǎlǐ?',
      meaning: {
        en: 'Where is the ticket office?',
        fr: 'Où est le guichet de billets ?',
      },
    },
    {
      id: 'train-station-ticket-pattern-7',
      pattern: '这是我的护照。',
      pinyin: 'Zhè shì wǒ de hùzhào.',
      meaning: {
        en: 'This is my passport.',
        fr: 'Voici mon passeport.',
      },
    },
    {
      id: 'train-station-ticket-pattern-8',
      pattern: '餐车在哪里？',
      pinyin: 'Cānchē zài nǎlǐ?',
      meaning: {
        en: 'Where is the dining car?',
        fr: 'Où est la voiture-restaurant ?',
      },
    },
    {
      id: 'train-station-ticket-pattern-9',
      pattern: '我误车了。',
      pinyin: 'Wǒ wù chē le.',
      meaning: {
        en: 'I missed my train.',
        fr: 'J\'ai raté mon train.',
      },
    },
    {
      id: 'train-station-ticket-pattern-10',
      pattern: '我没赶上火车。',
      pinyin: 'Wǒ méi gǎnshàng huǒchē.',
      meaning: {
        en: 'I missed the train.',
        fr: 'J\'ai raté le train.',
      },
    },
    {
      id: 'train-station-ticket-pattern-11',
      pattern: '能改签下一辆车吗？',
      pinyin: 'Néng gǎiqiān xià yí liàng chē ma?',
      meaning: {
        en: 'Can I change my ticket for a later train?',
        fr: 'Puis-je modifier mon billet pour un train suivant ?',
      },
    },
    {
      id: 'train-station-ticket-pattern-12',
      pattern: '如何退票退款呢？',
      pinyin: 'Rúhé tuìpiào tuìkuǎn ne?',
      meaning: {
        en: 'How can I get a ticket cancellation and refund?',
        fr: 'Comment obtenir l\'annulation et le remboursement du billet ?',
      },
    },
  ],
  vocabulary: [
    {
      id: 'train-station-ticket-vocab-1',
      hanzi: '火车站',
      pinyin: 'huǒchēzhàn',
      audio: '/audio/train-station-ticket/vocab-01.mp3',
      meaning: {
        en: 'train station',
        fr: 'gare',
      },
      explanation: {
        en: 'The place for this capstone ticketing scene.',
        fr: 'Le lieu de cette scène finale d\'achat de billet.',
      },
    },
    {
      id: 'train-station-ticket-vocab-2',
      hanzi: '车票',
      pinyin: 'chēpiào',
      audio: '/audio/train-station-ticket/vocab-02.mp3',
      meaning: {
        en: 'train ticket / vehicle ticket',
        fr: 'billet de train / ticket de transport',
      },
      explanation: {
        en: 'A ticket word you will see at stations.',
        fr: 'Un mot de billet que tu verras en gare.',
      },
    },
    {
      id: 'train-station-ticket-vocab-3',
      hanzi: '上海',
      pinyin: 'Shànghǎi',
      audio: '/audio/train-station-ticket/vocab-03.mp3',
      meaning: {
        en: 'Shanghai',
        fr: 'Shanghai',
      },
      explanation: {
        en: 'The model destination in the ticket request.',
        fr: 'La destination modèle dans la demande de billet.',
      },
    },
    {
      id: 'train-station-ticket-vocab-4',
      hanzi: '今天',
      pinyin: 'jīntiān',
      audio: '/audio/train-station-ticket/vocab-04.mp3',
      meaning: {
        en: 'today',
        fr: 'aujourd\'hui',
      },
      explanation: {
        en: 'The date answer paired with 明天.',
        fr: 'La réponse de date associée à 明天.',
      },
    },
    {
      id: 'train-station-ticket-vocab-5',
      hanzi: '出发',
      pinyin: 'chūfā',
      audio: '/audio/train-station-ticket/vocab-05.mp3',
      meaning: {
        en: 'depart',
        fr: 'partir / départ',
      },
      explanation: {
        en: 'The action word for the train leaving.',
        fr: 'Le mot d\'action pour le départ du train.',
      },
    },
    { id: 'train-station-ticket-vocab-6', hanzi: '硬座', pinyin: 'yìngzuò', audio: '/audio/train-station-ticket/vocab-06.mp3', meaning: { en: 'hard seat (basic class)', fr: 'place dure (classe de base)' }, explanation: { en: 'The most common and affordable train seat type.', fr: 'Le type de place le plus courant et abordable en train.' } },
    { id: 'train-station-ticket-vocab-7', hanzi: '软座', pinyin: 'ruǎnzuò', audio: '/audio/train-station-ticket/vocab-07.mp3', meaning: { en: 'soft seat (comfort class)', fr: 'place molle (classe confort)' }, explanation: { en: 'A more comfortable seat option that costs a bit more.', fr: 'Une option de place plus confortable qui coûte un peu plus cher.' } },
    { id: 'train-station-ticket-vocab-8', hanzi: '站台', pinyin: 'zhàntái', audio: '/audio/train-station-ticket/vocab-08.mp3', meaning: { en: 'platform', fr: 'quai' }, explanation: { en: 'The place where you board the train.', fr: 'L\'endroit où tu montes dans le train.' } },
    { id: 'train-station-ticket-vocab-9', hanzi: '晚点', pinyin: 'wǎndiǎn', audio: '/audio/train-station-ticket/vocab-09.mp3', meaning: { en: 'delay / late', fr: 'retard / en retard' }, explanation: { en: 'A word you will see on station displays if a train is late.', fr: 'Un mot que tu verras sur les écrans de gare si un train est en retard.' } },
    { id: 'train-station-ticket-vocab-10', hanzi: '护照', pinyin: 'hùzhào', audio: '/audio/train-station-ticket/vocab-10.mp3', meaning: { en: 'passport', fr: 'passeport' }, explanation: { en: 'You need it for buying long-distance train tickets.', fr: 'Tu en as besoin pour acheter des billets de train longue distance.' } },
    { id: 'train-station-ticket-vocab-11', hanzi: '进站口', pinyin: 'jìnzhànkǒu', audio: '/audio/train-station-ticket/vocab-11.mp3', meaning: { en: 'entrance', fr: 'entrée' }, explanation: { en: 'The entrance you use to go into the station.', fr: 'L\'entrée que tu utilises pour entrer dans la gare.' } },
    { id: 'train-station-ticket-vocab-12', hanzi: '人工通道', pinyin: 'réngōng tōngdào', audio: '/audio/train-station-ticket/vocab-12.mp3', meaning: { en: 'manual lane', fr: 'voie manuelle' }, explanation: { en: 'Use this if automated gates do not read your passport.', fr: 'Utilise cette voie si les portiques automatiques ne lisent pas ton passeport.' } },
    { id: 'train-station-ticket-vocab-13', hanzi: '检票口', pinyin: 'jiǎnpiàokǒu', audio: '/audio/train-station-ticket/vocab-13.mp3', meaning: { en: 'ticket check gate', fr: 'portique de contrôle des billets' }, explanation: { en: 'The gate where your ticket is checked before the platform.', fr: 'Le portique où l\'on vérifie ton billet avant le quai.' } },
    { id: 'train-station-ticket-vocab-14', hanzi: '车厢号', pinyin: 'chēxiānghào', audio: '/audio/train-station-ticket/vocab-14.mp3', meaning: { en: 'carriage number', fr: 'numéro de voiture' }, explanation: { en: 'Find this number on your ticket to locate your carriage.', fr: 'Trouve ce numéro sur ton billet pour localiser ta voiture.' } },
    { id: 'train-station-ticket-vocab-15', hanzi: '座位号', pinyin: 'zuòwèihào', audio: '/audio/train-station-ticket/vocab-15.mp3', meaning: { en: 'seat number', fr: 'numéro de siège' }, explanation: { en: 'Use this number to find your exact seat on the train.', fr: 'Utilise ce numéro pour trouver ta place exacte dans le train.' } },
  ],
  practice: {
    listening: [
      {
        id: 'train-station-ticket-listening-1',
        prompt: {
          en: 'Listen for the ticket to Shanghai.',
          fr: 'Écoute le billet pour Shanghai.',
        },
        target: '我想买一张去上海的票。',
        audio: '/audio/train-station-ticket/practice-listening-01.mp3',
        explanation: {
          en: 'The destination follows 去 and comes before 的票.',
          fr: 'La destination suit 去 et vient avant 的票.',
        },
      },
      { id: 'train-station-ticket-listening-2', prompt: { en: 'Which phrase says the train won\'t be delayed?', fr: 'Quelle phrase dit que le train n\'aura pas de retard ?' }, target: '不会晚点。', audio: '/audio/train-station-ticket/practice-listening-02.mp3', explanation: { en: '不会晚点 reassures you the train is on schedule.', fr: '不会晚点 te rassure que le train est à l\'heure.' } },
    ],
    speaking: [
      {
        id: 'train-station-ticket-speaking-1',
        prompt: {
          en: 'Say that you want to buy a ticket to Shanghai.',
          fr: 'Dis que tu veux acheter un billet pour Shanghai.',
        },
        target: '我想买一张去上海的票。',
        audio: '/audio/train-station-ticket/practice-speaking-01.mp3',
        explanation: {
          en: 'This is the core capstone ticketing sentence.',
          fr: 'C\'est la phrase principale de billetterie finale.',
        },
      },
      { id: 'train-station-ticket-speaking-2', prompt: { en: 'Ask which platform the train is at.', fr: 'Demande sur quel quai se trouve le train.' }, target: '在哪个站台？', audio: '/audio/train-station-ticket/practice-speaking-02.mp3', explanation: { en: 'A key question after you have your ticket.', fr: 'Une question clé après avoir obtenu ton billet.' } },
    ],
    reading: [
      {
        id: 'train-station-ticket-reading-1',
        prompt: {
          en: 'Read the departure time.',
          fr: 'Lis l\'heure de départ.',
        },
        target: '三点出发。',
        audio: '/audio/train-station-ticket/practice-reading-01.mp3',
        explanation: {
          en: 'Catch the number before 点 and 出发.',
          fr: 'Repère le nombre avant 点 et 出发.',
        },
      },
      { id: 'train-station-ticket-reading-2', prompt: { en: 'Match the word for platform.', fr: 'Associe le mot pour quai.' }, target: '站台', audio: '/audio/train-station-ticket/practice-reading-02.mp3', explanation: { en: '站台 is the platform where you board. Look for it on signs.', fr: '站台 est le quai où tu embarques. Cherche-le sur les panneaux.' } },
    ],
  },
  reviewCards: [
    {
      id: 'train-station-ticket-review-1',
      front: '火车站',
      back: {
        en: 'train station',
        fr: 'gare',
      },
      explanation: {
        en: 'The setting for buying the ticket.',
        fr: 'Le lieu où acheter le billet.',
      },
    },
    {
      id: 'train-station-ticket-review-2',
      front: '车票',
      back: {
        en: 'ticket',
        fr: 'billet',
      },
      explanation: {
        en: 'A station ticket word.',
        fr: 'Un mot de billet en gare.',
      },
    },
    {
      id: 'train-station-ticket-review-3',
      front: '三点出发',
      back: {
        en: 'departs at three o\'clock',
        fr: 'départ à trois heures',
      },
      explanation: {
        en: 'A compact phrase for the departure time.',
        fr: 'Une phrase compacte pour l\'heure de départ.',
      },
    },
    { id: 'train-station-ticket-review-4', front: '硬座', back: { en: 'hard seat', fr: 'place dure' }, explanation: { en: 'The standard train seat class in China.', fr: 'La classe de place standard en train en Chine.' } },
    { id: 'train-station-ticket-review-5', front: '站台', back: { en: 'platform', fr: 'quai' }, explanation: { en: 'Find this word on signs to locate your boarding area.', fr: 'Trouve ce mot sur les panneaux pour localiser ta zone d\'embarquement.' } },
    { id: 'train-station-ticket-review-6', front: '晚点', back: { en: 'delay', fr: 'retard' }, explanation: { en: 'Watch for this word on departure boards.', fr: 'Surveille ce mot sur les panneaux de départ.' } },
  ],
}
